export const permissionsLessNodeRegistryAbi = [
//   { inputs: [], stateMutability: 'nonpayable', type: 'constructor' },
//   { inputs: [], name: 'CallerNotExistingRewardAddress', type: 'error' },
//   { inputs: [], name: 'CallerNotManager', type: 'error' },
//   { inputs: [], name: 'CallerNotNewRewardAddress', type: 'error' },
//   { inputs: [], name: 'CallerNotOperator', type: 'error' },
//   { inputs: [], name: 'CallerNotStaderContract', type: 'error' },
//   { inputs: [], name: 'CooldownNotComplete', type: 'error' },
//   { inputs: [], name: 'DuplicatePoolIDOrPoolNotAdded', type: 'error' },
//   { inputs: [], name: 'InSufficientBalance', type: 'error' },
//   { inputs: [], name: 'InvalidBondEthValue', type: 'error' },
//   { inputs: [], name: 'InvalidKeyCount', type: 'error' },
//   { inputs: [], name: 'InvalidStartAndEndIndex', type: 'error' },
//   { inputs: [], name: 'MaxKeyLimitExceed', type: 'error' },
//   { inputs: [], name: 'MaxKeyLimitReached', type: 'error' },
//   { inputs: [], name: 'MisMatchingInputKeysSize', type: 'error' },
//   { inputs: [], name: 'NoChangeInState', type: 'error' },
//   { inputs: [], name: 'NotEnoughSDCollateral', type: 'error' },
//   { inputs: [], name: 'OperatorAlreadyOnBoardedInProtocol', type: 'error' },
//   { inputs: [], name: 'OperatorIsDeactivate', type: 'error' },
//   { inputs: [], name: 'OperatorNotOnBoarded', type: 'error' },
//   { inputs: [], name: 'PageNumberIsZero', type: 'error' },
//   { inputs: [], name: 'PubkeyAlreadyExist', type: 'error' },
//   { inputs: [], name: 'TooManyVerifiedKeysReported', type: 'error' },
//   { inputs: [], name: 'TooManyWithdrawnKeysReported', type: 'error' },
//   { inputs: [], name: 'TransferFailed', type: 'error' },
//   { inputs: [], name: 'UNEXPECTED_STATUS', type: 'error' },
//   { inputs: [], name: 'ZeroAddress', type: 'error' },
//   {
//     anonymous: false,
//     inputs: [
//       {
//         indexed: true,
//         internalType: 'address',
//         name: 'nodeOperator',
//         type: 'address',
//       },
//       { indexed: false, internalType: 'bytes', name: 'pubkey', type: 'bytes' },
//       {
//         indexed: false,
//         internalType: 'uint256',
//         name: 'validatorId',
//         type: 'uint256',
//       },
//     ],
//     name: 'AddedValidatorKey',
//     type: 'event',
//   },
//   {
//     anonymous: false,
//     inputs: [
//       {
//         indexed: false,
//         internalType: 'uint256',
//         name: 'totalActiveValidatorCount',
//         type: 'uint256',
//       },
//     ],
//     name: 'DecreasedTotalActiveValidatorCount',
//     type: 'event',
//   },
//   {
//     anonymous: false,
//     inputs: [
//       {
//         indexed: false,
//         internalType: 'uint256',
//         name: 'totalActiveValidatorCount',
//         type: 'uint256',
//       },
//     ],
//     name: 'IncreasedTotalActiveValidatorCount',
//     type: 'event',
//   },
//   {
//     anonymous: false,
//     inputs: [
//       { indexed: false, internalType: 'uint8', name: 'version', type: 'uint8' },
//     ],
//     name: 'Initialized',
//     type: 'event',
//   },
//   {
//     anonymous: false,
//     inputs: [
//       {
//         indexed: true,
//         internalType: 'address',
//         name: 'nodeOperator',
//         type: 'address',
//       },
//       {
//         indexed: false,
//         internalType: 'address',
//         name: 'nodeRewardAddress',
//         type: 'address',
//       },
//       {
//         indexed: false,
//         internalType: 'uint256',
//         name: 'operatorId',
//         type: 'uint256',
//       },
//       {
//         indexed: false,
//         internalType: 'bool',
//         name: 'optInForSocializingPool',
//         type: 'bool',
//       },
//     ],
//     name: 'OnboardedOperator',
//     type: 'event',
//   },
//   {
//     anonymous: false,
//     inputs: [
//       {
//         indexed: true,
//         internalType: 'address',
//         name: 'nodeOperator',
//         type: 'address',
//       },
//       {
//         indexed: true,
//         internalType: 'address',
//         name: 'rewardAddress',
//         type: 'address',
//       },
//     ],
//     name: 'OperatorRewardAddressUpdated',
//     type: 'event',
//   },
//   {
//     anonymous: false,
//     inputs: [
//       {
//         indexed: false,
//         internalType: 'address',
//         name: 'account',
//         type: 'address',
//       },
//     ],
//     name: 'Paused',
//     type: 'event',
//   },
//   {
//     anonymous: false,
//     inputs: [
//       {
//         indexed: true,
//         internalType: 'address',
//         name: 'nodeOperator',
//         type: 'address',
//       },
//       {
//         indexed: true,
//         internalType: 'address',
//         name: 'rewardAddress',
//         type: 'address',
//       },
//     ],
//     name: 'RewardAddressProposed',
//     type: 'event',
//   },
//   {
//     anonymous: false,
//     inputs: [
//       { indexed: true, internalType: 'bytes32', name: 'role', type: 'bytes32' },
//       {
//         indexed: true,
//         internalType: 'bytes32',
//         name: 'previousAdminRole',
//         type: 'bytes32',
//       },
//       {
//         indexed: true,
//         internalType: 'bytes32',
//         name: 'newAdminRole',
//         type: 'bytes32',
//       },
//     ],
//     name: 'RoleAdminChanged',
//     type: 'event',
//   },
//   {
//     anonymous: false,
//     inputs: [
//       { indexed: true, internalType: 'bytes32', name: 'role', type: 'bytes32' },
//       {
//         indexed: true,
//         internalType: 'address',
//         name: 'account',
//         type: 'address',
//       },
//       {
//         indexed: true,
//         internalType: 'address',
//         name: 'sender',
//         type: 'address',
//       },
//     ],
//     name: 'RoleGranted',
//     type: 'event',
//   },
//   {
//     anonymous: false,
//     inputs: [
//       { indexed: true, internalType: 'bytes32', name: 'role', type: 'bytes32' },
//       {
//         indexed: true,
//         internalType: 'address',
//         name: 'account',
//         type: 'address',
//       },
//       {
//         indexed: true,
//         internalType: 'address',
//         name: 'sender',
//         type: 'address',
//       },
//     ],
//     name: 'RoleRevoked',
//     type: 'event',
//   },
//   {
//     anonymous: false,
//     inputs: [
//       {
//         indexed: false,
//         internalType: 'uint256',
//         name: 'amount',
//         type: 'uint256',
//       },
//     ],
//     name: 'TransferredCollateralToPool',
//     type: 'event',
//   },
//   {
//     anonymous: false,
//     inputs: [
//       {
//         indexed: false,
//         internalType: 'address',
//         name: 'account',
//         type: 'address',
//       },
//     ],
//     name: 'Unpaused',
//     type: 'event',
//   },
//   {
//     anonymous: false,
//     inputs: [
//       {
//         indexed: false,
//         internalType: 'uint256',
//         name: 'maxKeysPerOperator',
//         type: 'uint256',
//       },
//     ],
//     name: 'UpdateMaxKeysPerOperator',
//     type: 'event',
//   },
//   {
//     anonymous: false,
//     inputs: [
//       {
//         indexed: false,
//         internalType: 'uint256',
//         name: 'batchKeyDepositLimit',
//         type: 'uint256',
//       },
//     ],
//     name: 'UpdatedInputKeyCountLimit',
//     type: 'event',
//   },
//   {
//     anonymous: false,
//     inputs: [
//       {
//         indexed: false,
//         internalType: 'uint64',
//         name: 'maxNonTerminalKeyPerOperator',
//         type: 'uint64',
//       },
//     ],
//     name: 'UpdatedMaxNonTerminalKeyPerOperator',
//     type: 'event',
//   },
//   {
//     anonymous: false,
//     inputs: [
//       {
//         indexed: false,
//         internalType: 'uint256',
//         name: 'nextQueuedValidatorIndex',
//         type: 'uint256',
//       },
//     ],
//     name: 'UpdatedNextQueuedValidatorIndex',
//     type: 'event',
//   },
//   {
//     anonymous: false,
//     inputs: [
//       {
//         indexed: true,
//         internalType: 'address',
//         name: 'nodeOperator',
//         type: 'address',
//       },
//       {
//         indexed: false,
//         internalType: 'string',
//         name: 'operatorName',
//         type: 'string',
//       },
//     ],
//     name: 'UpdatedOperatorName',
//     type: 'event',
//   },
//   {
//     anonymous: false,
//     inputs: [
//       {
//         indexed: false,
//         internalType: 'uint256',
//         name: 'operatorId',
//         type: 'uint256',
//       },
//       {
//         indexed: false,
//         internalType: 'bool',
//         name: 'optedForSocializingPool',
//         type: 'bool',
//       },
//       {
//         indexed: false,
//         internalType: 'uint256',
//         name: 'block',
//         type: 'uint256',
//       },
//     ],
//     name: 'UpdatedSocializingPoolState',
//     type: 'event',
//   },
//   {
//     anonymous: false,
//     inputs: [
//       {
//         indexed: false,
//         internalType: 'address',
//         name: 'staderConfig',
//         type: 'address',
//       },
//     ],
//     name: 'UpdatedStaderConfig',
//     type: 'event',
//   },
//   {
//     anonymous: false,
//     inputs: [
//       {
//         indexed: false,
//         internalType: 'uint256',
//         name: 'validatorId',
//         type: 'uint256',
//       },
//       {
//         indexed: false,
//         internalType: 'uint256',
//         name: 'depositBlock',
//         type: 'uint256',
//       },
//     ],
//     name: 'UpdatedValidatorDepositBlock',
//     type: 'event',
//   },
//   {
//     anonymous: false,
//     inputs: [
//       {
//         indexed: false,
//         internalType: 'uint256',
//         name: 'verifiedKeysBatchSize',
//         type: 'uint256',
//       },
//     ],
//     name: 'UpdatedVerifiedKeyBatchSize',
//     type: 'event',
//   },
//   {
//     anonymous: false,
//     inputs: [
//       {
//         indexed: false,
//         internalType: 'uint256',
//         name: 'withdrawnKeysBatchSize',
//         type: 'uint256',
//       },
//     ],
//     name: 'UpdatedWithdrawnKeyBatchSize',
//     type: 'event',
//   },
//   {
//     anonymous: false,
//     inputs: [
//       {
//         indexed: false,
//         internalType: 'uint256',
//         name: 'amount',
//         type: 'uint256',
//       },
//       {
//         indexed: false,
//         internalType: 'string',
//         name: 'referralId',
//         type: 'string',
//       },
//     ],
//     name: 'ValidatorAddedViaReferral',
//     type: 'event',
//   },
//   {
//     anonymous: false,
//     inputs: [
//       { indexed: false, internalType: 'bytes', name: 'pubkey', type: 'bytes' },
//       {
//         indexed: false,
//         internalType: 'uint256',
//         name: 'validatorId',
//         type: 'uint256',
//       },
//     ],
//     name: 'ValidatorMarkedAsFrontRunned',
//     type: 'event',
//   },
//   {
//     anonymous: false,
//     inputs: [
//       { indexed: false, internalType: 'bytes', name: 'pubkey', type: 'bytes' },
//       {
//         indexed: false,
//         internalType: 'uint256',
//         name: 'validatorId',
//         type: 'uint256',
//       },
//     ],
//     name: 'ValidatorMarkedReadyToDeposit',
//     type: 'event',
//   },
//   {
//     anonymous: false,
//     inputs: [
//       { indexed: false, internalType: 'bytes', name: 'pubkey', type: 'bytes' },
//       {
//         indexed: false,
//         internalType: 'uint256',
//         name: 'validatorId',
//         type: 'uint256',
//       },
//     ],
//     name: 'ValidatorStatusMarkedAsInvalidSignature',
//     type: 'event',
//   },
//   {
//     anonymous: false,
//     inputs: [
//       { indexed: false, internalType: 'bytes', name: 'pubkey', type: 'bytes' },
//       {
//         indexed: false,
//         internalType: 'uint256',
//         name: 'validatorId',
//         type: 'uint256',
//       },
//     ],
//     name: 'ValidatorWithdrawn',
//     type: 'event',
//   },
//   {
//     inputs: [],
//     name: 'COLLATERAL_ETH',
//     outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
//     stateMutability: 'view',
//     type: 'function',
//   },
//   {
//     inputs: [],
//     name: 'DEFAULT_ADMIN_ROLE',
//     outputs: [{ internalType: 'bytes32', name: '', type: 'bytes32' }],
//     stateMutability: 'view',
//     type: 'function',
//   },
//   {
//     inputs: [],
//     name: 'FRONT_RUN_PENALTY',
//     outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
//     stateMutability: 'view',
//     type: 'function',
//   },
//   {
//     inputs: [],
//     name: 'POOL_ID',
//     outputs: [{ internalType: 'uint8', name: '', type: 'uint8' }],
//     stateMutability: 'view',
//     type: 'function',
//   },
//   {
//     inputs: [
//       { internalType: 'bytes[]', name: '_pubkey', type: 'bytes[]' },
//       {
//         internalType: 'bytes[]',
//         name: '_preDepositSignature',
//         type: 'bytes[]',
//       },
//       { internalType: 'bytes[]', name: '_depositSignature', type: 'bytes[]' },
//     ],
//     name: 'addValidatorKeys',
//     outputs: [],
//     stateMutability: 'payable',
//     type: 'function',
//   },
//   {
//     inputs: [
//       { internalType: 'string', name: '_referralId', type: 'string' },
//       {
//         internalType: 'uint256',
//         name: '_amountOfSDToUtilize',
//         type: 'uint256',
//       },
//       { internalType: 'bytes[]', name: '_pubkey', type: 'bytes[]' },
//       {
//         internalType: 'bytes[]',
//         name: '_preDepositSignature',
//         type: 'bytes[]',
//       },
//       { internalType: 'bytes[]', name: '_depositSignature', type: 'bytes[]' },
//     ],
//     name: 'addValidatorKeysWithUtilizeSD',
//     outputs: [],
//     stateMutability: 'payable',
//     type: 'function',
//   },
//   {
//     inputs: [
//       { internalType: 'bool', name: '_optInForSocializingPool', type: 'bool' },
//     ],
//     name: 'changeSocializingPoolState',
//     outputs: [
//       { internalType: 'address', name: 'feeRecipientAddress', type: 'address' },
//     ],
//     stateMutability: 'nonpayable',
//     type: 'function',
//   },
//   {
//     inputs: [
//       { internalType: 'address', name: '_operatorAddress', type: 'address' },
//     ],
//     name: 'confirmRewardAddressChange',
//     outputs: [],
//     stateMutability: 'nonpayable',
//     type: 'function',
//   },
//   {
//     inputs: [
//       { internalType: 'uint256', name: '_pageNumber', type: 'uint256' },
//       { internalType: 'uint256', name: '_pageSize', type: 'uint256' },
//     ],
//     name: 'getAllActiveValidators',
//     outputs: [
//       {
//         components: [
//           {
//             internalType: 'enum ValidatorStatus',
//             name: 'status',
//             type: 'uint8',
//           },
//           { internalType: 'bytes', name: 'pubkey', type: 'bytes' },
//           { internalType: 'bytes', name: 'preDepositSignature', type: 'bytes' },
//           { internalType: 'bytes', name: 'depositSignature', type: 'bytes' },
//           {
//             internalType: 'address',
//             name: 'withdrawVaultAddress',
//             type: 'address',
//           },
//           { internalType: 'uint256', name: 'operatorId', type: 'uint256' },
//           { internalType: 'uint256', name: 'depositBlock', type: 'uint256' },
//           { internalType: 'uint256', name: 'withdrawnBlock', type: 'uint256' },
//         ],
//         internalType: 'struct Validator[]',
//         name: '',
//         type: 'tuple[]',
//       },
//     ],
//     stateMutability: 'view',
//     type: 'function',
//   },
//   {
//     inputs: [
//       { internalType: 'uint256', name: '_pageNumber', type: 'uint256' },
//       { internalType: 'uint256', name: '_pageSize', type: 'uint256' },
//     ],
//     name: 'getAllNodeELVaultAddress',
//     outputs: [{ internalType: 'address[]', name: '', type: 'address[]' }],
//     stateMutability: 'view',
//     type: 'function',
//   },
  {
    inputs: [],
    name: 'getCollateralETH',
    outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
    stateMutability: 'pure',
    type: 'function',
  },
//   {
//     inputs: [{ internalType: 'uint256', name: '_operatorId', type: 'uint256' }],
//     name: 'getOperatorRewardAddress',
//     outputs: [{ internalType: 'address payable', name: '', type: 'address' }],
//     stateMutability: 'view',
//     type: 'function',
//   },
  {
    inputs: [{ internalType: 'uint256', name: '_operatorId', type: 'uint256' }],
    name: 'getOperatorTotalKeys',
    outputs: [{ internalType: 'uint256', name: '_totalKeys', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
//   {
//     inputs: [
//       { internalType: 'address', name: '_nodeOperator', type: 'address' },
//       { internalType: 'uint256', name: '_startIndex', type: 'uint256' },
//       { internalType: 'uint256', name: '_endIndex', type: 'uint256' },
//     ],
//     name: 'getOperatorTotalNonTerminalKeys',
//     outputs: [{ internalType: 'uint64', name: '', type: 'uint64' }],
//     stateMutability: 'view',
//     type: 'function',
//   },
//   {
//     inputs: [{ internalType: 'bytes32', name: 'role', type: 'bytes32' }],
//     name: 'getRoleAdmin',
//     outputs: [{ internalType: 'bytes32', name: '', type: 'bytes32' }],
//     stateMutability: 'view',
//     type: 'function',
//   },
//   {
//     inputs: [{ internalType: 'uint256', name: '_operatorId', type: 'uint256' }],
//     name: 'getSocializingPoolStateChangeBlock',
//     outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
//     stateMutability: 'view',
//     type: 'function',
//   },
//   {
//     inputs: [],
//     name: 'getTotalActiveValidatorCount',
//     outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
//     stateMutability: 'view',
//     type: 'function',
//   },
//   {
//     inputs: [],
//     name: 'getTotalQueuedValidatorCount',
//     outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
//     stateMutability: 'view',
//     type: 'function',
//   },
//   {
//     inputs: [
//       { internalType: 'address', name: '_operator', type: 'address' },
//       { internalType: 'uint256', name: '_pageNumber', type: 'uint256' },
//       { internalType: 'uint256', name: '_pageSize', type: 'uint256' },
//     ],
//     name: 'getValidatorsByOperator',
//     outputs: [
//       {
//         components: [
//           {
//             internalType: 'enum ValidatorStatus',
//             name: 'status',
//             type: 'uint8',
//           },
//           { internalType: 'bytes', name: 'pubkey', type: 'bytes' },
//           { internalType: 'bytes', name: 'preDepositSignature', type: 'bytes' },
//           { internalType: 'bytes', name: 'depositSignature', type: 'bytes' },
//           {
//             internalType: 'address',
//             name: 'withdrawVaultAddress',
//             type: 'address',
//           },
//           { internalType: 'uint256', name: 'operatorId', type: 'uint256' },
//           { internalType: 'uint256', name: 'depositBlock', type: 'uint256' },
//           { internalType: 'uint256', name: 'withdrawnBlock', type: 'uint256' },
//         ],
//         internalType: 'struct Validator[]',
//         name: '',
//         type: 'tuple[]',
//       },
//     ],
//     stateMutability: 'view',
//     type: 'function',
//   },
//   {
//     inputs: [
//       { internalType: 'bytes32', name: 'role', type: 'bytes32' },
//       { internalType: 'address', name: 'account', type: 'address' },
//     ],
//     name: 'grantRole',
//     outputs: [],
//     stateMutability: 'nonpayable',
//     type: 'function',
//   },
//   {
//     inputs: [
//       { internalType: 'bytes32', name: 'role', type: 'bytes32' },
//       { internalType: 'address', name: 'account', type: 'address' },
//     ],
//     name: 'hasRole',
//     outputs: [{ internalType: 'bool', name: '', type: 'bool' }],
//     stateMutability: 'view',
//     type: 'function',
//   },
//   {
//     inputs: [{ internalType: 'uint256', name: '_count', type: 'uint256' }],
//     name: 'increaseTotalActiveValidatorCount',
//     outputs: [],
//     stateMutability: 'nonpayable',
//     type: 'function',
//   },
//   {
//     inputs: [
//       { internalType: 'address', name: '_admin', type: 'address' },
//       { internalType: 'address', name: '_staderConfig', type: 'address' },
//     ],
//     name: 'initialize',
//     outputs: [],
//     stateMutability: 'nonpayable',
//     type: 'function',
//   },
//   {
//     inputs: [],
//     name: 'inputKeyCountLimit',
//     outputs: [{ internalType: 'uint16', name: '', type: 'uint16' }],
//     stateMutability: 'view',
//     type: 'function',
//   },
//   {
//     inputs: [{ internalType: 'address', name: '_operAddr', type: 'address' }],
//     name: 'isExistingOperator',
//     outputs: [{ internalType: 'bool', name: '', type: 'bool' }],
//     stateMutability: 'view',
//     type: 'function',
//   },
//   {
//     inputs: [{ internalType: 'bytes', name: '_pubkey', type: 'bytes' }],
//     name: 'isExistingPubkey',
//     outputs: [{ internalType: 'bool', name: '', type: 'bool' }],
//     stateMutability: 'view',
//     type: 'function',
//   },
//   {
//     inputs: [
//       {
//         internalType: 'bytes[]',
//         name: '_readyToDepositPubkey',
//         type: 'bytes[]',
//       },
//       { internalType: 'bytes[]', name: '_frontRunPubkey', type: 'bytes[]' },
//       {
//         internalType: 'bytes[]',
//         name: '_invalidSignaturePubkey',
//         type: 'bytes[]',
//       },
//     ],
//     name: 'markValidatorReadyToDeposit',
//     outputs: [],
//     stateMutability: 'nonpayable',
//     type: 'function',
//   },
//   {
//     inputs: [],
//     name: 'maxKeysPerOperator',
//     outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
//     stateMutability: 'view',
//     type: 'function',
//   },
//   {
//     inputs: [],
//     name: 'maxNonTerminalKeyPerOperator',
//     outputs: [{ internalType: 'uint64', name: '', type: 'uint64' }],
//     stateMutability: 'view',
//     type: 'function',
//   },
//   {
//     inputs: [],
//     name: 'nextOperatorId',
//     outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
//     stateMutability: 'view',
//     type: 'function',
//   },
//   {
//     inputs: [],
//     name: 'nextQueuedValidatorIndex',
//     outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
//     stateMutability: 'view',
//     type: 'function',
//   },
//   {
//     inputs: [],
//     name: 'nextValidatorId',
//     outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
//     stateMutability: 'view',
//     type: 'function',
//   },
//   {
//     inputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
//     name: 'nodeELRewardVaultByOperatorId',
//     outputs: [{ internalType: 'address', name: '', type: 'address' }],
//     stateMutability: 'view',
//     type: 'function',
//   },
//   {
//     inputs: [
//       { internalType: 'bool', name: '_optInForSocializingPool', type: 'bool' },
//       { internalType: 'string', name: '_operatorName', type: 'string' },
//       {
//         internalType: 'address payable',
//         name: '_operatorRewardAddress',
//         type: 'address',
//       },
//     ],
//     name: 'onboardNodeOperator',
//     outputs: [
//       { internalType: 'address', name: 'feeRecipientAddress', type: 'address' },
//     ],
//     stateMutability: 'nonpayable',
//     type: 'function',
//   },
  {
    inputs: [{ internalType: 'address', name: '', type: 'address' }],
    name: 'operatorIDByAddress',
    outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
//   {
//     inputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
//     name: 'operatorStructById',
//     outputs: [
//       { internalType: 'bool', name: 'active', type: 'bool' },
//       { internalType: 'bool', name: 'optedForSocializingPool', type: 'bool' },
//       { internalType: 'string', name: 'operatorName', type: 'string' },
//       {
//         internalType: 'address payable',
//         name: 'operatorRewardAddress',
//         type: 'address',
//       },
//       { internalType: 'address', name: 'operatorAddress', type: 'address' },
//     ],
//     stateMutability: 'view',
//     type: 'function',
//   },
//   {
//     inputs: [],
//     name: 'pause',
//     outputs: [],
//     stateMutability: 'nonpayable',
//     type: 'function',
//   },
//   {
//     inputs: [],
//     name: 'paused',
//     outputs: [{ internalType: 'bool', name: '', type: 'bool' }],
//     stateMutability: 'view',
//     type: 'function',
//   },
//   {
//     inputs: [
//       { internalType: 'address', name: '_operatorAddress', type: 'address' },
//       { internalType: 'address', name: '_newRewardAddress', type: 'address' },
//     ],
//     name: 'proposeRewardAddress',
//     outputs: [],
//     stateMutability: 'nonpayable',
//     type: 'function',
//   },
//   {
//     inputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
//     name: 'proposedRewardAddressByOperatorId',
//     outputs: [{ internalType: 'address', name: '', type: 'address' }],
//     stateMutability: 'view',
//     type: 'function',
//   },
//   {
//     inputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
//     name: 'queuedValidators',
//     outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
//     stateMutability: 'view',
//     type: 'function',
//   },
//   {
//     inputs: [
//       { internalType: 'bytes32', name: 'role', type: 'bytes32' },
//       { internalType: 'address', name: 'account', type: 'address' },
//     ],
//     name: 'renounceRole',
//     outputs: [],
//     stateMutability: 'nonpayable',
//     type: 'function',
//   },
//   {
//     inputs: [
//       { internalType: 'bytes32', name: 'role', type: 'bytes32' },
//       { internalType: 'address', name: 'account', type: 'address' },
//     ],
//     name: 'revokeRole',
//     outputs: [],
//     stateMutability: 'nonpayable',
//     type: 'function',
//   },
//   {
//     inputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
//     name: 'socializingPoolStateChangeBlock',
//     outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
//     stateMutability: 'view',
//     type: 'function',
//   },
//   {
//     inputs: [],
//     name: 'staderConfig',
//     outputs: [
//       { internalType: 'contract IStaderConfig', name: '', type: 'address' },
//     ],
//     stateMutability: 'view',
//     type: 'function',
//   },
//   {
//     inputs: [{ internalType: 'bytes4', name: 'interfaceId', type: 'bytes4' }],
//     name: 'supportsInterface',
//     outputs: [{ internalType: 'bool', name: '', type: 'bool' }],
//     stateMutability: 'view',
//     type: 'function',
//   },
//   {
//     inputs: [],
//     name: 'totalActiveValidatorCount',
//     outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
//     stateMutability: 'view',
//     type: 'function',
//   },
//   {
//     inputs: [{ internalType: 'uint256', name: '_amount', type: 'uint256' }],
//     name: 'transferCollateralToPool',
//     outputs: [],
//     stateMutability: 'nonpayable',
//     type: 'function',
//   },
//   {
//     inputs: [],
//     name: 'unpause',
//     outputs: [],
//     stateMutability: 'nonpayable',
//     type: 'function',
//   },
//   {
//     inputs: [
//       { internalType: 'uint256', name: '_validatorId', type: 'uint256' },
//     ],
//     name: 'updateDepositStatusAndBlock',
//     outputs: [],
//     stateMutability: 'nonpayable',
//     type: 'function',
//   },
//   {
//     inputs: [
//       { internalType: 'uint16', name: '_inputKeyCountLimit', type: 'uint16' },
//     ],
//     name: 'updateInputKeyCountLimit',
//     outputs: [],
//     stateMutability: 'nonpayable',
//     type: 'function',
//   },
//   {
//     inputs: [
//       { internalType: 'uint256', name: '_maxKeysPerOperator', type: 'uint256' },
//     ],
//     name: 'updateMaxKeysPerOperator',
//     outputs: [],
//     stateMutability: 'nonpayable',
//     type: 'function',
//   },
//   {
//     inputs: [
//       {
//         internalType: 'uint64',
//         name: '_maxNonTerminalKeyPerOperator',
//         type: 'uint64',
//       },
//     ],
//     name: 'updateMaxNonTerminalKeyPerOperator',
//     outputs: [],
//     stateMutability: 'nonpayable',
//     type: 'function',
//   },
//   {
//     inputs: [
//       {
//         internalType: 'uint256',
//         name: '_nextQueuedValidatorIndex',
//         type: 'uint256',
//       },
//     ],
//     name: 'updateNextQueuedValidatorIndex',
//     outputs: [],
//     stateMutability: 'nonpayable',
//     type: 'function',
//   },
//   {
//     inputs: [{ internalType: 'string', name: '_operatorName', type: 'string' }],
//     name: 'updateOperatorName',
//     outputs: [],
//     stateMutability: 'nonpayable',
//     type: 'function',
//   },
//   {
//     inputs: [
//       { internalType: 'address', name: '_staderConfig', type: 'address' },
//     ],
//     name: 'updateStaderConfig',
//     outputs: [],
//     stateMutability: 'nonpayable',
//     type: 'function',
//   },
//   {
//     inputs: [
//       {
//         internalType: 'uint256',
//         name: '_verifiedKeysBatchSize',
//         type: 'uint256',
//       },
//     ],
//     name: 'updateVerifiedKeysBatchSize',
//     outputs: [],
//     stateMutability: 'nonpayable',
//     type: 'function',
//   },
//   {
//     inputs: [{ internalType: 'bytes', name: '', type: 'bytes' }],
//     name: 'validatorIdByPubkey',
//     outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
//     stateMutability: 'view',
//     type: 'function',
//   },
//   {
//     inputs: [
//       { internalType: 'uint256', name: '', type: 'uint256' },
//       { internalType: 'uint256', name: '', type: 'uint256' },
//     ],
//     name: 'validatorIdsByOperatorId',
//     outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
//     stateMutability: 'view',
//     type: 'function',
//   },
//   {
//     inputs: [],
//     name: 'validatorQueueSize',
//     outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
//     stateMutability: 'view',
//     type: 'function',
//   },
//   {
//     inputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
//     name: 'validatorRegistry',
//     outputs: [
//       { internalType: 'enum ValidatorStatus', name: 'status', type: 'uint8' },
//       { internalType: 'bytes', name: 'pubkey', type: 'bytes' },
//       { internalType: 'bytes', name: 'preDepositSignature', type: 'bytes' },
//       { internalType: 'bytes', name: 'depositSignature', type: 'bytes' },
//       {
//         internalType: 'address',
//         name: 'withdrawVaultAddress',
//         type: 'address',
//       },
//       { internalType: 'uint256', name: 'operatorId', type: 'uint256' },
//       { internalType: 'uint256', name: 'depositBlock', type: 'uint256' },
//       { internalType: 'uint256', name: 'withdrawnBlock', type: 'uint256' },
//     ],
//     stateMutability: 'view',
//     type: 'function',
//   },
//   {
//     inputs: [],
//     name: 'verifiedKeyBatchSize',
//     outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
//     stateMutability: 'view',
//     type: 'function',
//   },
//   {
//     inputs: [{ internalType: 'bytes[]', name: '_pubkeys', type: 'bytes[]' }],
//     name: 'withdrawnValidators',
//     outputs: [],
//     stateMutability: 'nonpayable',
//     type: 'function',
//   },
] as const;

export const sdUtilityPoolAbi = [
//   { inputs: [], stateMutability: 'nonpayable', type: 'constructor' },
//   { inputs: [], name: 'AlreadyClaimed', type: 'error' },
//   { inputs: [], name: 'AlreadyLiquidated', type: 'error' },
//   { inputs: [], name: 'CallerNotAuthorizedToRedeem', type: 'error' },
//   { inputs: [], name: 'CallerNotManager', type: 'error' },
//   { inputs: [], name: 'CallerNotStaderContract', type: 'error' },
//   { inputs: [], name: 'CannotFindRequestId', type: 'error' },
//   { inputs: [], name: 'InsufficientPoolBalance', type: 'error' },
//   { inputs: [], name: 'InvalidAmountOfWithdraw', type: 'error' },
//   { inputs: [], name: 'InvalidInput', type: 'error' },
//   { inputs: [], name: 'InvalidWithdrawAmount', type: 'error' },
//   {
//     inputs: [],
//     name: 'MaxLimitOnWithdrawRequestCountReached',
//     type: 'error',
//   },
//   { inputs: [], name: 'NotClaimable', type: 'error' },
//   { inputs: [], name: 'NotLiquidatable', type: 'error' },
//   { inputs: [], name: 'NotLiquidator', type: 'error' },
//   { inputs: [], name: 'OperatorUtilizedSDBalanceNonZero', type: 'error' },
//   {
//     inputs: [{ internalType: 'uint256', name: 'requestId', type: 'uint256' }],
//     name: 'RequestIdNotFinalized',
//     type: 'error',
//   },
//   { inputs: [], name: 'SDTransferFailed', type: 'error' },
//   { inputs: [], name: 'SDUtilizeLimitReached', type: 'error' },
//   { inputs: [], name: 'UnHealthyPosition', type: 'error' },
//   { inputs: [], name: 'ZeroAddress', type: 'error' },
//   {
//     anonymous: false,
//     inputs: [
//       {
//         indexed: false,
//         internalType: 'uint256',
//         name: 'feeAccumulated',
//         type: 'uint256',
//       },
//       {
//         indexed: false,
//         internalType: 'uint256',
//         name: 'totalProtocolFee',
//         type: 'uint256',
//       },
//       {
//         indexed: false,
//         internalType: 'uint256',
//         name: 'totalUtilizedSD',
//         type: 'uint256',
//       },
//     ],
//     name: 'AccruedFees',
//     type: 'event',
//   },
//   {
//     anonymous: false,
//     inputs: [
//       {
//         indexed: true,
//         internalType: 'address',
//         name: 'utilizer',
//         type: 'address',
//       },
//       {
//         indexed: false,
//         internalType: 'uint256',
//         name: 'sdInterest',
//         type: 'uint256',
//       },
//     ],
//     name: 'ClearedUtilizerInterest',
//     type: 'event',
//   },
//   {
//     anonymous: false,
//     inputs: [
//       {
//         indexed: true,
//         internalType: 'uint256',
//         name: 'index',
//         type: 'uint256',
//       },
//     ],
//     name: 'CompleteLiquidation',
//     type: 'event',
//   },
//   {
//     anonymous: false,
//     inputs: [
//       {
//         indexed: true,
//         internalType: 'address',
//         name: 'delegator',
//         type: 'address',
//       },
//       {
//         indexed: false,
//         internalType: 'uint256',
//         name: 'sdAmount',
//         type: 'uint256',
//       },
//       {
//         indexed: false,
//         internalType: 'uint256',
//         name: 'sdXToMint',
//         type: 'uint256',
//       },
//     ],
//     name: 'Delegated',
//     type: 'event',
//   },
//   {
//     anonymous: false,
//     inputs: [
//       {
//         indexed: false,
//         internalType: 'uint256',
//         name: 'nextRequestIdToFinalize',
//         type: 'uint256',
//       },
//     ],
//     name: 'FinalizedWithdrawRequest',
//     type: 'event',
//   },
//   {
//     anonymous: false,
//     inputs: [
//       {
//         indexed: false,
//         internalType: 'uint8',
//         name: 'version',
//         type: 'uint8',
//       },
//     ],
//     name: 'Initialized',
//     type: 'event',
//   },
//   {
//     anonymous: false,
//     inputs: [
//       {
//         indexed: true,
//         internalType: 'address',
//         name: 'account',
//         type: 'address',
//       },
//       {
//         indexed: false,
//         internalType: 'uint256',
//         name: 'totalLiquidationAmountInEth',
//         type: 'uint256',
//       },
//       {
//         indexed: false,
//         internalType: 'uint256',
//         name: 'liquidationBonusInEth',
//         type: 'uint256',
//       },
//       {
//         indexed: false,
//         internalType: 'uint256',
//         name: 'liquidationFeeInEth',
//         type: 'uint256',
//       },
//       {
//         indexed: true,
//         internalType: 'address',
//         name: 'liquidator',
//         type: 'address',
//       },
//     ],
//     name: 'LiquidationCall',
//     type: 'event',
//   },
//   {
//     anonymous: false,
//     inputs: [
//       {
//         indexed: false,
//         internalType: 'address',
//         name: 'account',
//         type: 'address',
//       },
//     ],
//     name: 'Paused',
//     type: 'event',
//   },
//   {
//     anonymous: false,
//     inputs: [
//       {
//         indexed: false,
//         internalType: 'uint256',
//         name: 'protocolFeeFactor',
//         type: 'uint256',
//       },
//     ],
//     name: 'ProtocolFeeFactorUpdated',
//     type: 'event',
//   },
//   {
//     anonymous: false,
//     inputs: [
//       {
//         indexed: true,
//         internalType: 'address',
//         name: 'delegator',
//         type: 'address',
//       },
//       {
//         indexed: false,
//         internalType: 'uint256',
//         name: 'sdAmount',
//         type: 'uint256',
//       },
//       {
//         indexed: false,
//         internalType: 'uint256',
//         name: 'sdXAmount',
//         type: 'uint256',
//       },
//     ],
//     name: 'Redeemed',
//     type: 'event',
//   },
//   {
//     anonymous: false,
//     inputs: [
//       {
//         indexed: true,
//         internalType: 'address',
//         name: 'utilizer',
//         type: 'address',
//       },
//       {
//         indexed: false,
//         internalType: 'uint256',
//         name: 'repayAmount',
//         type: 'uint256',
//       },
//     ],
//     name: 'Repaid',
//     type: 'event',
//   },
//   {
//     anonymous: false,
//     inputs: [
//       {
//         indexed: true,
//         internalType: 'address',
//         name: 'utilizer',
//         type: 'address',
//       },
//       {
//         indexed: false,
//         internalType: 'uint256',
//         name: 'utilizedSDAmount',
//         type: 'uint256',
//       },
//     ],
//     name: 'RepaidUtilizedSDBalance',
//     type: 'event',
//   },
//   {
//     anonymous: false,
//     inputs: [
//       {
//         indexed: false,
//         internalType: 'address',
//         name: 'caller',
//         type: 'address',
//       },
//       {
//         indexed: false,
//         internalType: 'uint256',
//         name: 'sdToTransfer',
//         type: 'uint256',
//       },
//     ],
//     name: 'RequestRedeemed',
//     type: 'event',
//   },
//   {
//     anonymous: false,
//     inputs: [
//       {
//         indexed: false,
//         internalType: 'uint256',
//         name: 'liquidationThreshold',
//         type: 'uint256',
//       },
//       {
//         indexed: false,
//         internalType: 'uint256',
//         name: 'liquidationBonusPercent',
//         type: 'uint256',
//       },
//       {
//         indexed: false,
//         internalType: 'uint256',
//         name: 'liquidationFeePercent',
//         type: 'uint256',
//       },
//       {
//         indexed: false,
//         internalType: 'uint256',
//         name: 'ltv',
//         type: 'uint256',
//       },
//     ],
//     name: 'RiskConfigUpdated',
//     type: 'event',
//   },
//   {
//     anonymous: false,
//     inputs: [
//       {
//         indexed: true,
//         internalType: 'bytes32',
//         name: 'role',
//         type: 'bytes32',
//       },
//       {
//         indexed: true,
//         internalType: 'bytes32',
//         name: 'previousAdminRole',
//         type: 'bytes32',
//       },
//       {
//         indexed: true,
//         internalType: 'bytes32',
//         name: 'newAdminRole',
//         type: 'bytes32',
//       },
//     ],
//     name: 'RoleAdminChanged',
//     type: 'event',
//   },
//   {
//     anonymous: false,
//     inputs: [
//       {
//         indexed: true,
//         internalType: 'bytes32',
//         name: 'role',
//         type: 'bytes32',
//       },
//       {
//         indexed: true,
//         internalType: 'address',
//         name: 'account',
//         type: 'address',
//       },
//       {
//         indexed: true,
//         internalType: 'address',
//         name: 'sender',
//         type: 'address',
//       },
//     ],
//     name: 'RoleGranted',
//     type: 'event',
//   },
//   {
//     anonymous: false,
//     inputs: [
//       {
//         indexed: true,
//         internalType: 'bytes32',
//         name: 'role',
//         type: 'bytes32',
//       },
//       {
//         indexed: true,
//         internalType: 'address',
//         name: 'account',
//         type: 'address',
//       },
//       {
//         indexed: true,
//         internalType: 'address',
//         name: 'sender',
//         type: 'address',
//       },
//     ],
//     name: 'RoleRevoked',
//     type: 'event',
//   },
//   {
//     anonymous: false,
//     inputs: [
//       {
//         indexed: false,
//         internalType: 'address',
//         name: 'utilizer',
//         type: 'address',
//       },
//       {
//         indexed: false,
//         internalType: 'uint256',
//         name: 'utilizeAmount',
//         type: 'uint256',
//       },
//     ],
//     name: 'SDUtilized',
//     type: 'event',
//   },
//   {
//     anonymous: false,
//     inputs: [
//       {
//         indexed: false,
//         internalType: 'address',
//         name: 'account',
//         type: 'address',
//       },
//     ],
//     name: 'Unpaused',
//     type: 'event',
//   },
//   {
//     anonymous: false,
//     inputs: [
//       {
//         indexed: false,
//         internalType: 'uint256',
//         name: 'conservativeEthPerKey',
//         type: 'uint256',
//       },
//     ],
//     name: 'UpdatedConservativeEthPerKey',
//     type: 'event',
//   },
//   {
//     anonymous: false,
//     inputs: [
//       {
//         indexed: false,
//         internalType: 'uint256',
//         name: 'finalizationBatchLimit',
//         type: 'uint256',
//       },
//     ],
//     name: 'UpdatedFinalizationBatchLimit',
//     type: 'event',
//   },
//   {
//     anonymous: false,
//     inputs: [
//       {
//         indexed: false,
//         internalType: 'uint256',
//         name: 'maxETHWorthOfSDPerValidator',
//         type: 'uint256',
//       },
//     ],
//     name: 'UpdatedMaxETHWorthOfSDPerValidator',
//     type: 'event',
//   },
//   {
//     anonymous: false,
//     inputs: [
//       {
//         indexed: false,
//         internalType: 'uint256',
//         name: 'count',
//         type: 'uint256',
//       },
//     ],
//     name: 'UpdatedMaxNonRedeemedDelegatorRequestCount',
//     type: 'event',
//   },
//   {
//     anonymous: false,
//     inputs: [
//       {
//         indexed: false,
//         internalType: 'uint256',
//         name: 'minBlockDelayToFinalizeRequest',
//         type: 'uint256',
//       },
//     ],
//     name: 'UpdatedMinBlockDelayToFinalizeRequest',
//     type: 'event',
//   },
//   {
//     anonymous: false,
//     inputs: [
//       {
//         indexed: true,
//         internalType: 'address',
//         name: '_staderConfig',
//         type: 'address',
//       },
//     ],
//     name: 'UpdatedStaderConfig',
//     type: 'event',
//   },
//   {
//     anonymous: false,
//     inputs: [
//       {
//         indexed: false,
//         internalType: 'uint256',
//         name: 'utilizationRatePerBlock',
//         type: 'uint256',
//       },
//     ],
//     name: 'UtilizationRatePerBlockUpdated',
//     type: 'event',
//   },
//   {
//     anonymous: false,
//     inputs: [
//       {
//         indexed: false,
//         internalType: 'address',
//         name: 'caller',
//         type: 'address',
//       },
//       {
//         indexed: false,
//         internalType: 'uint256',
//         name: 'nextRequestId',
//         type: 'uint256',
//       },
//       {
//         indexed: false,
//         internalType: 'uint256',
//         name: 'sdAmountToWithdraw',
//         type: 'uint256',
//       },
//     ],
//     name: 'WithdrawRequestReceived',
//     type: 'event',
//   },
//   {
//     anonymous: false,
//     inputs: [
//       {
//         indexed: false,
//         internalType: 'uint256',
//         name: 'amount',
//         type: 'uint256',
//       },
//     ],
//     name: 'WithdrawnProtocolFee',
//     type: 'event',
//   },
//   {
//     inputs: [],
//     name: 'DECIMAL',
//     outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
//     stateMutability: 'view',
//     type: 'function',
//   },
//   {
//     inputs: [],
//     name: 'DEFAULT_ADMIN_ROLE',
//     outputs: [{ internalType: 'bytes32', name: '', type: 'bytes32' }],
//     stateMutability: 'view',
//     type: 'function',
//   },
//   {
//     inputs: [],
//     name: 'MAX_PROTOCOL_FEE',
//     outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
//     stateMutability: 'view',
//     type: 'function',
//   },
//   {
//     inputs: [],
//     name: 'MAX_UTILIZATION_RATE_PER_BLOCK',
//     outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
//     stateMutability: 'view',
//     type: 'function',
//   },
//   {
//     inputs: [],
//     name: 'MIN_SD_DELEGATE_LIMIT',
//     outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
//     stateMutability: 'view',
//     type: 'function',
//   },
//   {
//     inputs: [],
//     name: 'MIN_SD_WITHDRAW_LIMIT',
//     outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
//     stateMutability: 'view',
//     type: 'function',
//   },
//   {
//     inputs: [],
//     name: 'accrualBlockNumber',
//     outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
//     stateMutability: 'view',
//     type: 'function',
//   },
//   {
//     inputs: [],
//     name: 'accrueFee',
//     outputs: [],
//     stateMutability: 'nonpayable',
//     type: 'function',
//   },
//   {
//     inputs: [],
//     name: 'accumulatedProtocolFee',
//     outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
//     stateMutability: 'view',
//     type: 'function',
//   },
//   {
//     inputs: [],
//     name: 'cTokenTotalSupply',
//     outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
//     stateMutability: 'view',
//     type: 'function',
//   },
//   {
//     inputs: [{ internalType: 'uint256', name: '_requestId', type: 'uint256' }],
//     name: 'claim',
//     outputs: [],
//     stateMutability: 'nonpayable',
//     type: 'function',
//   },
//   {
//     inputs: [
//       { internalType: 'address[]', name: '_utilizer', type: 'address[]' },
//     ],
//     name: 'clearUtilizerInterest',
//     outputs: [],
//     stateMutability: 'nonpayable',
//     type: 'function',
//   },
//   {
//     inputs: [{ internalType: 'address', name: 'account', type: 'address' }],
//     name: 'completeLiquidation',
//     outputs: [],
//     stateMutability: 'nonpayable',
//     type: 'function',
//   },
//   {
//     inputs: [],
//     name: 'conservativeEthPerKey',
//     outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
//     stateMutability: 'view',
//     type: 'function',
//   },
//   {
//     inputs: [{ internalType: 'uint256', name: 'sdAmount', type: 'uint256' }],
//     name: 'delegate',
//     outputs: [],
//     stateMutability: 'nonpayable',
//     type: 'function',
//   },
//   {
//     inputs: [{ internalType: 'address', name: '', type: 'address' }],
//     name: 'delegatorCTokenBalance',
//     outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
//     stateMutability: 'view',
//     type: 'function',
//   },
//   {
//     inputs: [{ internalType: 'address', name: '', type: 'address' }],
//     name: 'delegatorWithdrawRequestedCTokenCount',
//     outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
//     stateMutability: 'view',
//     type: 'function',
//   },
//   {
//     inputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
//     name: 'delegatorWithdrawRequests',
//     outputs: [
//       { internalType: 'address', name: 'owner', type: 'address' },
//       { internalType: 'uint256', name: 'amountOfCToken', type: 'uint256' },
//       { internalType: 'uint256', name: 'sdExpected', type: 'uint256' },
//       { internalType: 'uint256', name: 'sdFinalized', type: 'uint256' },
//       { internalType: 'uint256', name: 'requestBlock', type: 'uint256' },
//     ],
//     stateMutability: 'view',
//     type: 'function',
//   },
//   {
//     inputs: [],
//     name: 'exchangeRateCurrent',
//     outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
//     stateMutability: 'nonpayable',
//     type: 'function',
//   },
//   {
//     inputs: [],
//     name: 'exchangeRateStored',
//     outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
//     stateMutability: 'view',
//     type: 'function',
//   },
//   {
//     inputs: [],
//     name: 'finalizationBatchLimit',
//     outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
//     stateMutability: 'view',
//     type: 'function',
//   },
//   {
//     inputs: [],
//     name: 'finalizeDelegatorWithdrawalRequest',
//     outputs: [],
//     stateMutability: 'nonpayable',
//     type: 'function',
//   },
//   {
//     inputs: [],
//     name: 'getDelegationRatePerBlock',
//     outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
//     stateMutability: 'view',
//     type: 'function',
//   },
  {
    inputs: [{ internalType: 'address', name: '_delegator', type: 'address' }],
    name: 'getDelegatorLatestSDBalance',
    outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
//   {
//     inputs: [],
//     name: 'getLatestExchangeRate',
//     outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
//     stateMutability: 'view',
//     type: 'function',
//   },
//   {
//     inputs: [],
//     name: 'getLiquidationThreshold',
//     outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
//     stateMutability: 'view',
//     type: 'function',
//   },
//   {
//     inputs: [{ internalType: 'address', name: 'account', type: 'address' }],
//     name: 'getOperatorLiquidation',
//     outputs: [
//       {
//         components: [
//           {
//             internalType: 'uint256',
//             name: 'totalAmountInEth',
//             type: 'uint256',
//           },
//           {
//             internalType: 'uint256',
//             name: 'totalBonusInEth',
//             type: 'uint256',
//           },
//           { internalType: 'uint256', name: 'totalFeeInEth', type: 'uint256' },
//           { internalType: 'bool', name: 'isRepaid', type: 'bool' },
//           { internalType: 'bool', name: 'isClaimed', type: 'bool' },
//           { internalType: 'address', name: 'liquidator', type: 'address' },
//         ],
//         internalType: 'struct OperatorLiquidation',
//         name: '',
//         type: 'tuple',
//       },
//     ],
//     stateMutability: 'view',
//     type: 'function',
//   },
//   {
//     inputs: [{ internalType: 'address', name: 'operator', type: 'address' }],
//     name: 'getOperatorTotalEth',
//     outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
//     stateMutability: 'view',
//     type: 'function',
//   },
//   {
//     inputs: [],
//     name: 'getPoolAvailableSDBalance',
//     outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
//     stateMutability: 'view',
//     type: 'function',
//   },
//   {
//     inputs: [{ internalType: 'address', name: '_delegator', type: 'address' }],
//     name: 'getRequestIdsByDelegator',
//     outputs: [{ internalType: 'uint256[]', name: '', type: 'uint256[]' }],
//     stateMutability: 'view',
//     type: 'function',
//   },
//   {
//     inputs: [{ internalType: 'bytes32', name: 'role', type: 'bytes32' }],
//     name: 'getRoleAdmin',
//     outputs: [{ internalType: 'bytes32', name: '', type: 'bytes32' }],
//     stateMutability: 'view',
//     type: 'function',
//   },
//   {
//     inputs: [{ internalType: 'address', name: 'account', type: 'address' }],
//     name: 'getUserData',
//     outputs: [
//       {
//         components: [
//           {
//             internalType: 'uint256',
//             name: 'totalInterestSD',
//             type: 'uint256',
//           },
//           {
//             internalType: 'uint256',
//             name: 'totalCollateralInEth',
//             type: 'uint256',
//           },
//           { internalType: 'uint256', name: 'healthFactor', type: 'uint256' },
//           { internalType: 'uint256', name: 'lockedEth', type: 'uint256' },
//         ],
//         internalType: 'struct UserData',
//         name: '',
//         type: 'tuple',
//       },
//     ],
//     stateMutability: 'view',
//     type: 'function',
//   },
//   {
//     inputs: [{ internalType: 'address', name: '_utilizer', type: 'address' }],
//     name: 'getUtilizerLatestBalance',
//     outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
//     stateMutability: 'view',
//     type: 'function',
//   },
//   {
//     inputs: [
//       { internalType: 'bytes32', name: 'role', type: 'bytes32' },
//       { internalType: 'address', name: 'account', type: 'address' },
//     ],
//     name: 'grantRole',
//     outputs: [],
//     stateMutability: 'nonpayable',
//     type: 'function',
//   },
//   {
//     inputs: [
//       { internalType: 'bytes32', name: 'role', type: 'bytes32' },
//       { internalType: 'address', name: 'account', type: 'address' },
//     ],
//     name: 'hasRole',
//     outputs: [{ internalType: 'bool', name: '', type: 'bool' }],
//     stateMutability: 'view',
//     type: 'function',
//   },
//   {
//     inputs: [
//       { internalType: 'address', name: '_admin', type: 'address' },
//       { internalType: 'address', name: '_staderConfig', type: 'address' },
//     ],
//     name: 'initialize',
//     outputs: [],
//     stateMutability: 'nonpayable',
//     type: 'function',
//   },
//   {
//     inputs: [{ internalType: 'address', name: 'account', type: 'address' }],
//     name: 'liquidationCall',
//     outputs: [],
//     stateMutability: 'nonpayable',
//     type: 'function',
//   },
//   {
//     inputs: [{ internalType: 'address', name: '', type: 'address' }],
//     name: 'liquidationIndexByOperator',
//     outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
//     stateMutability: 'view',
//     type: 'function',
//   },
//   {
//     inputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
//     name: 'liquidations',
//     outputs: [
//       { internalType: 'uint256', name: 'totalAmountInEth', type: 'uint256' },
//       { internalType: 'uint256', name: 'totalBonusInEth', type: 'uint256' },
//       { internalType: 'uint256', name: 'totalFeeInEth', type: 'uint256' },
//       { internalType: 'bool', name: 'isRepaid', type: 'bool' },
//       { internalType: 'bool', name: 'isClaimed', type: 'bool' },
//       { internalType: 'address', name: 'liquidator', type: 'address' },
//     ],
//     stateMutability: 'view',
//     type: 'function',
//   },
//   {
//     inputs: [],
//     name: 'maxApproveSD',
//     outputs: [],
//     stateMutability: 'nonpayable',
//     type: 'function',
//   },
//   {
//     inputs: [],
//     name: 'maxETHWorthOfSDPerValidator',
//     outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
//     stateMutability: 'view',
//     type: 'function',
//   },
//   {
//     inputs: [],
//     name: 'maxNonRedeemedDelegatorRequestCount',
//     outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
//     stateMutability: 'view',
//     type: 'function',
//   },
//   {
//     inputs: [],
//     name: 'minBlockDelayToFinalizeRequest',
//     outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
//     stateMutability: 'view',
//     type: 'function',
//   },
//   {
//     inputs: [],
//     name: 'nextRequestId',
//     outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
//     stateMutability: 'view',
//     type: 'function',
//   },
//   {
//     inputs: [],
//     name: 'nextRequestIdToFinalize',
//     outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
//     stateMutability: 'view',
//     type: 'function',
//   },
//   {
//     inputs: [],
//     name: 'pause',
//     outputs: [],
//     stateMutability: 'nonpayable',
//     type: 'function',
//   },
//   {
//     inputs: [],
//     name: 'paused',
//     outputs: [{ internalType: 'bool', name: '', type: 'bool' }],
//     stateMutability: 'view',
//     type: 'function',
//   },
//   {
//     inputs: [],
//     name: 'poolUtilization',
//     outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
//     stateMutability: 'view',
//     type: 'function',
//   },
//   {
//     inputs: [],
//     name: 'protocolFee',
//     outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
//     stateMutability: 'view',
//     type: 'function',
//   },
//   {
//     inputs: [
//       { internalType: 'bytes32', name: 'role', type: 'bytes32' },
//       { internalType: 'address', name: 'account', type: 'address' },
//     ],
//     name: 'renounceRole',
//     outputs: [],
//     stateMutability: 'nonpayable',
//     type: 'function',
//   },
//   {
//     inputs: [{ internalType: 'uint256', name: 'repayAmount', type: 'uint256' }],
//     name: 'repay',
//     outputs: [
//       { internalType: 'uint256', name: 'repaidAmount', type: 'uint256' },
//       { internalType: 'uint256', name: 'feePaid', type: 'uint256' },
//     ],
//     stateMutability: 'nonpayable',
//     type: 'function',
//   },
//   {
//     inputs: [],
//     name: 'repayFullAmount',
//     outputs: [
//       { internalType: 'uint256', name: 'repaidAmount', type: 'uint256' },
//       { internalType: 'uint256', name: 'feePaid', type: 'uint256' },
//     ],
//     stateMutability: 'nonpayable',
//     type: 'function',
//   },
//   {
//     inputs: [
//       { internalType: 'address', name: 'utilizer', type: 'address' },
//       { internalType: 'uint256', name: 'repayAmount', type: 'uint256' },
//     ],
//     name: 'repayOnBehalf',
//     outputs: [
//       { internalType: 'uint256', name: 'repaidAmount', type: 'uint256' },
//       { internalType: 'uint256', name: 'feePaid', type: 'uint256' },
//     ],
//     stateMutability: 'nonpayable',
//     type: 'function',
//   },
//   {
//     inputs: [
//       { internalType: 'address', name: '_utilizer', type: 'address' },
//       { internalType: 'uint256', name: 'amount', type: 'uint256' },
//     ],
//     name: 'repayUtilizedSDBalance',
//     outputs: [],
//     stateMutability: 'nonpayable',
//     type: 'function',
//   },
//   {
//     inputs: [
//       { internalType: 'address', name: '', type: 'address' },
//       { internalType: 'uint256', name: '', type: 'uint256' },
//     ],
//     name: 'requestIdsByDelegatorAddress',
//     outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
//     stateMutability: 'view',
//     type: 'function',
//   },
//   {
//     inputs: [
//       { internalType: 'uint256', name: '_cTokenAmount', type: 'uint256' },
//     ],
//     name: 'requestWithdraw',
//     outputs: [{ internalType: 'uint256', name: '_requestId', type: 'uint256' }],
//     stateMutability: 'nonpayable',
//     type: 'function',
//   },
//   {
//     inputs: [{ internalType: 'uint256', name: '_sdAmount', type: 'uint256' }],
//     name: 'requestWithdrawWithSDAmount',
//     outputs: [{ internalType: 'uint256', name: '_requestId', type: 'uint256' }],
//     stateMutability: 'nonpayable',
//     type: 'function',
//   },
//   {
//     inputs: [
//       { internalType: 'bytes32', name: 'role', type: 'bytes32' },
//       { internalType: 'address', name: 'account', type: 'address' },
//     ],
//     name: 'revokeRole',
//     outputs: [],
//     stateMutability: 'nonpayable',
//     type: 'function',
//   },
//   {
//     inputs: [],
//     name: 'riskConfig',
//     outputs: [
//       {
//         internalType: 'uint256',
//         name: 'liquidationThreshold',
//         type: 'uint256',
//       },
//       {
//         internalType: 'uint256',
//         name: 'liquidationBonusPercent',
//         type: 'uint256',
//       },
//       {
//         internalType: 'uint256',
//         name: 'liquidationFeePercent',
//         type: 'uint256',
//       },
//       { internalType: 'uint256', name: 'ltv', type: 'uint256' },
//     ],
//     stateMutability: 'view',
//     type: 'function',
//   },
//   {
//     inputs: [],
//     name: 'sdRequestedForWithdraw',
//     outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
//     stateMutability: 'view',
//     type: 'function',
//   },
//   {
//     inputs: [],
//     name: 'sdReservedForClaim',
//     outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
//     stateMutability: 'view',
//     type: 'function',
//   },
//   {
//     inputs: [],
//     name: 'staderConfig',
//     outputs: [
//       { internalType: 'contract IStaderConfig', name: '', type: 'address' },
//     ],
//     stateMutability: 'view',
//     type: 'function',
//   },
//   {
//     inputs: [{ internalType: 'bytes4', name: 'interfaceId', type: 'bytes4' }],
//     name: 'supportsInterface',
//     outputs: [{ internalType: 'bool', name: '', type: 'bool' }],
//     stateMutability: 'view',
//     type: 'function',
//   },
//   {
//     inputs: [],
//     name: 'totalUtilizedSD',
//     outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
//     stateMutability: 'view',
//     type: 'function',
//   },
//   {
//     inputs: [],
//     name: 'unpause',
//     outputs: [],
//     stateMutability: 'nonpayable',
//     type: 'function',
//   },
//   {
//     inputs: [
//       { internalType: 'uint256', name: '_newEthPerKey', type: 'uint256' },
//     ],
//     name: 'updateConservativeEthPerKey',
//     outputs: [],
//     stateMutability: 'nonpayable',
//     type: 'function',
//   },
//   {
//     inputs: [
//       {
//         internalType: 'uint256',
//         name: '_finalizationBatchLimit',
//         type: 'uint256',
//       },
//     ],
//     name: 'updateFinalizationBatchLimit',
//     outputs: [],
//     stateMutability: 'nonpayable',
//     type: 'function',
//   },
//   {
//     inputs: [
//       {
//         internalType: 'uint256',
//         name: '_maxETHWorthOfSDPerValidator',
//         type: 'uint256',
//       },
//     ],
//     name: 'updateMaxETHWorthOfSDPerValidator',
//     outputs: [],
//     stateMutability: 'nonpayable',
//     type: 'function',
//   },
//   {
//     inputs: [{ internalType: 'uint256', name: '_count', type: 'uint256' }],
//     name: 'updateMaxNonRedeemedDelegatorRequestCount',
//     outputs: [],
//     stateMutability: 'nonpayable',
//     type: 'function',
//   },
//   {
//     inputs: [
//       {
//         internalType: 'uint256',
//         name: '_minBlockDelayToFinalizeRequest',
//         type: 'uint256',
//       },
//     ],
//     name: 'updateMinBlockDelayToFinalizeRequest',
//     outputs: [],
//     stateMutability: 'nonpayable',
//     type: 'function',
//   },
//   {
//     inputs: [
//       { internalType: 'uint256', name: '_protocolFee', type: 'uint256' },
//     ],
//     name: 'updateProtocolFee',
//     outputs: [],
//     stateMutability: 'nonpayable',
//     type: 'function',
//   },
//   {
//     inputs: [
//       {
//         internalType: 'uint256',
//         name: 'liquidationThreshold',
//         type: 'uint256',
//       },
//       {
//         internalType: 'uint256',
//         name: 'liquidationBonusPercent',
//         type: 'uint256',
//       },
//       {
//         internalType: 'uint256',
//         name: 'liquidationFeePercent',
//         type: 'uint256',
//       },
//       { internalType: 'uint256', name: 'ltv', type: 'uint256' },
//     ],
//     name: 'updateRiskConfig',
//     outputs: [],
//     stateMutability: 'nonpayable',
//     type: 'function',
//   },
//   {
//     inputs: [
//       { internalType: 'address', name: '_staderConfig', type: 'address' },
//     ],
//     name: 'updateStaderConfig',
//     outputs: [],
//     stateMutability: 'nonpayable',
//     type: 'function',
//   },
//   {
//     inputs: [
//       {
//         internalType: 'uint256',
//         name: '_utilizationRatePerBlock',
//         type: 'uint256',
//       },
//     ],
//     name: 'updateUtilizationRatePerBlock',
//     outputs: [],
//     stateMutability: 'nonpayable',
//     type: 'function',
//   },
//   {
//     inputs: [],
//     name: 'utilizationRatePerBlock',
//     outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
//     stateMutability: 'view',
//     type: 'function',
//   },
//   {
//     inputs: [
//       { internalType: 'uint256', name: 'utilizeAmount', type: 'uint256' },
//     ],
//     name: 'utilize',
//     outputs: [],
//     stateMutability: 'nonpayable',
//     type: 'function',
//   },
//   {
//     inputs: [],
//     name: 'utilizeIndex',
//     outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
//     stateMutability: 'view',
//     type: 'function',
//   },
//   {
//     inputs: [
//       { internalType: 'address', name: 'operator', type: 'address' },
//       { internalType: 'uint256', name: 'utilizeAmount', type: 'uint256' },
//       {
//         internalType: 'uint256',
//         name: 'nonTerminalKeyCount',
//         type: 'uint256',
//       },
//     ],
//     name: 'utilizeWhileAddingKeys',
//     outputs: [],
//     stateMutability: 'nonpayable',
//     type: 'function',
//   },
//   {
//     inputs: [{ internalType: 'address', name: 'account', type: 'address' }],
//     name: 'utilizerBalanceCurrent',
//     outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
//     stateMutability: 'nonpayable',
//     type: 'function',
//   },
//   {
//     inputs: [{ internalType: 'address', name: 'account', type: 'address' }],
//     name: 'utilizerBalanceStored',
//     outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
//     stateMutability: 'view',
//     type: 'function',
//   },
//   {
//     inputs: [{ internalType: 'address', name: '', type: 'address' }],
//     name: 'utilizerData',
//     outputs: [
//       { internalType: 'uint256', name: 'principal', type: 'uint256' },
//       { internalType: 'uint256', name: 'utilizeIndex', type: 'uint256' },
//     ],
//     stateMutability: 'view',
//     type: 'function',
//   },
//   {
//     inputs: [{ internalType: 'uint256', name: '_amount', type: 'uint256' }],
//     name: 'withdrawProtocolFee',
//     outputs: [],
//     stateMutability: 'nonpayable',
//     type: 'function',
//   },
] as const;

export const sdCollateralPoolAbi = [
  // { inputs: [], stateMutability: 'nonpayable', type: 'constructor' },
  // { inputs: [], name: 'CallerNotManager', type: 'error' },
  // { inputs: [], name: 'CallerNotStaderContract', type: 'error' },
  // { inputs: [], name: 'CallerNotWithdrawVault', type: 'error' },
  // {
  //   inputs: [
  //     {
  //       internalType: 'uint256',
  //       name: 'operatorSDCollateral',
  //       type: 'uint256',
  //     },
  //   ],
  //   name: 'InsufficientSDToWithdraw',
  //   type: 'error',
  // },
  // { inputs: [], name: 'InsufficientSelfBondToRepay', type: 'error' },
  // { inputs: [], name: 'InvalidPoolId', type: 'error' },
  // { inputs: [], name: 'InvalidPoolLimit', type: 'error' },
  // { inputs: [], name: 'NoStateChange', type: 'error' },
  // { inputs: [], name: 'NonTerminalKeysNotZero', type: 'error' },
  // { inputs: [], name: 'SDTransferFailed', type: 'error' },
  // { inputs: [], name: 'ZeroAddress', type: 'error' },
  // {
  //   anonymous: false,
  //   inputs: [
  //     { indexed: false, internalType: 'uint8', name: 'version', type: 'uint8' },
  //   ],
  //   name: 'Initialized',
  //   type: 'event',
  // },
  // {
  //   anonymous: false,
  //   inputs: [
  //     {
  //       indexed: true,
  //       internalType: 'address',
  //       name: 'operator',
  //       type: 'address',
  //     },
  //     {
  //       indexed: false,
  //       internalType: 'uint256',
  //       name: 'sdAmount',
  //       type: 'uint256',
  //     },
  //   ],
  //   name: 'ReducedUtilizedPosition',
  //   type: 'event',
  // },
  // {
  //   anonymous: false,
  //   inputs: [
  //     { indexed: true, internalType: 'bytes32', name: 'role', type: 'bytes32' },
  //     {
  //       indexed: true,
  //       internalType: 'bytes32',
  //       name: 'previousAdminRole',
  //       type: 'bytes32',
  //     },
  //     {
  //       indexed: true,
  //       internalType: 'bytes32',
  //       name: 'newAdminRole',
  //       type: 'bytes32',
  //     },
  //   ],
  //   name: 'RoleAdminChanged',
  //   type: 'event',
  // },
  // {
  //   anonymous: false,
  //   inputs: [
  //     { indexed: true, internalType: 'bytes32', name: 'role', type: 'bytes32' },
  //     {
  //       indexed: true,
  //       internalType: 'address',
  //       name: 'account',
  //       type: 'address',
  //     },
  //     {
  //       indexed: true,
  //       internalType: 'address',
  //       name: 'sender',
  //       type: 'address',
  //     },
  //   ],
  //   name: 'RoleGranted',
  //   type: 'event',
  // },
  // {
  //   anonymous: false,
  //   inputs: [
  //     { indexed: true, internalType: 'bytes32', name: 'role', type: 'bytes32' },
  //     {
  //       indexed: true,
  //       internalType: 'address',
  //       name: 'account',
  //       type: 'address',
  //     },
  //     {
  //       indexed: true,
  //       internalType: 'address',
  //       name: 'sender',
  //       type: 'address',
  //     },
  //   ],
  //   name: 'RoleRevoked',
  //   type: 'event',
  // },
  // {
  //   anonymous: false,
  //   inputs: [
  //     {
  //       indexed: true,
  //       internalType: 'address',
  //       name: 'operator',
  //       type: 'address',
  //     },
  //     {
  //       indexed: false,
  //       internalType: 'uint256',
  //       name: 'sdAmount',
  //       type: 'uint256',
  //     },
  //   ],
  //   name: 'SDDeposited',
  //   type: 'event',
  // },
  // {
  //   anonymous: false,
  //   inputs: [
  //     {
  //       indexed: false,
  //       internalType: 'address',
  //       name: 'operator',
  //       type: 'address',
  //     },
  //     {
  //       indexed: false,
  //       internalType: 'uint256',
  //       name: 'repayAmount',
  //       type: 'uint256',
  //     },
  //   ],
  //   name: 'SDRepaid',
  //   type: 'event',
  // },
  // {
  //   anonymous: false,
  //   inputs: [
  //     {
  //       indexed: true,
  //       internalType: 'address',
  //       name: 'operator',
  //       type: 'address',
  //     },
  //     {
  //       indexed: true,
  //       internalType: 'address',
  //       name: 'auction',
  //       type: 'address',
  //     },
  //     {
  //       indexed: false,
  //       internalType: 'uint256',
  //       name: 'sdSlashed',
  //       type: 'uint256',
  //     },
  //   ],
  //   name: 'SDSlashed',
  //   type: 'event',
  // },
  // {
  //   anonymous: false,
  //   inputs: [
  //     {
  //       indexed: true,
  //       internalType: 'address',
  //       name: 'operator',
  //       type: 'address',
  //     },
  //     {
  //       indexed: false,
  //       internalType: 'uint256',
  //       name: 'sdAmount',
  //       type: 'uint256',
  //     },
  //   ],
  //   name: 'SDWithdrawn',
  //   type: 'event',
  // },
  // {
  //   anonymous: false,
  //   inputs: [
  //     { indexed: false, internalType: 'uint8', name: 'poolId', type: 'uint8' },
  //     {
  //       indexed: false,
  //       internalType: 'address',
  //       name: 'operator',
  //       type: 'address',
  //     },
  //   ],
  //   name: 'UpdatedPoolIdForOperator',
  //   type: 'event',
  // },
  // {
  //   anonymous: false,
  //   inputs: [
  //     { indexed: false, internalType: 'uint8', name: 'poolId', type: 'uint8' },
  //     {
  //       indexed: false,
  //       internalType: 'uint256',
  //       name: 'minThreshold',
  //       type: 'uint256',
  //     },
  //     {
  //       indexed: false,
  //       internalType: 'uint256',
  //       name: 'withdrawThreshold',
  //       type: 'uint256',
  //     },
  //   ],
  //   name: 'UpdatedPoolThreshold',
  //   type: 'event',
  // },
  // {
  //   anonymous: false,
  //   inputs: [
  //     {
  //       indexed: true,
  //       internalType: 'address',
  //       name: 'staderConfig',
  //       type: 'address',
  //     },
  //   ],
  //   name: 'UpdatedStaderConfig',
  //   type: 'event',
  // },
  // {
  //   anonymous: false,
  //   inputs: [
  //     {
  //       indexed: true,
  //       internalType: 'address',
  //       name: 'operator',
  //       type: 'address',
  //     },
  //     {
  //       indexed: false,
  //       internalType: 'uint256',
  //       name: 'sdAmount',
  //       type: 'uint256',
  //     },
  //   ],
  //   name: 'UtilizedSDDeposited',
  //   type: 'event',
  // },
  // {
  //   anonymous: false,
  //   inputs: [
  //     {
  //       indexed: false,
  //       internalType: 'address',
  //       name: 'operator',
  //       type: 'address',
  //     },
  //     {
  //       indexed: false,
  //       internalType: 'uint256',
  //       name: 'sdSlashFromUtilized',
  //       type: 'uint256',
  //     },
  //   ],
  //   name: 'UtilizedSDSlashed',
  //   type: 'event',
  // },
  // {
  //   inputs: [],
  //   name: 'DEFAULT_ADMIN_ROLE',
  //   outputs: [{ internalType: 'bytes32', name: '', type: 'bytes32' }],
  //   stateMutability: 'view',
  //   type: 'function',
  // },
  // {
  //   inputs: [{ internalType: 'uint256', name: '_ethAmount', type: 'uint256' }],
  //   name: 'convertETHToSD',
  //   outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
  //   stateMutability: 'view',
  //   type: 'function',
  // },
  // {
  //   inputs: [{ internalType: 'uint256', name: '_sdAmount', type: 'uint256' }],
  //   name: 'convertSDToETH',
  //   outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
  //   stateMutability: 'view',
  //   type: 'function',
  // },
  // {
  //   inputs: [{ internalType: 'uint256', name: '_sdAmount', type: 'uint256' }],
  //   name: 'depositSDAsCollateral',
  //   outputs: [],
  //   stateMutability: 'nonpayable',
  //   type: 'function',
  // },
  // {
  //   inputs: [
  //     { internalType: 'address', name: '_operator', type: 'address' },
  //     { internalType: 'uint256', name: '_sdAmount', type: 'uint256' },
  //   ],
  //   name: 'depositSDAsCollateralOnBehalf',
  //   outputs: [],
  //   stateMutability: 'nonpayable',
  //   type: 'function',
  // },
  // {
  //   inputs: [
  //     { internalType: 'address', name: '_operator', type: 'address' },
  //     { internalType: 'uint256', name: '_sdAmount', type: 'uint256' },
  //   ],
  //   name: 'depositSDFromUtilityPool',
  //   outputs: [],
  //   stateMutability: 'nonpayable',
  //   type: 'function',
  // },
  // {
  //   inputs: [
  //     { internalType: 'uint8', name: '_poolId', type: 'uint8' },
  //     { internalType: 'uint256', name: '_numValidator', type: 'uint256' },
  //   ],
  //   name: 'getMinimumSDToBond',
  //   outputs: [
  //     { internalType: 'uint256', name: '_minSDToBond', type: 'uint256' },
  //   ],
  //   stateMutability: 'view',
  //   type: 'function',
  // },
  // {
  //   inputs: [{ internalType: 'address', name: '_operator', type: 'address' }],
  //   name: 'getOperatorInfo',
  //   outputs: [
  //     { internalType: 'uint8', name: '_poolId', type: 'uint8' },
  //     { internalType: 'uint256', name: '_operatorId', type: 'uint256' },
  //     { internalType: 'uint256', name: '_validatorCount', type: 'uint256' },
  //   ],
  //   stateMutability: 'view',
  //   type: 'function',
  // },
  // {
  //   inputs: [{ internalType: 'address', name: '_operator', type: 'address' }],
  //   name: 'getOperatorWithdrawThreshold',
  //   outputs: [
  //     {
  //       internalType: 'uint256',
  //       name: 'operatorWithdrawThreshold',
  //       type: 'uint256',
  //     },
  //   ],
  //   stateMutability: 'view',
  //   type: 'function',
  // },
  // {
  //   inputs: [
  //     { internalType: 'address', name: '_operator', type: 'address' },
  //     { internalType: 'uint8', name: '_poolId', type: 'uint8' },
  //     { internalType: 'uint256', name: '_numValidator', type: 'uint256' },
  //   ],
  //   name: 'getRemainingSDToBond',
  //   outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
  //   stateMutability: 'view',
  //   type: 'function',
  // },
  // {
  //   inputs: [{ internalType: 'address', name: '_operator', type: 'address' }],
  //   name: 'getRewardEligibleSD',
  //   outputs: [
  //     { internalType: 'uint256', name: '_rewardEligibleSD', type: 'uint256' },
  //   ],
  //   stateMutability: 'view',
  //   type: 'function',
  // },
  // {
  //   inputs: [{ internalType: 'bytes32', name: 'role', type: 'bytes32' }],
  //   name: 'getRoleAdmin',
  //   outputs: [{ internalType: 'bytes32', name: '', type: 'bytes32' }],
  //   stateMutability: 'view',
  //   type: 'function',
  // },
  // {
  //   inputs: [
  //     { internalType: 'bytes32', name: 'role', type: 'bytes32' },
  //     { internalType: 'address', name: 'account', type: 'address' },
  //   ],
  //   name: 'grantRole',
  //   outputs: [],
  //   stateMutability: 'nonpayable',
  //   type: 'function',
  // },
  // {
  //   inputs: [
  //     { internalType: 'address', name: '_operator', type: 'address' },
  //     { internalType: 'uint8', name: '_poolId', type: 'uint8' },
  //     { internalType: 'uint256', name: '_numValidator', type: 'uint256' },
  //   ],
  //   name: 'hasEnoughSDCollateral',
  //   outputs: [{ internalType: 'bool', name: '', type: 'bool' }],
  //   stateMutability: 'view',
  //   type: 'function',
  // },
  // {
  //   inputs: [
  //     { internalType: 'bytes32', name: 'role', type: 'bytes32' },
  //     { internalType: 'address', name: 'account', type: 'address' },
  //   ],
  //   name: 'hasRole',
  //   outputs: [{ internalType: 'bool', name: '', type: 'bool' }],
  //   stateMutability: 'view',
  //   type: 'function',
  // },
  // {
  //   inputs: [
  //     { internalType: 'address', name: '_admin', type: 'address' },
  //     { internalType: 'address', name: '_staderConfig', type: 'address' },
  //   ],
  //   name: 'initialize',
  //   outputs: [],
  //   stateMutability: 'nonpayable',
  //   type: 'function',
  // },
  // {
  //   inputs: [],
  //   name: 'maxApproveSD',
  //   outputs: [],
  //   stateMutability: 'nonpayable',
  //   type: 'function',
  // },
  {
    inputs: [{ internalType: 'address', name: '', type: 'address' }],
    name: 'operatorSDBalance',
    outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  // {
  //   inputs: [{ internalType: 'address', name: '', type: 'address' }],
  //   name: 'operatorUtilizedSDBalance',
  //   outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
  //   stateMutability: 'view',
  //   type: 'function',
  // },
  // {
  //   inputs: [{ internalType: 'uint8', name: '', type: 'uint8' }],
  //   name: 'poolThresholdbyPoolId',
  //   outputs: [
  //     { internalType: 'uint256', name: 'minThreshold', type: 'uint256' },
  //     { internalType: 'uint256', name: 'maxThreshold', type: 'uint256' },
  //     { internalType: 'uint256', name: 'withdrawThreshold', type: 'uint256' },
  //     { internalType: 'string', name: 'units', type: 'string' },
  //   ],
  //   stateMutability: 'view',
  //   type: 'function',
  // },
  // {
  //   inputs: [
  //     { internalType: 'address', name: '_operator', type: 'address' },
  //     { internalType: 'uint256', name: '_sdAmount', type: 'uint256' },
  //   ],
  //   name: 'reduceUtilizedSDPosition',
  //   outputs: [],
  //   stateMutability: 'nonpayable',
  //   type: 'function',
  // },
  // {
  //   inputs: [
  //     { internalType: 'bytes32', name: 'role', type: 'bytes32' },
  //     { internalType: 'address', name: 'account', type: 'address' },
  //   ],
  //   name: 'renounceRole',
  //   outputs: [],
  //   stateMutability: 'nonpayable',
  //   type: 'function',
  // },
  // {
  //   inputs: [
  //     { internalType: 'bytes32', name: 'role', type: 'bytes32' },
  //     { internalType: 'address', name: 'account', type: 'address' },
  //   ],
  //   name: 'revokeRole',
  //   outputs: [],
  //   stateMutability: 'nonpayable',
  //   type: 'function',
  // },
  // {
  //   inputs: [
  //     { internalType: 'uint256', name: '_validatorId', type: 'uint256' },
  //     { internalType: 'uint8', name: '_poolId', type: 'uint8' },
  //   ],
  //   name: 'slashValidatorSD',
  //   outputs: [],
  //   stateMutability: 'nonpayable',
  //   type: 'function',
  // },
  // {
  //   inputs: [],
  //   name: 'staderConfig',
  //   outputs: [
  //     { internalType: 'contract IStaderConfig', name: '', type: 'address' },
  //   ],
  //   stateMutability: 'view',
  //   type: 'function',
  // },
  // {
  //   inputs: [{ internalType: 'bytes4', name: 'interfaceId', type: 'bytes4' }],
  //   name: 'supportsInterface',
  //   outputs: [{ internalType: 'bool', name: '', type: 'bool' }],
  //   stateMutability: 'view',
  //   type: 'function',
  // },
  // {
  //   inputs: [{ internalType: 'address', name: '_operator', type: 'address' }],
  //   name: 'transferBackUtilizedSD',
  //   outputs: [],
  //   stateMutability: 'nonpayable',
  //   type: 'function',
  // },
  // {
  //   inputs: [
  //     { internalType: 'uint8', name: '_poolId', type: 'uint8' },
  //     { internalType: 'uint256', name: '_minThreshold', type: 'uint256' },
  //     { internalType: 'uint256', name: '_maxThreshold', type: 'uint256' },
  //     { internalType: 'uint256', name: '_withdrawThreshold', type: 'uint256' },
  //     { internalType: 'string', name: '_units', type: 'string' },
  //   ],
  //   name: 'updatePoolThreshold',
  //   outputs: [],
  //   stateMutability: 'nonpayable',
  //   type: 'function',
  // },
  // {
  //   inputs: [
  //     { internalType: 'address', name: '_staderConfig', type: 'address' },
  //   ],
  //   name: 'updateStaderConfig',
  //   outputs: [],
  //   stateMutability: 'nonpayable',
  //   type: 'function',
  // },
  // {
  //   inputs: [
  //     { internalType: 'uint256', name: '_requestedSD', type: 'uint256' },
  //   ],
  //   name: 'withdraw',
  //   outputs: [],
  //   stateMutability: 'nonpayable',
  //   type: 'function',
  // },
  // {
  //   inputs: [
  //     { internalType: 'uint256', name: '_requestedSD', type: 'uint256' },
  //     { internalType: 'address', name: '_operator', type: 'address' },
  //   ],
  //   name: 'withdrawOnBehalf',
  //   outputs: [],
  //   stateMutability: 'nonpayable',
  //   type: 'function',
  // },
] as const;
