export const LoopscaleIdl = {
  address: 'abfcSQac2vK2Pa6UAJb37DzarVxF15bDTdphJzAqYYp',
  metadata: {
    name: 'creditbook',
    version: '0.1.0',
    spec: '0.1.0',
    description: 'Created with Anchor',
  },
  docs: ['Ceditbook program'],
  instructions: [
    {
      name: 'cancel_order',
      docs: ['cancel order'],
      discriminator: [95, 129, 237, 240, 8, 49, 223, 132],
      accounts: [
        { name: 'payer', writable: true, signer: true },
        { name: 'user', writable: true, signer: true },
        { name: 'user_role' },
        { name: 'market_engine', writable: true, signer: true },
        { name: 'escrow_account' },
        { name: 'order', writable: true },
        { name: 'system_program' },
        { name: 'instructions_program' },
      ],
      args: [],
    },
    {
      name: 'check_default',
      discriminator: [252, 81, 226, 106, 103, 50, 40, 150],
      accounts: [
        { name: 'payer', writable: true, signer: true },
        { name: 'market_engine', writable: true, signer: true },
        { name: 'order', writable: true },
        { name: 'loan_vault' },
        { name: 'order_ledgers' },
      ],
      args: [],
    },
    {
      name: 'close_lut',
      discriminator: [163, 121, 7, 40, 193, 219, 160, 213],
      accounts: [
        { name: 'payer', writable: true, signer: true },
        { name: 'market_engine', writable: true, signer: true },
        { name: 'escrow_account', writable: true },
        { name: 'lut', writable: true },
        { name: 'address_lookup_table_program' },
      ],
      args: [],
    },
    {
      name: 'close_role',
      discriminator: [139, 108, 157, 18, 175, 150, 155, 26],
      accounts: [
        { name: 'payer', writable: true, signer: true },
        { name: 'admin', writable: true, signer: true },
        { name: 'market_engine', writable: true, signer: true },
        { name: 'admin_role' },
        { name: 'role', writable: true },
        { name: 'system_program' },
        { name: 'event_authority' },
        { name: 'program' },
      ],
      args: [{ name: 'params', type: { defined: { name: 'RoleParams' } } }],
    },
    {
      name: 'create_escrow',
      docs: ["escrow ix's", 'create escrow account'],
      discriminator: [253, 215, 165, 116, 36, 108, 68, 80],
      accounts: [
        { name: 'user', writable: true, signer: true },
        { name: 'user_role' },
        { name: 'payer', writable: true, signer: true },
        { name: 'market_engine', writable: true, signer: true },
        { name: 'escrow_account', writable: true },
        { name: 'escrow_yield_pda', writable: true },
        { name: 'system_program' },
        { name: 'instructions_program' },
        { name: 'event_authority' },
        { name: 'program' },
      ],
      args: [
        { name: 'params', type: { defined: { name: 'CreateEscrowParams' } } },
      ],
    },
    {
      name: 'create_escrow_role',
      docs: ['edit escrow account'],
      discriminator: [180, 139, 213, 89, 216, 149, 43, 220],
      accounts: [
        { name: 'payer', writable: true, signer: true },
        { name: 'admin', writable: true, signer: true },
        { name: 'market_engine', writable: true, signer: true },
        { name: 'admin_role' },
        { name: 'role', writable: true },
        { name: 'escrow_account' },
        { name: 'system_program' },
        { name: 'event_authority' },
        { name: 'program' },
      ],
      args: [
        { name: 'params', type: { defined: { name: 'EscrowRoleParams' } } },
      ],
    },
    {
      name: 'create_external_yield_for_escrow',
      discriminator: [152, 50, 6, 55, 83, 97, 152, 252],
      accounts: [
        { name: 'user', writable: true, signer: true },
        { name: 'user_role' },
        { name: 'payer', writable: true, signer: true },
        { name: 'market_engine', writable: true, signer: true },
        { name: 'escrow_account', writable: true },
        { name: 'escrow_external_yield', writable: true },
        { name: 'system_program' },
        { name: 'event_authority' },
        { name: 'program' },
      ],
      args: [
        {
          name: 'args',
          type: { defined: { name: 'CreateExternalYieldForEscrowParams' } },
        },
      ],
    },
    {
      name: 'create_first_admin',
      docs: ["auth management ix's"],
      discriminator: [231, 53, 88, 230, 32, 105, 163, 51],
      accounts: [
        { name: 'payer', writable: true, signer: true },
        { name: 'market_engine', writable: true, signer: true },
        { name: 'super_admin', writable: true },
        { name: 'first_admin', writable: true },
        { name: 'system_program' },
        { name: 'event_authority' },
        { name: 'program' },
      ],
      args: [{ name: 'params', type: { defined: { name: 'RoleParams' } } }],
    },
    {
      name: 'create_lut',
      discriminator: [246, 95, 104, 1, 220, 87, 23, 255],
      accounts: [
        { name: 'payer', writable: true, signer: true },
        { name: 'market_engine', writable: true, signer: true },
        { name: 'escrow_account', writable: true },
        { name: 'lut', writable: true },
        { name: 'system_program' },
        { name: 'address_lookup_table_program' },
      ],
      args: [{ name: 'slot', type: 'u64' }],
    },
    {
      name: 'create_order',
      docs: ['create an abf order'],
      discriminator: [141, 54, 37, 207, 237, 210, 250, 215],
      accounts: [
        { name: 'payer', writable: true, signer: true },
        { name: 'user', writable: true, signer: true },
        { name: 'user_role' },
        { name: 'market_engine', writable: true, signer: true },
        { name: 'escrow_account' },
        { name: 'nonce' },
        { name: 'order', writable: true },
        { name: 'order_ledgers', writable: true },
        { name: 'collateral_mint' },
        { name: 'principal_mint' },
        { name: 'escrow_asset_ta' },
        { name: 'market_manager' },
        { name: 'liquidation_manager' },
        { name: 'designated_taker' },
        { name: 'associated_token_program' },
        { name: 'token_program' },
        { name: 'token22_program' },
        { name: 'system_program' },
        { name: 'instructions_program' },
      ],
      args: [
        { name: 'params', type: { defined: { name: 'CreateOrderParams' } } },
      ],
    },
    {
      name: 'create_role',
      discriminator: [170, 147, 127, 223, 222, 112, 205, 163],
      accounts: [
        { name: 'payer', writable: true, signer: true },
        { name: 'admin', writable: true, signer: true },
        { name: 'market_engine', writable: true, signer: true },
        { name: 'admin_role' },
        { name: 'role', writable: true },
        { name: 'system_program' },
        { name: 'event_authority' },
        { name: 'program' },
      ],
      args: [{ name: 'params', type: { defined: { name: 'RoleParams' } } }],
    },
    {
      name: 'create_strategy_order',
      discriminator: [184, 160, 90, 55, 181, 30, 130, 246],
      accounts: [
        { name: 'payer', writable: true, signer: true },
        { name: 'strategy', writable: true, signer: true },
        { name: 'market_engine', writable: true, signer: true },
        { name: 'lender_escrow_account', writable: true },
        { name: 'nonce' },
        { name: 'order', writable: true },
        { name: 'order_ledgers', writable: true },
        { name: 'collateral_mint' },
        { name: 'principal_mint' },
        { name: 'market_manager' },
        { name: 'liquidation_manager' },
        { name: 'designated_taker' },
        { name: 'borrower_escrow_account', writable: true },
        { name: 'system_program' },
        { name: 'program' },
      ],
      args: [
        {
          name: 'args',
          type: { defined: { name: 'CreateStrategyOrderParams' } },
        },
      ],
    },
    {
      name: 'deactivate_lut',
      discriminator: [136, 64, 121, 45, 204, 255, 45, 59],
      accounts: [
        { name: 'payer', writable: true, signer: true },
        { name: 'market_engine', writable: true, signer: true },
        { name: 'escrow_account', writable: true },
        { name: 'lut', writable: true },
        { name: 'address_lookup_table_program' },
      ],
      args: [],
    },
    {
      name: 'delete_ledger_account',
      discriminator: [25, 212, 111, 126, 168, 160, 54, 56],
      accounts: [
        { name: 'payer', writable: true, signer: true },
        { name: 'market_engine', writable: true, signer: true },
        { name: 'order', writable: true },
        { name: 'order_ledgers', writable: true },
        { name: 'system_program' },
      ],
      args: [
        {
          name: 'ledgers',
          type: { defined: { name: 'DeleteLedgerAccountArgs' } },
        },
      ],
    },
    {
      name: 'deposit_asset',
      discriminator: [107, 93, 89, 87, 226, 203, 154, 19],
      accounts: [
        { name: 'user', writable: true, signer: true },
        { name: 'user_role' },
        { name: 'payer', writable: true, signer: true },
        { name: 'market_engine', writable: true, signer: true },
        { name: 'escrow_account', writable: true },
        { name: 'deposit_mint' },
        { name: 'owner_deposit_ta', writable: true },
        { name: 'escrow_deposit_ta', writable: true },
        { name: 'associated_token_program' },
        { name: 'token_program' },
        { name: 'system_program' },
        { name: 'instructions_program' },
        { name: 'event_authority' },
        { name: 'program' },
      ],
      args: [
        { name: 'args', type: { defined: { name: 'EscrowUpdateParams' } } },
      ],
    },
    {
      name: 'deposit_staked_sol',
      discriminator: [205, 92, 117, 144, 162, 226, 122, 32],
      accounts: [
        { name: 'user', writable: true, signer: true },
        { name: 'user_role' },
        { name: 'payer', writable: true, signer: true },
        { name: 'market_engine', writable: true, signer: true },
        { name: 'escrow_account', writable: true },
        { name: 'user_stake_account', writable: true },
        { name: 'new_stake_account', writable: true, signer: true },
        { name: 'system_program' },
        { name: 'clock' },
        { name: 'stake_program' },
        { name: 'event_authority' },
        { name: 'program' },
        { name: 'stake_history' },
      ],
      args: [
        { name: 'args', type: { defined: { name: 'EscrowUpdateParams' } } },
      ],
    },
    {
      name: 'deposit_to_external_yield',
      discriminator: [88, 6, 147, 2, 130, 180, 9, 189],
      accounts: [
        { name: 'user', writable: true, signer: true },
        { name: 'user_role' },
        { name: 'payer', writable: true, signer: true },
        { name: 'market_engine', writable: true, signer: true },
        { name: 'escrow_account', writable: true },
        { name: 'deposit_mint' },
        { name: 'escrow_deposit_ta', writable: true },
        { name: 'associated_token_program' },
        { name: 'token_program' },
        { name: 'system_program' },
        { name: 'instructions_program' },
        { name: 'event_authority' },
        { name: 'program' },
      ],
      args: [
        {
          name: 'args',
          type: { defined: { name: 'ExternalYieldDepositParams' } },
        },
      ],
    },
    {
      name: 'edit_escrow',
      docs: ['edit escrow account'],
      discriminator: [74, 97, 127, 43, 234, 174, 207, 19],
      accounts: [
        { name: 'user', writable: true, signer: true },
        { name: 'user_role' },
        { name: 'payer', writable: true, signer: true },
        { name: 'market_engine', writable: true, signer: true },
        { name: 'escrow_account', writable: true },
        { name: 'system_program' },
        { name: 'instructions_program' },
      ],
      args: [
        { name: 'params', type: { defined: { name: 'EditEscrowParams' } } },
      ],
    },
    {
      name: 'edit_ledger_account',
      docs: ["ledger ix's"],
      discriminator: [84, 5, 21, 217, 33, 14, 174, 255],
      accounts: [
        { name: 'payer', writable: true, signer: true },
        { name: 'market_engine', writable: true, signer: true },
        { name: 'order', writable: true },
        { name: 'order_ledgers', writable: true },
        { name: 'system_program' },
      ],
      args: [
        { name: 'args', type: { defined: { name: 'EditLedgerAccountArgs' } } },
      ],
    },
    {
      name: 'extend_lut',
      discriminator: [191, 14, 42, 48, 91, 248, 173, 89],
      accounts: [
        { name: 'payer', writable: true, signer: true },
        { name: 'market_engine', writable: true, signer: true },
        { name: 'escrow_account', writable: true },
        { name: 'lut', writable: true },
        { name: 'system_program' },
        { name: 'address_lookup_table_program' },
      ],
      args: [],
    },
    {
      name: 'fill_borrow_order',
      docs: ['fill abf borrow order'],
      discriminator: [102, 4, 167, 76, 131, 170, 93, 19],
      accounts: [
        { name: 'payer', writable: true, signer: true },
        { name: 'user_role' },
        { name: 'filler', writable: true, signer: true },
        { name: 'market_engine', writable: true, signer: true },
        { name: 'order', writable: true },
        { name: 'borrower_escrow_account', writable: true },
        { name: 'lender_escrow_account', writable: true },
        { name: 'loan_vault', writable: true },
        { name: 'collateral_mint' },
        { name: 'principal_mint' },
        { name: 'loan_escrow_account', writable: true },
        { name: 'loan_escrow_collateral_ta', writable: true },
        { name: 'borrower_escrow_collateral_ta', writable: true },
        { name: 'borrower_escrow_principal_ta', writable: true },
        { name: 'lender_escrow_principal_ta', writable: true },
        { name: 'market_fee_account', writable: true },
        { name: 'market_fee_account_principal_ta', writable: true },
        { name: 'associated_token_program' },
        { name: 'token_program' },
        { name: 'system_program' },
      ],
      args: [],
    },
    {
      name: 'fill_lend_order',
      docs: ['fill abf lender order'],
      discriminator: [22, 233, 28, 59, 5, 23, 175, 171],
      accounts: [
        { name: 'payer', writable: true, signer: true },
        { name: 'user_role' },
        { name: 'filler', writable: true, signer: true },
        { name: 'market_engine', writable: true, signer: true },
        { name: 'order', writable: true },
        { name: 'borrower_escrow_account', writable: true },
        { name: 'lender_escrow_account', writable: true },
        { name: 'loan_vault', writable: true },
        { name: 'collateral_mint' },
        { name: 'principal_mint' },
        { name: 'loan_escrow_account', writable: true },
        { name: 'loan_escrow_collateral_ta', writable: true },
        { name: 'borrower_escrow_collateral_ta', writable: true },
        { name: 'filler_principal_ta', writable: true },
        { name: 'lender_escrow_principal_ta', writable: true },
        { name: 'market_fee_account', writable: true },
        { name: 'market_fee_account_principal_ta', writable: true },
        { name: 'associated_token_program' },
        { name: 'token_program' },
        { name: 'token22_program' },
        { name: 'system_program' },
        { name: 'event_authority' },
        { name: 'program' },
      ],
      args: [
        { name: 'args', type: { defined: { name: 'FillLendOrderArgs' } } },
      ],
    },
    {
      name: 'fill_strategy_order',
      discriminator: [75, 204, 165, 17, 38, 151, 70, 50],
      accounts: [
        { name: 'payer', writable: true, signer: true },
        { name: 'strategy', writable: true, signer: true },
        { name: 'market_engine', writable: true, signer: true },
        { name: 'lender_escrow_account', writable: true },
        { name: 'order', writable: true },
        {
          name: 'lender_escrow_principal_ta',
          docs: ['CHECK inner ix check'],
          writable: true,
        },
        { name: 'filler', writable: true, signer: true },
        { name: 'borrower_escrow_account', writable: true },
        { name: 'loan_vault', writable: true },
        { name: 'loan_escrow_account', writable: true },
        { name: 'collateral_mint' },
        { name: 'principal_mint' },
        { name: 'loan_escrow_collateral_ta', writable: true },
        { name: 'borrower_escrow_collateral_ta', writable: true },
        { name: 'filler_principal_ta', writable: true },
        { name: 'market_fee_account', writable: true },
        { name: 'market_fee_account_principal_ta', writable: true },
        { name: 'associated_token_program' },
        { name: 'token_program' },
        { name: 'token22_program' },
        { name: 'system_program' },
        { name: 'event_authority' },
        { name: 'program' },
      ],
      args: [
        {
          name: 'args',
          type: { defined: { name: 'FillStrategyOrderParams' } },
        },
      ],
    },
    {
      name: 'generate_fee',
      docs: ["fee ix's"],
      discriminator: [232, 254, 148, 54, 48, 253, 117, 128],
      accounts: [
        { name: 'payer', writable: true, signer: true },
        { name: 'market_engine', writable: true, signer: true },
        { name: 'order', writable: true },
        { name: 'loan_vault', writable: true },
        { name: 'order_ledgers', writable: true },
        { name: 'fee_account', writable: true },
        { name: 'system_program' },
        { name: 'event_authority' },
        { name: 'program' },
      ],
      args: [
        { name: 'params', type: { defined: { name: 'FeeAccountParams' } } },
      ],
    },
    {
      name: 'liquidate_order',
      discriminator: [79, 9, 75, 143, 119, 217, 161, 131],
      accounts: [
        { name: 'liquidation_manager', signer: true },
        { name: 'order', writable: true },
        { name: 'loan_vault', writable: true },
        { name: 'collateral_mint' },
        { name: 'principal_mint' },
        { name: 'loan_vault_escrow_account' },
        { name: 'loan_vault_escrow_collateral_ta', writable: true },
        { name: 'loan_vault_escrow_principal_ta', writable: true },
        { name: 'principal_recipient_owner', writable: true },
        { name: 'collateral_recipient_owner' },
        { name: 'principal_recipient', writable: true },
        { name: 'collateral_recipient', writable: true },
        { name: 'token_program' },
        { name: 'token22_program' },
        { name: 'system_program' },
        { name: 'event_authority' },
        { name: 'program' },
      ],
      args: [],
    },
    {
      name: 'loan_close',
      discriminator: [223, 3, 149, 81, 4, 60, 249, 244],
      accounts: [
        { name: 'payer', writable: true, signer: true },
        { name: 'loan_vault', writable: true },
        { name: 'order', writable: true },
        { name: 'order_ledgers', writable: true },
        { name: 'loan_escrow_principal_ta', writable: true },
        { name: 'loan_escrow_collateral_ta', writable: true },
        { name: 'loan_escrow_account', writable: true },
        { name: 'principal_mint' },
        { name: 'collateral_mint' },
        { name: 'associated_token_program' },
        { name: 'token_program' },
        { name: 'token22_program' },
        { name: 'system_program' },
        { name: 'event_authority' },
        { name: 'program' },
      ],
      args: [],
    },
    {
      name: 'loan_withdraw',
      discriminator: [238, 114, 126, 234, 110, 133, 104, 84],
      accounts: [
        { name: 'payer', writable: true, signer: true },
        { name: 'loan_vault', writable: true },
        { name: 'order', writable: true },
        { name: 'collateral_mint' },
        { name: 'principal_mint' },
        { name: 'loan_escrow_account', writable: true },
        { name: 'loan_escrow_collateral_ta', writable: true },
        { name: 'loan_escrow_principal_ta', writable: true },
        { name: 'creditor_account', writable: true },
        { name: 'creditor_collateral_ta', writable: true },
        { name: 'creditor_principal_ta', writable: true },
        { name: 'debtor_account', writable: true },
        { name: 'debtor_collateral_ta', writable: true },
        { name: 'associated_token_program' },
        { name: 'token_program' },
        { name: 'token22_program' },
        { name: 'system_program' },
        { name: 'event_authority' },
        { name: 'program' },
      ],
      args: [],
    },
    {
      name: 'mark_default',
      discriminator: [182, 231, 123, 132, 66, 208, 137, 139],
      accounts: [
        { name: 'payer', signer: true },
        { name: 'market_manager', signer: true },
        { name: 'order', writable: true },
      ],
      args: [],
    },
    {
      name: 'mint_credit_note',
      docs: ['credt note ixs'],
      discriminator: [135, 186, 54, 167, 118, 182, 88, 118],
      accounts: [
        { name: 'payer', writable: true, signer: true },
        { name: 'user', writable: true, signer: true },
        { name: 'market_engine', writable: true, signer: true },
        { name: 'user_role' },
        { name: 'loan_vault', writable: true },
        { name: 'credit_note_mint', writable: true, signer: true },
        { name: 'order', writable: true },
        { name: 'creditor_escrow_account', writable: true },
        { name: 'creditor_credit_note_ta', writable: true },
        { name: 'principal_mint' },
        { name: 'loan_escrow_account', writable: true },
        { name: 'loan_escrow_principal_ta', writable: true },
        { name: 'creditor_principal_ta', writable: true },
        { name: 'associated_token_program' },
        { name: 'token_program' },
        { name: 'token_22_program' },
        { name: 'system_program' },
      ],
      args: [],
    },
    {
      name: 'pay_fee',
      discriminator: [98, 25, 152, 0, 46, 9, 186, 61],
      accounts: [
        { name: 'payer', writable: true, signer: true },
        { name: 'user', writable: true, signer: true },
        { name: 'user_role' },
        { name: 'market_engine', writable: true, signer: true },
        { name: 'order', writable: true },
        { name: 'loan_vault', writable: true },
        { name: 'fee_account', writable: true },
        { name: 'fee_mint', writable: true },
        { name: 'loan_escrow_account', writable: true },
        { name: 'user_escrow_account', writable: true },
        { name: 'user_escrow_fee_ta', writable: true },
        { name: 'loan_escrow_fee_ta', writable: true },
        { name: 'associated_token_program' },
        { name: 'token_program' },
        { name: 'system_program' },
        { name: 'event_authority' },
        { name: 'program' },
      ],
      args: [
        { name: 'params', type: { defined: { name: 'FeeAccountParams' } } },
      ],
    },
    {
      name: 'redeem_credit_note',
      discriminator: [89, 17, 29, 226, 22, 197, 194, 183],
      accounts: [
        { name: 'payer', writable: true, signer: true },
        { name: 'user', writable: true, signer: true },
        { name: 'market_engine', writable: true, signer: true },
        { name: 'user_role' },
        { name: 'loan_vault', writable: true },
        { name: 'credit_note_mint', writable: true },
        { name: 'order', writable: true },
        { name: 'creditor_escrow_account', writable: true },
        { name: 'creditor_credit_note_ta', writable: true },
        { name: 'associated_token_program' },
        { name: 'token_program' },
        { name: 'token_22_program' },
        { name: 'system_program' },
      ],
      args: [],
    },
    {
      name: 'refinance_order_complete',
      discriminator: [47, 88, 64, 68, 109, 193, 95, 35],
      accounts: [
        { name: 'payer', writable: true, signer: true },
        { name: 'order', writable: true },
        { name: 'refinanced_order', writable: true },
        { name: 'refinanced_loan_escrow_account', writable: true },
        { name: 'lender_escrow_account', writable: true },
        { name: 'refinanced_loan_vault', writable: true },
        { name: 'loan_vault', writable: true },
        { name: 'collateral_mint' },
        { name: 'principal_mint' },
        { name: 'loan_escrow_account', writable: true },
        { name: 'loan_escrow_collateral_ta', writable: true },
        { name: 'refinanced_loan_lender', writable: true },
        { name: 'refinanced_loan_lender_principal_ta', writable: true },
        { name: 'refinanced_loan_escrow_principal_ta', writable: true },
        { name: 'refinanced_loan_escrow_collateral_ta', writable: true },
        { name: 'lender_escrow_principal_ta', writable: true },
        { name: 'market_fee_account', writable: true },
        { name: 'market_fee_account_principal_ta', writable: true },
        { name: 'associated_token_program' },
        { name: 'token_program' },
        { name: 'token22_program' },
        { name: 'system_program' },
        { name: 'event_authority' },
        { name: 'program' },
      ],
      args: [],
    },
    {
      name: 'refinance_order_setup',
      discriminator: [147, 183, 67, 53, 61, 24, 200, 20],
      accounts: [
        { name: 'payer', writable: true, signer: true },
        { name: 'market_engine', writable: true, signer: true },
        { name: 'strategy', writable: true, signer: true },
        { name: 'refinanced_order', writable: true },
        { name: 'order', writable: true },
        { name: 'refinanced_loan_escrow_account', writable: true },
        { name: 'lender_escrow_account', writable: true },
        { name: 'refinanced_order_ledgers', writable: true },
        { name: 'refinanced_loan_vault', writable: true },
        { name: 'loan_vault', writable: true },
        { name: 'lender_escrow_principal_ta', writable: true },
        { name: 'loan_vault_escrow', writable: true },
        { name: 'collateral_mint' },
        { name: 'principal_mint' },
        { name: 'associated_token_program' },
        { name: 'token_program' },
        { name: 'token22_program' },
        { name: 'system_program' },
        { name: 'event_authority' },
        { name: 'program' },
      ],
      args: [],
      returns: 'u64',
    },
    {
      name: 'repay_loan',
      docs: ["loan ix's", 'repay loan'],
      discriminator: [224, 93, 144, 77, 61, 17, 137, 54],
      accounts: [
        { name: 'user', writable: true, signer: true },
        { name: 'payer', writable: true, signer: true },
        { name: 'market_engine', writable: true, signer: true },
        { name: 'user_role' },
        { name: 'order', writable: true },
        { name: 'loan_vault' },
        { name: 'principal_mint' },
        { name: 'order_ledgers', writable: true },
        { name: 'loan_escrow_account', writable: true },
        { name: 'user_escrow_account', writable: true },
        { name: 'user_escrow_principal_ta', writable: true },
        { name: 'loan_escrow_principal_ta', writable: true },
        { name: 'associated_token_program' },
        { name: 'token_program' },
        { name: 'system_program' },
        { name: 'event_authority' },
        { name: 'program' },
      ],
      args: [
        { name: 'params', type: { defined: { name: 'RepayLoanParams' } } },
      ],
    },
    {
      name: 'sign_in',
      discriminator: [117, 20, 102, 18, 141, 220, 173, 235],
      accounts: [
        { name: 'user', writable: true, signer: true },
        { name: 'market_engine', writable: true, signer: true },
      ],
      args: [],
    },
    {
      name: 'transfer_credit_note',
      discriminator: [152, 18, 175, 85, 232, 167, 94, 129],
      accounts: [
        { name: 'payer', writable: true, signer: true },
        { name: 'user', writable: true, signer: true },
        { name: 'market_engine', writable: true, signer: true },
        { name: 'user_role' },
        { name: 'loan_vault', writable: true },
        { name: 'order' },
        { name: 'seller_escrow_account', writable: true },
        { name: 'buyer_escrow_account', writable: true },
        { name: 'seller_credit_note_ta', writable: true },
        { name: 'buyer_credit_note_ta', writable: true },
        { name: 'credit_note_mint', writable: true },
        { name: 'principal_mint' },
        { name: 'seller_principal_ta' },
        { name: 'buyer_principal_ta' },
        { name: 'order_ledgers' },
        { name: 'associated_token_program' },
        { name: 'token_22_program' },
        { name: 'token_program' },
        { name: 'system_program' },
        { name: 'event_authority' },
        { name: 'program' },
      ],
      args: [
        { name: 'sell_params', type: { defined: { name: 'SellLoanParams' } } },
      ],
    },
    {
      name: 'update_order',
      discriminator: [54, 8, 208, 207, 34, 134, 239, 168],
      accounts: [
        { name: 'payer', writable: true, signer: true },
        { name: 'user', writable: true, signer: true },
        { name: 'user_role', writable: true },
        { name: 'market_engine', writable: true, signer: true },
        { name: 'escrow_account' },
        { name: 'order', writable: true },
        { name: 'loan_vault' },
      ],
      args: [{ name: 'args', type: { defined: { name: 'UpdateOrderArgs' } } }],
    },
    {
      name: 'upsert_ledger_accounts',
      discriminator: [162, 232, 149, 247, 28, 208, 205, 24],
      accounts: [
        { name: 'payer', writable: true, signer: true },
        { name: 'market_engine', writable: true, signer: true },
        { name: 'order', writable: true },
        { name: 'order_ledgers', writable: true },
        { name: 'system_program' },
      ],
      args: [{ name: 'args', type: { defined: { name: 'LedgerUpsertArgs' } } }],
    },
    {
      name: 'withdraw_asset',
      discriminator: [78, 193, 207, 125, 63, 193, 129, 12],
      accounts: [
        { name: 'user', writable: true, signer: true },
        { name: 'user_role' },
        { name: 'payer', writable: true, signer: true },
        { name: 'market_engine', writable: true, signer: true },
        { name: 'escrow_account', writable: true },
        { name: 'deposit_mint' },
        { name: 'owner_withdraw_ta', writable: true },
        { name: 'escrow_deposit_ta', writable: true },
        { name: 'associated_token_program' },
        { name: 'token_program' },
        { name: 'system_program' },
        { name: 'instructions_program' },
        { name: 'event_authority' },
        { name: 'program' },
      ],
      args: [
        { name: 'args', type: { defined: { name: 'EscrowWithdrawParams' } } },
      ],
    },
    {
      name: 'withdraw_from_external_yield',
      discriminator: [111, 121, 216, 159, 50, 40, 218, 33],
      accounts: [
        { name: 'user', writable: true, signer: true },
        { name: 'user_role' },
        { name: 'payer', writable: true, signer: true },
        { name: 'market_engine', writable: true, signer: true },
        { name: 'escrow_account' },
        { name: 'deposit_mint' },
        { name: 'escrow_deposit_ta', writable: true },
        { name: 'associated_token_program' },
        { name: 'token_program' },
        { name: 'system_program' },
        { name: 'instructions_program' },
        { name: 'event_authority' },
        { name: 'program' },
      ],
      args: [
        {
          name: 'args',
          type: { defined: { name: 'ExternalYieldWithdrawParams' } },
        },
      ],
    },
    {
      name: 'withdraw_staked_sol',
      discriminator: [246, 241, 107, 108, 181, 37, 25, 164],
      accounts: [
        { name: 'user', writable: true, signer: true },
        { name: 'user_role' },
        { name: 'payer', writable: true, signer: true },
        { name: 'market_engine', writable: true, signer: true },
        { name: 'escrow_account', writable: true },
        { name: 'program_stake_account', writable: true },
        { name: 'new_stake_account', writable: true, signer: true },
        { name: 'system_program' },
        { name: 'clock' },
        { name: 'stake_program' },
        { name: 'event_authority' },
        { name: 'program' },
        { name: 'stake_history' },
      ],
      args: [
        { name: 'args', type: { defined: { name: 'EscrowUpdateParams' } } },
      ],
    },
  ],
  accounts: [
    {
      name: 'EscrowAccount',
      discriminator: [36, 69, 48, 18, 128, 225, 125, 135],
    },
    {
      name: 'ExternalYieldAccount',
      discriminator: [130, 117, 239, 61, 204, 174, 181, 198],
    },
    {
      name: 'FeeAccount',
      discriminator: [137, 191, 201, 34, 168, 222, 43, 138],
    },
    { name: 'LoanVault', discriminator: [70, 164, 79, 174, 234, 185, 25, 181] },
    { name: 'Order', discriminator: [134, 173, 223, 185, 77, 86, 28, 51] },
    {
      name: 'OrderLedgers',
      discriminator: [59, 169, 222, 60, 224, 142, 68, 173],
    },
    {
      name: 'RoleAccount',
      discriminator: [142, 236, 135, 197, 214, 3, 244, 226],
    },
    { name: 'StakeAccount', discriminator: [0, 0, 0, 0, 0, 0, 0, 0] },
  ],
  events: [
    {
      name: 'EscrowCloseTAEvent',
      discriminator: [241, 206, 224, 255, 107, 85, 95, 16],
    },
    {
      name: 'EscrowRoleEditEvent',
      discriminator: [95, 102, 49, 241, 69, 212, 104, 47],
    },
    {
      name: 'EscrowStakedSolEvent',
      discriminator: [147, 50, 251, 201, 240, 47, 144, 45],
    },
    {
      name: 'FeeEditEvent',
      discriminator: [35, 119, 116, 77, 167, 122, 229, 178],
    },
    {
      name: 'LiquidateEvent',
      discriminator: [158, 94, 144, 4, 147, 52, 5, 255],
    },
    {
      name: 'LiquidationAssetMetadata',
      discriminator: [79, 42, 139, 32, 11, 26, 232, 238],
    },
    {
      name: 'LoanRefinanceEvent',
      discriminator: [224, 59, 53, 57, 26, 132, 60, 147],
    },
    {
      name: 'LoanVaultCloseEvent',
      discriminator: [38, 123, 12, 180, 130, 57, 181, 232],
    },
    {
      name: 'RoleCloseEvent',
      discriminator: [69, 242, 23, 59, 239, 181, 143, 228],
    },
    {
      name: 'RoleEditEvent',
      discriminator: [125, 89, 29, 252, 191, 207, 221, 179],
    },
    {
      name: 'SellLoanEvent',
      discriminator: [72, 173, 245, 27, 57, 106, 36, 153],
    },
  ],
  errors: [
    {
      code: 6000,
      name: 'NextDueLedgerAccountInvalid',
      msg: 'Next due ledger account is invalid.',
    },
    {
      code: 6001,
      name: 'LastDueLedgerAccountInvalid',
      msg: 'Last due ledger account is invalid.',
    },
    {
      code: 6002,
      name: 'LedgerAccountsNotConsecutive',
      msg: 'Ledger accounts passed in are not consecutive.',
    },
    {
      code: 6003,
      name: 'WrongProgramCPI',
      msg: 'Cpi program expected to be right',
    },
    {
      code: 6004,
      name: 'UserRoleAccountInvalid',
      msg: 'User role account is invalid.',
    },
    {
      code: 6005,
      name: 'FeeAccountAddress',
      msg: 'Fee account address is invalid.',
    },
    {
      code: 6006,
      name: 'DesignatedTakerCannotBeMaker',
      msg: 'Designated taker cannot be the same as the maker.',
    },
    {
      code: 6007,
      name: 'InsufficientCollateral',
      msg: 'Insufficient collateral in the escrow account.',
    },
    {
      code: 6008,
      name: 'InsufficientPrincipal',
      msg: 'Insufficient principal in the escrow account.',
    },
    {
      code: 6009,
      name: 'StakeAccountInvalid',
      msg: 'Stake account is invalid.',
    },
    {
      code: 6010,
      name: 'EscrowEventMathError',
      msg: 'Over/underflow error on Escrow Event creation.',
    },
    { code: 6011, name: 'InvalidLedgerId', msg: 'Invalid ledger id' },
    {
      code: 6012,
      name: 'InvalidLedgerIdOrder',
      msg: 'Ledger id order is invalid',
    },
    { code: 6013, name: 'LoanDefaulted', msg: 'Loan is defaulted' },
    {
      code: 6014,
      name: 'CouldntFindLastDueLedgerAccount',
      msg: 'Couldnt find the last due ledger account',
    },
    {
      code: 6015,
      name: 'CouldntFindNextDueLedgerAccount',
      msg: 'Couldnt find the next due ledger account',
    },
    {
      code: 6016,
      name: 'EscrowAccountInvalid',
      msg: 'Escrow account is invalid',
    },
    { code: 6017, name: 'ArithmeticOverflow', msg: 'Arithmetic overflow' },
    { code: 6018, name: 'InvalidOrderLedgers', msg: 'Invalid order ledgers' },
    {
      code: 6019,
      name: 'RefinancePrincipalAmountTooLow',
      msg: 'Refinance order principal amount too low',
    },
    { code: 6020, name: 'InvalidLender', msg: 'Refinance loan lender wrong' },
    {
      code: 6021,
      name: 'ExternalYieldAlreadyEnabled',
      msg: 'External yield is already enabled for this escrow',
    },
  ],
  types: [
    {
      name: 'CreateEscrowParams',
      type: {
        kind: 'struct',
        fields: [
          { name: 'organization_identifier', type: 'pubkey' },
          { name: 'nonce', type: 'pubkey' },
          { name: 'origination_cap', type: 'u64' },
          { name: 'external_yield_source', type: 'u8' },
          { name: 'principal_mint', type: { option: 'pubkey' } },
        ],
      },
    },
    {
      name: 'CreateExternalYieldForEscrowParams',
      type: {
        kind: 'struct',
        fields: [
          { name: 'external_yield_source', type: 'u8' },
          { name: 'principal_mint', type: 'pubkey' },
        ],
      },
    },
    {
      name: 'CreateOrderParams',
      type: {
        kind: 'struct',
        fields: [
          { name: 'principal_amount', type: 'u64' },
          { name: 'collateral_amount', type: 'u64' },
          { name: 'maker_role', type: 'u8' },
          { name: 'max_outstanding_payments', type: 'u64' },
          { name: 'funding_type', type: 'u8' },
          { name: 'allow_early_repayments', type: 'bool' },
          { name: 'origination_fee', type: 'u64' },
          { name: 'liquidation_threshold', type: 'u64' },
          { name: 'refinance_enabled', type: 'bool' },
          { name: 'max_refinance_apy', type: 'u64' },
          { name: 'refinance_duration', type: 'i64' },
          { name: 'refinance_duration_type', type: 'u8' },
        ],
      },
    },
    {
      name: 'CreateStrategyOrderParams',
      type: {
        kind: 'struct',
        fields: [
          { name: 'principal_amount', type: 'u64' },
          { name: 'collateral_amount', type: 'u64' },
          { name: 'origination_fee', type: 'u64' },
          { name: 'liquidation_threshold', type: 'u64' },
          { name: 'refinance_enabled', type: 'bool' },
          { name: 'max_refinance_apy', type: 'u64' },
          { name: 'refinance_duration', type: 'i64' },
          { name: 'refinance_duration_type', type: 'u8' },
          {
            name: 'ledger',
            type: { defined: { name: 'LedgerCreateOrUpdateArgs' } },
          },
          { name: 'order_status', type: 'u8' },
        ],
      },
    },
    {
      name: 'DeleteLedgerAccountArgs',
      type: {
        kind: 'struct',
        fields: [{ name: 'ledger_ids', type: { vec: 'u64' } }],
      },
    },
    {
      name: 'EditEscrowParams',
      type: {
        kind: 'struct',
        fields: [
          { name: 'origination_cap', type: 'u64' },
          { name: 'external_yield_source', type: 'u8' },
        ],
      },
    },
    {
      name: 'EditLedgerAccountArgs',
      type: {
        kind: 'struct',
        fields: [
          {
            name: 'updates',
            type: { vec: { defined: { name: 'EditLedgerAccountParams' } } },
          },
        ],
      },
    },
    {
      name: 'EditLedgerAccountParams',
      docs: [
        '* This ix is to be called by the BE to process early repayments and handle amortization cases',
      ],
      type: {
        kind: 'struct',
        fields: [
          { name: 'ledger_id', type: 'u64' },
          { name: 'principal_due', type: { option: 'u64' } },
          { name: 'interest_due', type: { option: 'u64' } },
          { name: 'due_time_offset', type: { option: 'i64' } },
        ],
      },
    },
    {
      name: 'EscrowAccount',
      docs: ["Escrow account to keep track of user's escrowed assets"],
      type: {
        kind: 'struct',
        fields: [
          {
            name: 'organization_identifier',
            docs: ['organization that owns the escrow account'],
            type: 'pubkey',
          },
          {
            name: 'num_escrowed',
            docs: ['DEPRECATED AND NOT UPDATED number of escrowed assets'],
            type: 'u64',
          },
          {
            name: 'nonce',
            docs: [
              'nonce for potentially supporting multiple escrows/user. For now this will always be default pubkey',
            ],
            type: 'pubkey',
          },
          {
            name: 'origination_cap',
            docs: ['origination cap, set to u64 MAX if no cap'],
            type: 'u64',
          },
          {
            name: 'cumulative_amount_originated',
            docs: ['cumulative value of amount originated'],
            type: 'u64',
          },
          {
            name: 'external_yield_source',
            docs: ['external yield source'],
            type: 'u8',
          },
          {
            name: 'buffer_1',
            docs: [
              'buffer for potential future use, 112 bytes, 64 + 32 + 16 = 112',
            ],
            type: { array: ['u8', 64] },
          },
          { name: 'buffer_2', type: { array: ['u8', 32] } },
          { name: 'buffer_3', type: { array: ['u8', 15] } },
        ],
      },
    },
    {
      name: 'EscrowCloseTAEvent',
      type: {
        kind: 'struct',
        fields: [
          { name: 'escrow_address', type: 'string' },
          { name: 'asset_mint', type: 'string' },
        ],
      },
    },
    {
      name: 'EscrowRole',
      repr: { kind: 'rust' },
      type: { kind: 'enum', variants: [{ name: 'OrderManager' }] },
    },
    {
      name: 'EscrowRoleEditEvent',
      type: {
        kind: 'struct',
        fields: [
          { name: 'address', type: 'string' },
          { name: 'user', type: 'string' },
          { name: 'escrow_account', type: 'string' },
          { name: 'role', type: 'u32' },
        ],
      },
    },
    {
      name: 'EscrowRoleParams',
      type: {
        kind: 'struct',
        fields: [
          { name: 'user', type: 'pubkey' },
          { name: 'role', type: { defined: { name: 'EscrowRole' } } },
          { name: 'escrow_account', type: 'pubkey' },
        ],
      },
    },
    {
      name: 'EscrowStakedSolEvent',
      type: {
        kind: 'struct',
        fields: [
          { name: 'escrow_address', type: 'string' },
          { name: 'nonce', type: 'string' },
          { name: 'escrower', type: 'string' },
          { name: 'amount', type: 'u64' },
          { name: 'stake_account_address', type: 'string' },
          {
            name: 'transaction_type',
            type: { defined: { name: 'EscrowTransactionType' } },
          },
          {
            name: 'stake_account',
            type: { option: { defined: { name: 'ParsedStakeAccount' } } },
          },
        ],
      },
    },
    {
      name: 'EscrowTransactionType',
      repr: { kind: 'rust' },
      type: {
        kind: 'enum',
        variants: [{ name: 'Deposit' }, { name: 'Withdrawal' }],
      },
    },
    {
      name: 'EscrowUpdateParams',
      type: {
        kind: 'struct',
        fields: [
          { name: 'organization_identifier', type: 'pubkey' },
          { name: 'escrow_nonce', type: 'pubkey' },
          { name: 'amount', type: 'u64' },
          { name: 'use_external_yield', type: 'bool' },
        ],
      },
    },
    {
      name: 'EscrowWithdrawParams',
      type: {
        kind: 'struct',
        fields: [
          { name: 'amount', type: 'u64' },
          { name: 'withdraw_all', type: { option: 'bool' } },
          { name: 'use_external_yield', type: 'bool' },
        ],
      },
    },
    { name: 'ExternalYieldAccount', type: { kind: 'struct', fields: [] } },
    {
      name: 'ExternalYieldDepositParams',
      type: {
        kind: 'struct',
        fields: [
          { name: 'organization_identifier', type: 'pubkey' },
          { name: 'escrow_nonce', type: 'pubkey' },
        ],
      },
    },
    {
      name: 'ExternalYieldWithdrawParams',
      type: {
        kind: 'struct',
        fields: [
          { name: 'amount', type: 'u64' },
          { name: 'withdraw_all', type: { option: 'bool' } },
        ],
      },
    },
    {
      name: 'FeeAccount',
      docs: ['Fee Account'],
      type: {
        kind: 'struct',
        fields: [
          { name: 'ledger_id', docs: ['ledger id'], type: 'u64' },
          { name: 'amount_due', docs: ['amount to pay for fee'], type: 'u64' },
          { name: 'amount_paid', docs: ['amount paid'], type: 'u64' },
          {
            name: 'buffer',
            docs: ['buffer for potential future use'],
            type: { array: ['u8', 128] },
          },
        ],
      },
    },
    {
      name: 'FeeAccountParams',
      docs: [
        '* This ix is to be called by the BE to add a fee payment based from off-chain logic',
      ],
      type: {
        kind: 'struct',
        fields: [
          { name: 'ledger_id', type: 'u64' },
          { name: 'fee_type', type: 'u8' },
          { name: 'amount', type: 'u64' },
        ],
      },
    },
    {
      name: 'FeeEditEvent',
      type: {
        kind: 'struct',
        fields: [
          { name: 'address', type: 'string' },
          { name: 'loan_vault', type: 'string' },
          { name: 'ledger_id', type: 'u64' },
          { name: 'amount_due', type: 'u64' },
          { name: 'amount_paid', type: 'u64' },
          { name: 'fee_type', type: 'u8' },
        ],
      },
    },
    {
      name: 'FillLendOrderArgs',
      type: {
        kind: 'struct',
        fields: [
          {
            name: 'use_recipient_escrow',
            docs: [
              'send principal to recipient escrow. If false, will send to filler. Debt note is still always sent to escrow.',
            ],
            type: 'bool',
          },
        ],
      },
    },
    {
      name: 'FillStrategyOrderParams',
      type: {
        kind: 'struct',
        fields: [
          { name: 'principal_amount', type: 'u64' },
          { name: 'collateral_amount', type: 'u64' },
          { name: 'origination_fee', type: 'u64' },
          { name: 'remaining_accounts_index', type: 'u64' },
        ],
      },
    },
    {
      name: 'Ledger',
      docs: ['Ledger Account to keep track of repayment schedule'],
      type: {
        kind: 'struct',
        fields: [
          {
            name: 'ledger_id',
            docs: ['integer ID of the payment, increments starting with 1'],
            type: 'u64',
          },
          {
            name: 'principal_due',
            docs: [
              'key of the order this charge is used for',
              'principal amount owed for this payment',
            ],
            type: 'u64',
          },
          {
            name: 'principal_repaid',
            docs: ['principal amount paid back to this payment'],
            type: 'u64',
          },
          {
            name: 'interest_due',
            docs: ['interst due for this payment'],
            type: 'u64',
          },
          {
            name: 'interest_repaid',
            docs: ['interest amount paid back to this payment'],
            type: 'u64',
          },
          {
            name: 'due_time_offset',
            docs: ['seconds after loan start time'],
            type: 'i64',
          },
          { name: 'paid_time', type: 'i64' },
          { name: 'payment_type', docs: ['ledger type'], type: 'u8' },
          {
            name: 'is_filled',
            docs: [
              'whether or not the payments have been made for this account',
            ],
            type: 'bool',
          },
          {
            name: 'grace_period',
            docs: ['Grace period for ledger default'],
            type: 'i64',
          },
          {
            name: 'late_payment_fee',
            docs: ['late payment fee on ledger, bps of outstadning'],
            type: 'u64',
          },
          {
            name: 'early_payment_fee',
            docs: ['early payment fee on ledger, bps of early payment'],
            type: 'u64',
          },
          {
            name: 'payment_window',
            docs: ['payment window for when a payment is counted as early'],
            type: 'i64',
          },
          {
            name: 'reserve',
            docs: ['reserve space'],
            type: { array: ['u8', 32] },
          },
        ],
      },
    },
    {
      name: 'LedgerCreateOrUpdateArgs',
      type: {
        kind: 'struct',
        fields: [
          { name: 'ledger_id', type: 'u64' },
          { name: 'principal_due', type: 'u64' },
          { name: 'interest_due', type: 'u64' },
          { name: 'due_time_offset', type: 'i64' },
          { name: 'payment_type', type: 'u8' },
          { name: 'grace_period', type: 'i64' },
          { name: 'late_payment_fee', type: 'u64' },
          { name: 'early_payment_fee', type: 'u64' },
          { name: 'payment_window', type: 'i64' },
        ],
      },
    },
    {
      name: 'LedgerUpsertArgs',
      type: {
        kind: 'struct',
        fields: [
          {
            name: 'ledgers',
            type: { vec: { defined: { name: 'LedgerCreateOrUpdateArgs' } } },
          },
          { name: 'is_final', type: 'bool' },
        ],
      },
    },
    {
      name: 'LiquidateEvent',
      type: {
        kind: 'struct',
        fields: [
          { name: 'liquidator', type: 'string' },
          {
            name: 'metadata',
            type: { vec: { defined: { name: 'LiquidationAssetMetadata' } } },
          },
          { name: 'loan_address', type: 'string' },
          { name: 'current_loan_ratio', type: 'f64' },
          { name: 'liquidation_threshold', type: 'f64' },
          { name: 'liquidation_timestamp', type: 'i64' },
        ],
      },
    },
    {
      name: 'LiquidationAssetMetadata',
      type: {
        kind: 'struct',
        fields: [
          { name: 'mint', type: 'string' },
          { name: 'oracle_account', type: 'string' },
          { name: 'price', type: 'f64' },
          { name: 'quantity', type: 'f64' },
          { name: 'decimals', type: 'u8' },
          { name: 'mint_type', type: 'u8' },
          { name: 'quote_mint', type: 'string' },
        ],
      },
    },
    {
      name: 'LoanRefinanceEvent',
      type: {
        kind: 'struct',
        fields: [
          { name: 'refinanced_from', type: 'string' },
          { name: 'refinanced_to', type: 'string' },
        ],
      },
    },
    {
      name: 'LoanVault',
      type: {
        kind: 'struct',
        fields: [
          { name: 'order', docs: ['order account'], type: 'pubkey' },
          { name: 'lender', docs: ['lender pubkey'], type: 'pubkey' },
          { name: 'borrower', docs: ['borrower pubkey'], type: 'pubkey' },
          { name: 'collateral', docs: ['collateral mint'], type: 'pubkey' },
          {
            name: 'debt_note',
            docs: [
              'debt note',
              "this is the mint of the nft that is minted to the borrower's escrow account",
            ],
            type: 'pubkey',
          },
          {
            name: 'credit_note',
            docs: [
              'credit note',
              "this is the mint of the nft that is minted to the lender's escrow account",
              'holding this will allow the lender to claim the collateral if the borrower does not repay',
            ],
            type: 'pubkey',
          },
          {
            name: 'credit_claimed',
            docs: ['has the collateral been right claimed by the lender'],
            type: 'bool',
          },
          {
            name: 'debt_claimed',
            docs: [
              'obligation claimed',
              'borrower has repaid the loan and claimed back the obligation',
            ],
            type: 'bool',
          },
          {
            name: 'loan_start_time',
            docs: ['loan start timestamp'],
            type: 'i64',
          },
          {
            name: 'num_fees_outstanding',
            docs: ['number of unpaid fee accounts'],
            type: 'u64',
          },
          {
            name: 'fees_received',
            docs: ['amount of fees received, used in credit claim'],
            type: 'u64',
          },
          { name: 'amount_claimed', docs: ['amount claimed'], type: 'u64' },
          {
            name: 'buffer_0',
            docs: [
              'buffer for potential future use, need to split up 120 bytes',
            ],
            type: { array: ['u8', 64] },
          },
          {
            name: 'buffer_1',
            docs: [
              'buffer for potential future use, need to split up 120 bytes',
            ],
            type: { array: ['u8', 32] },
          },
          {
            name: 'buffer_2',
            docs: [
              'buffer for potential future use, need to split up 120 bytes',
            ],
            type: { array: ['u8', 8] },
          },
        ],
      },
    },
    {
      name: 'LoanVaultCloseEvent',
      type: {
        kind: 'struct',
        fields: [
          { name: 'loan_address', type: 'string' },
          {
            name: 'loan_credit_claimed',
            docs: ['has the collateral been right claimed by the lender'],
            type: 'bool',
          },
          {
            name: 'loan_debt_claimed',
            docs: [
              'obligation claimed',
              'borrower has repaid the loan and claimed back the obligation',
            ],
            type: 'bool',
          },
          { name: 'order_address', docs: ['address'], type: 'string' },
          { name: 'order_status', docs: ['order status'], type: 'u8' },
          {
            name: 'order_default_type',
            docs: ['default type of the loan'],
            type: 'u8',
          },
          {
            name: 'ledgers',
            docs: ['order ledgers before close'],
            type: { vec: { defined: { name: 'Ledger' } } },
          },
        ],
      },
    },
    {
      name: 'Order',
      type: {
        kind: 'struct',
        fields: [
          { name: 'version', docs: ['loan version'], type: 'u8' },
          {
            name: 'nonce',
            docs: ['nonce for supporting multiple orders/user'],
            type: 'pubkey',
          },
          { name: 'maker', docs: ['order maker pubkey'], type: 'pubkey' },
          {
            name: 'designated_taker',
            docs: [
              'intended taker pubkey',
              'this can be set to default to allow the order to be filled by any user',
            ],
            type: 'pubkey',
          },
          { name: 'principal_mint', docs: ['principal mint'], type: 'pubkey' },
          { name: 'principal_amount', docs: ['principal amount'], type: 'u64' },
          {
            name: 'collateral_mint',
            docs: ['collateral mint'],
            type: 'pubkey',
          },
          {
            name: 'collateral_amount',
            docs: ['collateral amount'],
            type: 'u64',
          },
          { name: 'maker_role', docs: ['order type'], type: 'u8' },
          {
            name: 'last_updated_slot',
            docs: ['last updated slot'],
            type: 'u64',
          },
          {
            name: 'max_outstanding_payments',
            docs: [
              'max outstanding payments accepted until order is defaulted',
            ],
            type: 'u64',
          },
          {
            name: 'last_payment_id',
            docs: [
              'id of the last ledger account for which payment has been made',
            ],
            type: 'u64',
          },
          {
            name: 'final_payment_id',
            docs: [
              'id of the final ledger account for which payment has to be made for',
            ],
            type: 'u64',
          },
          {
            name: 'final_payment_time_offset',
            docs: ['final payment time'],
            type: 'i64',
          },
          { name: 'status', docs: ['order status'], type: 'u8' },
          {
            name: 'default_type',
            docs: ['default type of the loan'],
            type: 'u8',
          },
          { name: 'created_at', docs: ['order created at'], type: 'i64' },
          {
            name: 'funding_type',
            docs: ['funding type of the order'],
            type: 'u8',
          },
          {
            name: 'allow_early_repayments',
            docs: ['recalculate interest on early repayments'],
            type: 'bool',
          },
          {
            name: 'origination_fee',
            docs: ['recalculate interest on early repayments'],
            type: 'u64',
          },
          {
            name: 'liquidation_manager',
            docs: [
              'this is the authority that has the ability to liquidate the loan once it is marked as default',
            ],
            type: 'pubkey',
          },
          {
            name: 'market_manager',
            docs: [
              'this is the authority that has the ability to mark a loan as defaulted based on external oracles',
            ],
            type: 'pubkey',
          },
          {
            name: 'liquidation_threshold',
            docs: [
              'this is the minimum (loan value / collateral value at any point) * 10_000 * 100, below which the loan will be liquidated',
            ],
            type: 'u64',
          },
          {
            name: 'refinance_enabled',
            docs: ['refinance enabled'],
            type: 'bool',
          },
          {
            name: 'max_refinance_apy',
            docs: ['max refinance apy in cbps'],
            type: 'u64',
          },
          {
            name: 'refinance_duration',
            docs: ['refinance duration'],
            type: 'i64',
          },
          {
            name: 'refinance_duration_type',
            docs: ['refinance duration type'],
            type: 'u8',
          },
          { name: 'buffer_3', docs: ['buffer'], type: { array: ['u8', 19] } },
        ],
      },
    },
    {
      name: 'OrderLedgers',
      type: {
        kind: 'struct',
        fields: [
          { name: 'version', type: 'u8' },
          { name: 'order', type: 'pubkey' },
          { name: 'ledgers', type: { vec: { defined: { name: 'Ledger' } } } },
        ],
      },
    },
    {
      name: 'ParsedStakeAccount',
      type: {
        kind: 'struct',
        fields: [
          { name: 'amount', type: 'u64' },
          { name: 'stake_account', type: 'string' },
          { name: 'owner', type: 'string' },
          { name: 'rent_exempt_reserve', type: 'u64' },
          { name: 'authorized_staker', type: 'string' },
          { name: 'authorized_withdrawer', type: 'string' },
          { name: 'lockup_unix_timestamp', type: 'i64' },
          { name: 'lockup_epoch', type: 'u64' },
          { name: 'lockup_pubkey', type: 'string' },
          { name: 'delegation_voter_pubkey', type: 'string' },
          { name: 'delegation_stake', type: 'u64' },
          { name: 'delegation_activation_epoch', type: 'u64' },
          { name: 'delegation_deactivation_epoch', type: 'u64' },
          { name: 'credits_observed', type: 'u64' },
        ],
      },
    },
    {
      name: 'RepayLoanParams',
      type: {
        kind: 'struct',
        fields: [
          { name: 'amount', type: 'u64' },
          {
            name: 'repayment_type',
            type: { defined: { name: 'RepaymentType' } },
          },
          { name: 'overpay', type: 'bool' },
          { name: 'ledger_id', type: 'u64' },
        ],
      },
    },
    {
      name: 'RepaymentType',
      repr: { kind: 'rust' },
      type: {
        kind: 'enum',
        variants: [{ name: 'Principal' }, { name: 'Interest' }],
      },
    },
    {
      name: 'Role',
      repr: { kind: 'rust' },
      type: {
        kind: 'enum',
        variants: [
          { name: 'Member' },
          { name: 'EscrowManager' },
          { name: 'Borrower' },
          { name: 'Lender' },
          { name: 'Admin' },
          { name: 'SuperAdmin' },
          { name: 'OrderManager' },
        ],
      },
    },
    {
      name: 'RoleAccount',
      docs: [
        'Role account to keep track of user roles.',
        '',
        'If a user has multiple roles then they have multiple role accounts.',
        'Each ix will require a set of role accounts, all of which must  be passed in.',
        'e.g to create borrow order oyu need the borrower role.',
        'The created account is the proof or role, to remove a role close the role account.',
      ],
      type: { kind: 'struct', fields: [] },
    },
    {
      name: 'RoleCloseEvent',
      type: { kind: 'struct', fields: [{ name: 'address', type: 'string' }] },
    },
    {
      name: 'RoleEditEvent',
      type: {
        kind: 'struct',
        fields: [
          { name: 'address', type: 'string' },
          { name: 'user', type: 'string' },
          { name: 'organization_identifier', type: 'string' },
          { name: 'role', type: 'u32' },
        ],
      },
    },
    {
      name: 'RoleParams',
      type: {
        kind: 'struct',
        fields: [
          { name: 'user', type: 'pubkey' },
          { name: 'role', type: { defined: { name: 'Role' } } },
          { name: 'organization_identifier', type: 'pubkey' },
        ],
      },
    },
    {
      name: 'SellLoanEvent',
      type: {
        kind: 'struct',
        fields: [
          { name: 'seller', docs: ['seller'], type: 'string' },
          { name: 'buyer', docs: ['buyer'], type: 'string' },
          { name: 'loan_vault', docs: ['loan being sold'], type: 'string' },
          { name: 'sell_amount', docs: ['sell amount'], type: 'u64' },
          { name: 'seller_apy', docs: ['seller apy (display)'], type: 'u64' },
          { name: 'buyer_apy', docs: ['buyer apy (display)'], type: 'u64' },
          {
            name: 'interest_paid',
            docs: ['interest paid (display)'],
            type: 'u64',
          },
          {
            name: 'principal_paid',
            docs: ['principal paid (display)'],
            type: 'u64',
          },
          { name: 'fees_paid', docs: ['fees paid (display)'], type: 'u64' },
        ],
      },
    },
    {
      name: 'SellLoanParams',
      type: {
        kind: 'struct',
        fields: [
          { name: 'sell_amount', type: 'u64' },
          { name: 'amount_claimed', type: 'u64' },
          { name: 'seller_apy', type: 'u64' },
          { name: 'buyer_apy', type: 'u64' },
          { name: 'seller_withdraw', type: 'bool' },
        ],
      },
    },
    { name: 'StakeAccount', type: { kind: 'struct', fields: [] } },
    {
      name: 'UpdateOrderArgs',
      type: {
        kind: 'struct',
        fields: [
          { name: 'liquidation_manager', type: { option: 'pubkey' } },
          { name: 'max_refinance_apy', type: { option: 'u64' } },
          { name: 'refinance_enabled', type: { option: 'bool' } },
          { name: 'refinance_duration', type: { option: 'i64' } },
          { name: 'refinance_duration_type', type: { option: 'u8' } },
        ],
      },
    },
  ],
};
