export const ensofiIdl = {
  version: '0.3.2',
  name: 'enso_lending',
  instructions: [
    {
      name: 'initSettingAccount',
      accounts: [
        { name: 'owner', isMut: true, isSigner: true },
        { name: 'receiver', isMut: false, isSigner: false },
        { name: 'settingAccount', isMut: true, isSigner: false },
        { name: 'systemProgram', isMut: false, isSigner: false },
      ],
      args: [
        { name: 'tierId', type: 'string' },
        { name: 'amount', type: 'u64' },
        { name: 'duration', type: 'u64' },
        { name: 'lenderFeePercent', type: 'f64' },
        { name: 'borrowerFeePercent', type: 'f64' },
      ],
    },
    {
      name: 'editSettingAccount',
      accounts: [
        { name: 'owner', isMut: true, isSigner: true },
        { name: 'receiver', isMut: false, isSigner: false },
        { name: 'settingAccount', isMut: true, isSigner: false },
        { name: 'systemProgram', isMut: false, isSigner: false },
      ],
      args: [
        { name: 'tierId', type: 'string' },
        { name: 'amount', type: { option: 'u64' } },
        { name: 'duration', type: { option: 'u64' } },
        { name: 'lenderFeePercent', type: { option: 'f64' } },
        { name: 'borrowerFeePercent', type: { option: 'f64' } },
      ],
    },
    {
      name: 'closeSettingAccount',
      accounts: [
        { name: 'owner', isMut: true, isSigner: true },
        { name: 'settingAccount', isMut: true, isSigner: false },
        { name: 'systemProgram', isMut: false, isSigner: false },
      ],
      args: [{ name: 'tierId', type: 'string' }],
    },
    {
      name: 'initAsset',
      accounts: [
        { name: 'owner', isMut: true, isSigner: true },
        { name: 'tokenMint', isMut: false, isSigner: false },
        { name: 'asset', isMut: true, isSigner: false },
        { name: 'priceFeedAccount', isMut: false, isSigner: false },
        { name: 'systemProgram', isMut: false, isSigner: false },
      ],
      args: [
        { name: 'name', type: 'string' },
        { name: 'isLend', type: 'bool' },
        { name: 'isCollateral', type: 'bool' },
        { name: 'priceFeedId', type: 'string' },
        { name: 'maxPriceAgeSeconds', type: 'u64' },
      ],
    },
    {
      name: 'editAsset',
      accounts: [
        { name: 'owner', isMut: true, isSigner: true },
        { name: 'tokenMint', isMut: false, isSigner: false },
        { name: 'asset', isMut: true, isSigner: false },
        {
          name: 'priceFeedAccount',
          isMut: false,
          isSigner: false,
          isOptional: true,
        },
      ],
      args: [
        { name: 'name', type: { option: 'string' } },
        { name: 'isLend', type: { option: 'bool' } },
        { name: 'isCollateral', type: { option: 'bool' } },
        { name: 'priceFeedId', type: { option: 'string' } },
        { name: 'maxPriceAgeSeconds', type: { option: 'u64' } },
      ],
    },
    {
      name: 'initVaultAuthority',
      accounts: [
        { name: 'borrower', isMut: true, isSigner: true },
        { name: 'vaultAuthority', isMut: true, isSigner: false },
        { name: 'systemProgram', isMut: false, isSigner: false },
      ],
      args: [],
    },
    {
      name: 'createLendOffer',
      accounts: [
        { name: 'lender', isMut: true, isSigner: true },
        { name: 'lendAsset', isMut: false, isSigner: false },
        { name: 'mintAsset', isMut: false, isSigner: false },
        { name: 'lenderAtaAsset', isMut: true, isSigner: false },
        { name: 'settingAccount', isMut: false, isSigner: false },
        { name: 'lendOffer', isMut: true, isSigner: false },
        { name: 'hotWalletAta', isMut: true, isSigner: false },
        { name: 'tokenProgram', isMut: false, isSigner: false },
        { name: 'systemProgram', isMut: false, isSigner: false },
      ],
      args: [
        { name: 'offerId', type: 'string' },
        { name: 'tierId', type: 'string' },
        { name: 'interest', type: 'f64' },
      ],
    },
    {
      name: 'editLendOffer',
      accounts: [
        { name: 'lender', isMut: true, isSigner: true },
        { name: 'lendOffer', isMut: true, isSigner: false },
      ],
      args: [
        { name: 'offerId', type: 'string' },
        { name: 'interest', type: 'f64' },
      ],
    },
    {
      name: 'systemCancelLendOffer',
      accounts: [
        { name: 'lender', isMut: false, isSigner: false },
        { name: 'lenderAtaAsset', isMut: true, isSigner: false },
        { name: 'mintAsset', isMut: false, isSigner: false },
        { name: 'lendOffer', isMut: true, isSigner: false },
        { name: 'system', isMut: true, isSigner: true },
        { name: 'systemAta', isMut: true, isSigner: false },
        { name: 'tokenProgram', isMut: false, isSigner: false },
      ],
      args: [
        { name: 'offerId', type: 'string' },
        { name: 'tierId', type: 'string' },
        { name: 'waitingInterest', type: 'u64' },
      ],
    },
    {
      name: 'cancelLendOffer',
      accounts: [
        { name: 'lender', isMut: true, isSigner: true },
        { name: 'lendOffer', isMut: true, isSigner: false },
      ],
      args: [{ name: 'offerId', type: 'string' }],
    },
    {
      name: 'createLoanOffer',
      accounts: [
        { name: 'borrower', isMut: true, isSigner: true },
        { name: 'collateralMintAsset', isMut: false, isSigner: false },
        { name: 'lendMintAsset', isMut: false, isSigner: false },
        { name: 'borrowerAtaAsset', isMut: true, isSigner: false },
        { name: 'lendAsset', isMut: false, isSigner: false },
        { name: 'collateralAsset', isMut: false, isSigner: false },
        { name: 'loanOffer', isMut: true, isSigner: false },
        { name: 'lendOffer', isMut: true, isSigner: false },
        { name: 'vaultAuthority', isMut: true, isSigner: false },
        { name: 'vault', isMut: true, isSigner: false },
        { name: 'lender', isMut: false, isSigner: false },
        { name: 'lendPriceFeedAccount', isMut: false, isSigner: false },
        { name: 'collateralPriceFeedAccount', isMut: false, isSigner: false },
        { name: 'settingAccount', isMut: false, isSigner: false },
        { name: 'associatedTokenProgram', isMut: false, isSigner: false },
        { name: 'tokenProgram', isMut: false, isSigner: false },
        { name: 'systemProgram', isMut: false, isSigner: false },
      ],
      args: [
        { name: 'offerId', type: 'string' },
        { name: 'lendOfferId', type: 'string' },
        { name: 'tierId', type: 'string' },
        { name: 'collateralAmount', type: 'u64' },
        { name: 'interest', type: 'f64' },
      ],
    },
    {
      name: 'createLoanOfferNative',
      accounts: [
        { name: 'borrower', isMut: true, isSigner: true },
        { name: 'collateralMintAsset', isMut: false, isSigner: false },
        { name: 'lendMintAsset', isMut: false, isSigner: false },
        { name: 'lendAsset', isMut: false, isSigner: false },
        { name: 'collateralAsset', isMut: false, isSigner: false },
        { name: 'loanOffer', isMut: true, isSigner: false },
        { name: 'lender', isMut: false, isSigner: false },
        { name: 'lendOffer', isMut: true, isSigner: false },
        { name: 'lendPriceFeedAccount', isMut: false, isSigner: false },
        { name: 'collateralPriceFeedAccount', isMut: false, isSigner: false },
        { name: 'settingAccount', isMut: false, isSigner: false },
        { name: 'tokenProgram', isMut: false, isSigner: false },
        { name: 'systemProgram', isMut: false, isSigner: false },
      ],
      args: [
        { name: 'offerId', type: 'string' },
        { name: 'lendOfferId', type: 'string' },
        { name: 'tierId', type: 'string' },
        { name: 'collateralAmount', type: 'u64' },
        { name: 'interest', type: 'f64' },
      ],
    },
    {
      name: 'systemUpdateLoanOffer',
      accounts: [
        { name: 'borrower', isMut: false, isSigner: false },
        { name: 'borrowerAtaAsset', isMut: true, isSigner: false },
        { name: 'mintAsset', isMut: false, isSigner: false },
        { name: 'loanOffer', isMut: true, isSigner: false },
        { name: 'system', isMut: true, isSigner: true },
        { name: 'systemAta', isMut: true, isSigner: false },
        { name: 'tokenProgram', isMut: false, isSigner: false },
      ],
      args: [
        { name: 'offerId', type: 'string' },
        { name: 'tierId', type: 'string' },
        { name: 'borrowAmount', type: 'u64' },
      ],
    },
    {
      name: 'depositCollateralLoanOfferNative',
      accounts: [
        { name: 'borrower', isMut: true, isSigner: true },
        { name: 'loanOffer', isMut: true, isSigner: false },
        { name: 'systemProgram', isMut: false, isSigner: false },
      ],
      args: [
        { name: 'offerId', type: 'string' },
        { name: 'tierId', type: 'string' },
        { name: 'amount', type: 'u64' },
      ],
    },
    {
      name: 'depositCollateralLoanOffer',
      accounts: [
        { name: 'borrower', isMut: true, isSigner: true },
        { name: 'collateralMintAsset', isMut: false, isSigner: false },
        { name: 'borrowerAtaAsset', isMut: true, isSigner: false },
        { name: 'loanOffer', isMut: true, isSigner: false },
        { name: 'vaultAuthority', isMut: false, isSigner: false },
        { name: 'vault', isMut: true, isSigner: false },
        { name: 'tokenProgram', isMut: false, isSigner: false },
      ],
      args: [
        { name: 'offerId', type: 'string' },
        { name: 'tierId', type: 'string' },
        { name: 'amount', type: 'u64' },
      ],
    },
    {
      name: 'repayLoanOfferNative',
      accounts: [
        { name: 'borrower', isMut: true, isSigner: true },
        { name: 'lendMintAsset', isMut: false, isSigner: false },
        { name: 'borrowerAtaLendAsset', isMut: true, isSigner: false },
        { name: 'loanOffer', isMut: true, isSigner: false },
        { name: 'hotWalletAtaLendAsset', isMut: true, isSigner: false },
        { name: 'tokenProgram', isMut: false, isSigner: false },
        { name: 'systemProgram', isMut: false, isSigner: false },
      ],
      args: [{ name: 'loanOfferId', type: 'string' }],
    },
    {
      name: 'repayLoanOffer',
      accounts: [
        { name: 'borrower', isMut: true, isSigner: true },
        { name: 'collateralMintAsset', isMut: false, isSigner: false },
        { name: 'lendMintAsset', isMut: false, isSigner: false },
        { name: 'borrowerAtaLendAsset', isMut: true, isSigner: false },
        { name: 'borrowerAtaCollateralAsset', isMut: true, isSigner: false },
        { name: 'loanOffer', isMut: true, isSigner: false },
        { name: 'vaultAuthority', isMut: true, isSigner: false },
        { name: 'vault', isMut: true, isSigner: false },
        { name: 'hotWalletAtaLendAsset', isMut: true, isSigner: false },
        { name: 'tokenProgram', isMut: false, isSigner: false },
      ],
      args: [{ name: 'loanOfferId', type: 'string' }],
    },
    {
      name: 'withdrawCollateralLoanOfferNative',
      accounts: [
        { name: 'borrower', isMut: true, isSigner: true },
        { name: 'collateralMintAsset', isMut: false, isSigner: false },
        { name: 'lendMintAsset', isMut: false, isSigner: false },
        { name: 'lendAsset', isMut: false, isSigner: false },
        { name: 'collateralAsset', isMut: false, isSigner: false },
        { name: 'loanOffer', isMut: true, isSigner: false },
        { name: 'lendPriceFeedAccount', isMut: false, isSigner: false },
        { name: 'collateralPriceFeedAccount', isMut: false, isSigner: false },
      ],
      args: [
        { name: 'loanOfferId', type: 'string' },
        { name: 'withdrawAmount', type: 'u64' },
      ],
    },
    {
      name: 'withdrawCollateralLoanOffer',
      accounts: [
        { name: 'borrower', isMut: true, isSigner: true },
        { name: 'collateralMintAsset', isMut: false, isSigner: false },
        { name: 'lendMintAsset', isMut: false, isSigner: false },
        { name: 'lendAsset', isMut: false, isSigner: false },
        { name: 'collateralAsset', isMut: false, isSigner: false },
        { name: 'borrowerAtaCollateralAsset', isMut: true, isSigner: false },
        { name: 'loanOffer', isMut: true, isSigner: false },
        { name: 'vaultAuthority', isMut: true, isSigner: false },
        { name: 'vault', isMut: true, isSigner: false },
        { name: 'lendPriceFeedAccount', isMut: false, isSigner: false },
        { name: 'collateralPriceFeedAccount', isMut: false, isSigner: false },
        { name: 'tokenProgram', isMut: false, isSigner: false },
      ],
      args: [
        { name: 'loanOfferId', type: 'string' },
        { name: 'withdrawAmount', type: 'u64' },
      ],
    },
    {
      name: 'startLiquidateLoanOfferNativeHealth',
      accounts: [
        { name: 'system', isMut: true, isSigner: true },
        { name: 'borrower', isMut: false, isSigner: false },
        { name: 'loanOffer', isMut: true, isSigner: false },
        { name: 'hotWallet', isMut: true, isSigner: false },
        { name: 'collateralMintAsset', isMut: false, isSigner: false },
        { name: 'lendMintAsset', isMut: false, isSigner: false },
        { name: 'lendAsset', isMut: false, isSigner: false },
        { name: 'collateralAsset', isMut: false, isSigner: false },
        { name: 'lendPriceFeedAccount', isMut: false, isSigner: false },
        { name: 'collateralPriceFeedAccount', isMut: false, isSigner: false },
      ],
      args: [{ name: 'offerId', type: 'string' }],
    },
    {
      name: 'startLiquidateLoanOfferHealth',
      accounts: [
        { name: 'system', isMut: true, isSigner: true },
        { name: 'borrower', isMut: false, isSigner: false },
        { name: 'loanOffer', isMut: true, isSigner: false },
        { name: 'collateralMintAsset', isMut: false, isSigner: false },
        { name: 'lendMintAsset', isMut: false, isSigner: false },
        { name: 'lendAsset', isMut: false, isSigner: false },
        { name: 'collateralAsset', isMut: false, isSigner: false },
        { name: 'lendPriceFeedAccount', isMut: false, isSigner: false },
        { name: 'collateralPriceFeedAccount', isMut: false, isSigner: false },
        { name: 'hotWalletAtaCollateralAsset', isMut: true, isSigner: false },
        { name: 'vaultAuthority', isMut: true, isSigner: false },
        { name: 'vault', isMut: true, isSigner: false },
        { name: 'tokenProgram', isMut: false, isSigner: false },
      ],
      args: [{ name: 'offerId', type: 'string' }],
    },
    {
      name: 'startLiquidateLoanOfferNativeExpired',
      accounts: [
        { name: 'system', isMut: true, isSigner: true },
        { name: 'borrower', isMut: false, isSigner: false },
        { name: 'loanOffer', isMut: true, isSigner: false },
        { name: 'hotWallet', isMut: true, isSigner: false },
      ],
      args: [{ name: 'offerId', type: 'string' }],
    },
    {
      name: 'startLiquidateLoanOfferExpired',
      accounts: [
        { name: 'system', isMut: true, isSigner: true },
        { name: 'borrower', isMut: false, isSigner: false },
        { name: 'collateralMintAsset', isMut: false, isSigner: false },
        { name: 'loanOffer', isMut: true, isSigner: false },
        { name: 'hotWalletAtaCollateralAsset', isMut: true, isSigner: false },
        { name: 'vaultAuthority', isMut: true, isSigner: false },
        { name: 'vault', isMut: true, isSigner: false },
        { name: 'tokenProgram', isMut: false, isSigner: false },
      ],
      args: [{ name: 'offerId', type: 'string' }],
    },
    {
      name: 'finishLiquidateContract',
      accounts: [
        { name: 'system', isMut: true, isSigner: true },
        { name: 'systemAta', isMut: true, isSigner: false },
        { name: 'mintAsset', isMut: false, isSigner: false },
        { name: 'borrower', isMut: false, isSigner: false },
        { name: 'borrowerAtaAsset', isMut: true, isSigner: false },
        { name: 'loanOffer', isMut: true, isSigner: false },
        { name: 'tokenProgram', isMut: false, isSigner: false },
      ],
      args: [
        { name: 'loanOfferId', type: 'string' },
        { name: 'collateralSwappedAmount', type: 'u64' },
        { name: 'liquidatedPrice', type: 'u64' },
        { name: 'liquidatedTx', type: 'string' },
      ],
    },
    {
      name: 'systemFinishLoanOffer',
      accounts: [
        { name: 'system', isMut: true, isSigner: true },
        { name: 'systemAta', isMut: true, isSigner: false },
        { name: 'mintAsset', isMut: false, isSigner: false },
        { name: 'lender', isMut: false, isSigner: false },
        { name: 'lenderAtaAsset', isMut: true, isSigner: false },
        { name: 'borrower', isMut: true, isSigner: false },
        { name: 'loanOffer', isMut: true, isSigner: false },
        { name: 'tokenProgram', isMut: false, isSigner: false },
        { name: 'systemProgram', isMut: false, isSigner: false },
      ],
      args: [
        { name: 'loanOfferId', type: 'string' },
        { name: 'loanAmount', type: 'u64' },
        { name: 'interestAmount', type: 'u64' },
      ],
    },
    {
      name: 'systemRevertStatus',
      accounts: [
        { name: 'system', isMut: true, isSigner: true },
        { name: 'borrower', isMut: false, isSigner: false },
        { name: 'loanOffer', isMut: true, isSigner: false },
      ],
      args: [{ name: 'offerId', type: 'string' }],
    },
    {
      name: 'closeLendOffer',
      accounts: [
        { name: 'signer', isMut: true, isSigner: true },
        { name: 'lender', isMut: false, isSigner: false },
        { name: 'lendOffer', isMut: true, isSigner: false },
        { name: 'systemProgram', isMut: false, isSigner: false },
      ],
      args: [{ name: 'offerId', type: 'string' }],
    },
  ],
  accounts: [
    {
      name: 'Asset',
      type: {
        kind: 'struct',
        fields: [
          { name: 'tokenMint', type: 'publicKey' },
          { name: 'maxPriceAgeSeconds', type: 'u64' },
          { name: 'decimals', type: 'u8' },
          { name: 'isCollateral', type: 'bool' },
          { name: 'isLend', type: 'bool' },
          { name: 'priceFeedId', type: 'string' },
          { name: 'priceFeedAccount', type: 'publicKey' },
          { name: 'bump', type: 'u8' },
          { name: 'name', type: 'string' },
        ],
      },
    },
    {
      name: 'LendOfferAccount',
      type: {
        kind: 'struct',
        fields: [
          { name: 'interest', type: 'f64' },
          { name: 'lenderFeePercent', type: 'f64' },
          { name: 'duration', type: 'u64' },
          { name: 'offerId', type: 'string' },
          { name: 'lender', type: 'publicKey' },
          { name: 'lendMintToken', type: 'publicKey' },
          { name: 'amount', type: 'u64' },
          { name: 'bump', type: 'u8' },
          { name: 'status', type: { defined: 'LendOfferStatus' } },
        ],
      },
    },
    {
      name: 'LoanOfferAccount',
      type: {
        kind: 'struct',
        fields: [
          { name: 'tierId', type: 'string' },
          { name: 'lendOfferId', type: 'string' },
          { name: 'interest', type: 'f64' },
          { name: 'borrowAmount', type: 'u64' },
          { name: 'lenderFeePercent', type: 'f64' },
          { name: 'duration', type: 'u64' },
          { name: 'lendMintToken', type: 'publicKey' },
          { name: 'lender', type: 'publicKey' },
          { name: 'offerId', type: 'string' },
          { name: 'borrower', type: 'publicKey' },
          { name: 'collateralMintToken', type: 'publicKey' },
          { name: 'collateralAmount', type: 'u64' },
          { name: 'requestWithdrawAmount', type: { option: 'u64' } },
          { name: 'status', type: { defined: 'LoanOfferStatus' } },
          { name: 'borrowerFeePercent', type: 'f64' },
          { name: 'startedAt', type: 'i64' },
          { name: 'liquidatingAt', type: { option: 'i64' } },
          { name: 'liquidatingPrice', type: { option: 'f64' } },
          { name: 'liquidatedTx', type: { option: 'string' } },
          { name: 'liquidatedPrice', type: { option: 'u64' } },
          { name: 'bump', type: 'u8' },
        ],
      },
    },
    {
      name: 'SettingAccount',
      type: {
        kind: 'struct',
        fields: [
          { name: 'amount', type: 'u64' },
          { name: 'duration', type: 'u64' },
          { name: 'owner', type: 'publicKey' },
          { name: 'receiver', type: 'publicKey' },
          { name: 'lendMintAsset', type: 'publicKey' },
          { name: 'collateralMintAsset', type: 'publicKey' },
          { name: 'tierId', type: 'string' },
          { name: 'lenderFeePercent', type: 'f64' },
          { name: 'borrowerFeePercent', type: 'f64' },
          { name: 'lendPriceFeed', type: 'publicKey' },
          { name: 'collateralPriceFeed', type: 'publicKey' },
          { name: 'bump', type: 'u8' },
        ],
      },
    },
    {
      name: 'VaultAuthority',
      type: {
        kind: 'struct',
        fields: [
          { name: 'initializer', type: 'publicKey' },
          { name: 'bump', type: 'u8' },
        ],
      },
    },
  ],
  types: [
    {
      name: 'LendOfferStatus',
      type: {
        kind: 'enum',
        variants: [
          { name: 'Created' },
          { name: 'Canceling' },
          { name: 'Canceled' },
          { name: 'Loaned' },
        ],
      },
    },
    {
      name: 'LoanOfferStatus',
      type: {
        kind: 'enum',
        variants: [
          { name: 'Matched' },
          { name: 'FundTransferred' },
          { name: 'Repay' },
          { name: 'BorrowerPaid' },
          { name: 'Liquidating' },
          { name: 'Liquidated' },
          { name: 'Finished' },
        ],
      },
    },
    {
      name: 'LendOfferError',
      type: {
        kind: 'enum',
        variants: [
          { name: 'InvalidLendAmount' },
          { name: 'NotEnoughAmount' },
          { name: 'InvalidMintAsset' },
          { name: 'InterestGreaterThanZero' },
          { name: 'InvalidLender' },
          { name: 'InvalidOfferStatus' },
          { name: 'InvalidOfferId' },
          { name: 'InvalidReceiver' },
          { name: 'InterestOverLimit' },
          { name: 'InvalidSigner' },
        ],
      },
    },
    {
      name: 'LoanOfferError',
      type: {
        kind: 'enum',
        variants: [
          { name: 'InvalidReceiver' },
          { name: 'CanNotDepositCollateralToContractThatNotAvailable' },
          { name: 'CanNotTakeALoanBecauseHealthRatioIsNotValid' },
          { name: 'InvalidPriceFeedAccountForCollateralAsset' },
          { name: 'InvalidPriceFeedAccountForLendAsset' },
          { name: 'NotEnoughAmount' },
          { name: 'InvalidCollateralMintAsset' },
          { name: 'InvalidLendMintAsset' },
          { name: 'InvalidOfferStatus' },
          { name: 'LendOfferIsNotAvailable' },
          { name: 'HealthRatioLimit' },
          { name: 'LoanOfferExpired' },
          { name: 'LoanOfferNotExpired' },
          { name: 'InvalidHotWallet' },
          { name: 'InvalidSystem' },
          { name: 'InvalidBorrower' },
          { name: 'InvalidLoanOffer' },
          { name: 'InvalidBorrowAmount' },
          { name: 'NotAvailableToWithdraw' },
          { name: 'HealthRatioInvalid' },
          { name: 'CanNotCreateLoanCauseLendInterestUpdated' },
          { name: 'InvalidPriceFeedAccount' },
          { name: 'InvalidAssetAccount' },
          { name: 'NotEnoughCollateral' },
          { name: 'InvalidInitializerVaultAuthority' },
        ],
      },
    },
    {
      name: 'RepayOfferError',
      type: {
        kind: 'enum',
        variants: [
          { name: 'InvalidMintAsset' },
          { name: 'NotEnoughAmount' },
          { name: 'LoanOfferIsNotAvailable' },
          { name: 'InvalidLendAmount' },
          { name: 'InvalidBorrower' },
          { name: 'InvalidCollateralAmount' },
          { name: 'InvalidOfferStatus' },
          { name: 'InvalidLender' },
          { name: 'TimeUnmetException' },
        ],
      },
    },
    {
      name: 'LiquidateOfferError',
      type: {
        kind: 'enum',
        variants: [
          { name: 'InvalidLender' },
          { name: 'InvalidBorrower' },
          { name: 'InvalidOfferStatus' },
          { name: 'InvalidLendAmount' },
          { name: 'NotEnoughAmount' },
          { name: 'InvalidMintAsset' },
          { name: 'InvalidSystem' },
        ],
      },
    },
  ],
  events: [
    {
      name: 'InitSettingAccountEvent',
      fields: [
        { name: 'amount', type: 'u64', index: false },
        { name: 'duration', type: 'u64', index: false },
        { name: 'owner', type: 'publicKey', index: false },
        { name: 'receiver', type: 'publicKey', index: false },
        { name: 'tierId', type: 'string', index: false },
        { name: 'lenderFeePercent', type: 'f64', index: false },
        { name: 'borrowerFeePercent', type: 'f64', index: false },
      ],
    },
    {
      name: 'EditSettingAccountEvent',
      fields: [
        { name: 'receiver', type: 'publicKey', index: false },
        { name: 'tierId', type: 'string', index: false },
        { name: 'amount', type: 'u64', index: false },
        { name: 'duration', type: 'u64', index: false },
        { name: 'lenderFeePercent', type: 'f64', index: false },
      ],
    },
    {
      name: 'CloseSettingAccountEvent',
      fields: [{ name: 'tierId', type: 'string', index: false }],
    },
    {
      name: 'InitAssetEvent',
      fields: [
        { name: 'tokenMint', type: 'publicKey', index: false },
        { name: 'maxPriceAgeSeconds', type: 'u64', index: false },
        { name: 'decimals', type: 'u8', index: false },
        { name: 'isCollateral', type: 'bool', index: false },
        { name: 'isLend', type: 'bool', index: false },
        { name: 'priceFeedId', type: 'string', index: false },
        { name: 'priceFeedAccount', type: 'publicKey', index: false },
        { name: 'bump', type: 'u8', index: false },
        { name: 'name', type: 'string', index: false },
      ],
    },
    {
      name: 'EditAssetEvent',
      fields: [
        { name: 'tokenMint', type: 'publicKey', index: false },
        { name: 'maxPriceAgeSeconds', type: 'u64', index: false },
        { name: 'decimals', type: 'u8', index: false },
        { name: 'isCollateral', type: 'bool', index: false },
        { name: 'isLend', type: 'bool', index: false },
        { name: 'priceFeedId', type: 'string', index: false },
        { name: 'priceFeedAccount', type: 'publicKey', index: false },
        { name: 'bump', type: 'u8', index: false },
        { name: 'name', type: 'string', index: false },
      ],
    },
    {
      name: 'CreateLendOfferEvent',
      fields: [
        { name: 'lender', type: 'publicKey', index: false },
        { name: 'interest', type: 'f64', index: false },
        { name: 'lenderFeePercent', type: 'f64', index: false },
        { name: 'duration', type: 'u64', index: false },
        { name: 'amount', type: 'u64', index: false },
        { name: 'offerId', type: 'string', index: false },
        { name: 'tierId', type: 'string', index: false },
      ],
    },
    {
      name: 'EditLendOfferEvent',
      fields: [
        { name: 'lender', type: 'publicKey', index: false },
        { name: 'interest', type: 'f64', index: false },
        { name: 'lenderFeePercent', type: 'f64', index: false },
        { name: 'duration', type: 'u64', index: false },
        { name: 'amount', type: 'u64', index: false },
        { name: 'offerId', type: 'string', index: false },
      ],
    },
    {
      name: 'LendOfferCancelRequestEvent',
      fields: [
        { name: 'lender', type: 'publicKey', index: false },
        { name: 'interest', type: 'f64', index: false },
        { name: 'lenderFeePercent', type: 'f64', index: false },
        { name: 'duration', type: 'u64', index: false },
        { name: 'amount', type: 'u64', index: false },
        { name: 'offerId', type: 'string', index: false },
      ],
    },
    {
      name: 'LendOfferCanceledEvent',
      fields: [
        { name: 'lender', type: 'publicKey', index: false },
        { name: 'interest', type: 'f64', index: false },
        { name: 'lenderFeePercent', type: 'f64', index: false },
        { name: 'duration', type: 'u64', index: false },
        { name: 'amount', type: 'u64', index: false },
        { name: 'offerId', type: 'string', index: false },
      ],
    },
    {
      name: 'LoanOfferCreateRequestEvent',
      fields: [
        { name: 'tierId', type: 'string', index: false },
        { name: 'lendOfferId', type: 'string', index: false },
        { name: 'interest', type: 'f64', index: false },
        { name: 'borrowAmount', type: 'u64', index: false },
        { name: 'lenderFeePercent', type: 'f64', index: false },
        { name: 'duration', type: 'u64', index: false },
        { name: 'lendMintToken', type: 'publicKey', index: false },
        { name: 'lender', type: 'publicKey', index: false },
        { name: 'offerId', type: 'string', index: false },
        { name: 'borrower', type: 'publicKey', index: false },
        { name: 'collateralMintToken', type: 'publicKey', index: false },
        { name: 'collateralAmount', type: 'u64', index: false },
        { name: 'status', type: { defined: 'LoanOfferStatus' }, index: false },
        { name: 'borrowerFeePercent', type: 'f64', index: false },
        { name: 'startedAt', type: 'i64', index: false },
      ],
    },
    {
      name: 'LoanOfferUpdateEvent',
      fields: [
        { name: 'tierId', type: 'string', index: false },
        { name: 'lendOfferId', type: 'string', index: false },
        { name: 'interest', type: 'f64', index: false },
        { name: 'borrowAmount', type: 'u64', index: false },
        { name: 'lenderFeePercent', type: 'f64', index: false },
        { name: 'duration', type: 'u64', index: false },
        { name: 'lendMintToken', type: 'publicKey', index: false },
        { name: 'lender', type: 'publicKey', index: false },
        { name: 'offerId', type: 'string', index: false },
        { name: 'borrower', type: 'publicKey', index: false },
        { name: 'collateralMintToken', type: 'publicKey', index: false },
        { name: 'collateralAmount', type: 'u64', index: false },
        { name: 'status', type: { defined: 'LoanOfferStatus' }, index: false },
        { name: 'borrowerFeePercent', type: 'f64', index: false },
        { name: 'startedAt', type: 'i64', index: false },
      ],
    },
    {
      name: 'WithdrawCollateralEvent',
      fields: [
        { name: 'borrower', type: 'publicKey', index: false },
        { name: 'withdrawAmount', type: 'u64', index: false },
        { name: 'loanOfferId', type: 'string', index: false },
        { name: 'collateralAmount', type: 'u64', index: false },
      ],
    },
    {
      name: 'UnhealthyRatioDetectedEvent',
      fields: [
        { name: 'borrower', type: 'publicKey', index: false },
        { name: 'withdrawAmount', type: 'u64', index: false },
        { name: 'loanOfferId', type: 'string', index: false },
        { name: 'collateralAmount', type: 'u64', index: false },
      ],
    },
    {
      name: 'LoanOfferExpiredEvent',
      fields: [
        { name: 'borrower', type: 'publicKey', index: false },
        { name: 'withdrawAmount', type: 'u64', index: false },
        { name: 'loanOfferId', type: 'string', index: false },
        { name: 'collateralAmount', type: 'u64', index: false },
      ],
    },
    {
      name: 'DepositCollateralLoanOfferEvent',
      fields: [
        { name: 'tierId', type: 'string', index: false },
        { name: 'lendOfferId', type: 'string', index: false },
        { name: 'interest', type: 'f64', index: false },
        { name: 'borrowAmount', type: 'u64', index: false },
        { name: 'lenderFeePercent', type: 'f64', index: false },
        { name: 'duration', type: 'u64', index: false },
        { name: 'lendMintToken', type: 'publicKey', index: false },
        { name: 'lender', type: 'publicKey', index: false },
        { name: 'offerId', type: 'string', index: false },
        { name: 'borrower', type: 'publicKey', index: false },
        { name: 'collateralMintToken', type: 'publicKey', index: false },
        { name: 'collateralAmount', type: 'u64', index: false },
        { name: 'status', type: { defined: 'LoanOfferStatus' }, index: false },
        { name: 'borrowerFeePercent', type: 'f64', index: false },
        { name: 'startedAt', type: 'i64', index: false },
      ],
    },
    {
      name: 'RepayLoanOfferEvent',
      fields: [
        { name: 'borrower', type: 'publicKey', index: false },
        { name: 'loanOfferId', type: 'string', index: false },
        { name: 'repayAmount', type: 'u64', index: false },
        { name: 'borrowerFeePercent', type: 'f64', index: false },
        { name: 'status', type: { defined: 'LoanOfferStatus' }, index: false },
      ],
    },
    {
      name: 'LiquidatingCollateralEvent',
      fields: [
        { name: 'offerId', type: 'string', index: false },
        { name: 'liquidatingPrice', type: { option: 'f64' }, index: false },
        { name: 'liquidatingAt', type: { option: 'i64' }, index: false },
      ],
    },
    {
      name: 'LiquidatedCollateralEvent',
      fields: [
        { name: 'loanOfferId', type: 'string', index: false },
        { name: 'liquidatedPrice', type: 'u64', index: false },
        { name: 'liquidatedTx', type: 'string', index: false },
        { name: 'system', type: 'publicKey', index: false },
        { name: 'lender', type: 'publicKey', index: false },
        { name: 'borrower', type: 'publicKey', index: false },
        { name: 'remainingFundToBorrower', type: 'u64', index: false },
        { name: 'collateralSwappedAmount', type: 'u64', index: false },
        { name: 'status', type: { defined: 'LoanOfferStatus' }, index: false },
      ],
    },
    {
      name: 'SystemRepayLoanOfferEvent',
      fields: [
        { name: 'lender', type: 'publicKey', index: false },
        { name: 'borrower', type: 'publicKey', index: false },
        { name: 'interest', type: 'f64', index: false },
        { name: 'loanAmount', type: 'u64', index: false },
        { name: 'collateralAmount', type: 'u64', index: false },
        { name: 'loanOfferId', type: 'string', index: false },
        { name: 'tierId', type: 'string', index: false },
        { name: 'status', type: { defined: 'LoanOfferStatus' }, index: false },
      ],
    },
    {
      name: 'SystemFinishLoanOfferEvent',
      fields: [
        { name: 'system', type: 'publicKey', index: false },
        { name: 'lender', type: 'publicKey', index: false },
        { name: 'borrower', type: 'publicKey', index: false },
        { name: 'interest', type: 'f64', index: false },
        { name: 'loanAmount', type: 'u64', index: false },
        { name: 'loanOfferId', type: 'string', index: false },
        { name: 'tierId', type: 'string', index: false },
        { name: 'status', type: { defined: 'LoanOfferStatus' }, index: false },
      ],
    },
    {
      name: 'SystemRevertEvent',
      fields: [
        { name: 'offerId', type: 'string', index: false },
        { name: 'status', type: { defined: 'LoanOfferStatus' }, index: false },
      ],
    },
  ],
  errors: [
    { code: 6000, name: 'InvalidTierId', msg: 'Invalid tier id' },
    { code: 6001, name: 'InvalidOwner', msg: 'Invalid owner account' },
  ],
};
