export const ensofiIdl = {
  version: '1.0.0',
  name: 'enso_lending',
  instructions: [
    {
      name: 'initSettingAccount',
      accounts: [
        { name: 'owner', isMut: true, isSigner: true },
        { name: 'receiver', isMut: false, isSigner: false },
        { name: 'settingAccount', isMut: true, isSigner: false },
        { name: 'systemProgram', isMut: false, isSigner: false },
      ],
      args: [
        { name: 'tierId', type: 'string' },
        { name: 'amount', type: 'u64' },
        { name: 'duration', type: 'u64' },
        { name: 'lenderFeePercent', type: 'f64' },
        { name: 'borrowerFeePercent', type: 'f64' },
        { name: 'liquidationFeePercent', type: 'f64' },
      ],
    },
    {
      name: 'editSettingAccount',
      accounts: [
        { name: 'owner', isMut: true, isSigner: true },
        { name: 'receiver', isMut: false, isSigner: false },
        { name: 'settingAccount', isMut: true, isSigner: false },
        { name: 'systemProgram', isMut: false, isSigner: false },
      ],
      args: [
        { name: 'tierId', type: 'string' },
        { name: 'amount', type: { option: 'u64' } },
        { name: 'duration', type: { option: 'u64' } },
        { name: 'lenderFeePercent', type: { option: 'f64' } },
        { name: 'borrowerFeePercent', type: { option: 'f64' } },
        { name: 'liquidationFeePercent', type: { option: 'f64' } },
      ],
    },
    {
      name: 'closeSettingAccount',
      accounts: [
        { name: 'owner', isMut: true, isSigner: true },
        { name: 'settingAccount', isMut: true, isSigner: false },
        { name: 'systemProgram', isMut: false, isSigner: false },
      ],
      args: [{ name: 'tierId', type: 'string' }],
    },
    {
      name: 'initAsset',
      accounts: [
        { name: 'owner', isMut: true, isSigner: true },
        { name: 'tokenMint', isMut: false, isSigner: false },
        { name: 'asset', isMut: true, isSigner: false },
        { name: 'priceFeedAccount', isMut: false, isSigner: false },
        { name: 'systemProgram', isMut: false, isSigner: false },
      ],
      args: [
        { name: 'name', type: 'string' },
        { name: 'isLend', type: 'bool' },
        { name: 'isCollateral', type: 'bool' },
        { name: 'priceFeedId', type: 'string' },
        { name: 'maxPriceAgeSeconds', type: 'u64' },
        { name: 'tokenAddress', type: { option: { array: ['u8', 32] } } },
        { name: 'chainId', type: 'u16' },
      ],
    },
    {
      name: 'editAsset',
      accounts: [
        { name: 'owner', isMut: true, isSigner: true },
        { name: 'tokenMint', isMut: false, isSigner: false },
        { name: 'asset', isMut: true, isSigner: false },
        {
          name: 'priceFeedAccount',
          isMut: false,
          isSigner: false,
          isOptional: true,
        },
      ],
      args: [
        { name: 'name', type: { option: 'string' } },
        { name: 'isLend', type: { option: 'bool' } },
        { name: 'isCollateral', type: { option: 'bool' } },
        { name: 'priceFeedId', type: { option: 'string' } },
        { name: 'maxPriceAgeSeconds', type: { option: 'u64' } },
        { name: 'tokenAddress', type: { option: { array: ['u8', 32] } } },
      ],
    },
    {
      name: 'closeAsset',
      accounts: [
        { name: 'owner', isMut: true, isSigner: true },
        { name: 'tokenMint', isMut: false, isSigner: false },
        { name: 'asset', isMut: true, isSigner: false },
      ],
      args: [],
    },
    {
      name: 'initVaultAuthority',
      accounts: [
        { name: 'borrower', isMut: true, isSigner: true },
        { name: 'vaultAuthority', isMut: true, isSigner: false },
        { name: 'mint', isMut: false, isSigner: false },
        { name: 'vault', isMut: true, isSigner: false },
        { name: 'associatedTokenProgram', isMut: false, isSigner: false },
        { name: 'tokenProgram', isMut: false, isSigner: false },
        { name: 'systemProgram', isMut: false, isSigner: false },
      ],
      args: [],
    },
    {
      name: 'createLendOffer',
      accounts: [
        { name: 'lender', isMut: true, isSigner: true },
        { name: 'lendAsset', isMut: false, isSigner: false },
        { name: 'mintAsset', isMut: false, isSigner: false },
        { name: 'lenderAtaAsset', isMut: true, isSigner: false },
        { name: 'settingAccount', isMut: false, isSigner: false },
        { name: 'lendOffer', isMut: true, isSigner: false },
        { name: 'hotWalletAta', isMut: true, isSigner: false },
        { name: 'tokenProgram', isMut: false, isSigner: false },
        { name: 'systemProgram', isMut: false, isSigner: false },
      ],
      args: [
        { name: 'offerId', type: 'string' },
        { name: 'tierId', type: 'string' },
        { name: 'interest', type: 'u16' },
      ],
    },
    {
      name: 'editLendOffer',
      accounts: [
        { name: 'lender', isMut: true, isSigner: true },
        { name: 'lendOffer', isMut: true, isSigner: false },
      ],
      args: [
        { name: 'offerId', type: 'string' },
        { name: 'interest', type: 'u16' },
      ],
    },
    {
      name: 'systemCancelLendOffer',
      accounts: [
        { name: 'lender', isMut: false, isSigner: false },
        { name: 'lenderAtaAsset', isMut: true, isSigner: false },
        { name: 'mintAsset', isMut: false, isSigner: false },
        { name: 'lendOffer', isMut: true, isSigner: false },
        { name: 'system', isMut: true, isSigner: true },
        { name: 'systemAta', isMut: true, isSigner: false },
        { name: 'tokenProgram', isMut: false, isSigner: false },
      ],
      args: [
        { name: 'offerId', type: 'string' },
        { name: 'tierId', type: 'string' },
        { name: 'waitingInterest', type: 'u64' },
      ],
    },
    {
      name: 'cancelLendOffer',
      accounts: [
        { name: 'lender', isMut: true, isSigner: true },
        { name: 'lendOffer', isMut: true, isSigner: false },
      ],
      args: [{ name: 'offerId', type: 'string' }],
    },
    {
      name: 'createLoanOffer',
      accounts: [
        { name: 'borrower', isMut: true, isSigner: true },
        { name: 'collateralMintAsset', isMut: false, isSigner: false },
        { name: 'lendMintAsset', isMut: false, isSigner: false },
        { name: 'borrowerAtaAsset', isMut: true, isSigner: false },
        { name: 'lendAsset', isMut: false, isSigner: false },
        { name: 'collateralAsset', isMut: false, isSigner: false },
        { name: 'loanOffer', isMut: true, isSigner: false },
        { name: 'lendOffer', isMut: true, isSigner: false },
        { name: 'vaultAuthority', isMut: true, isSigner: false },
        { name: 'vault', isMut: true, isSigner: false },
        { name: 'lender', isMut: false, isSigner: false },
        { name: 'lendPriceFeedAccount', isMut: false, isSigner: false },
        { name: 'collateralPriceFeedAccount', isMut: false, isSigner: false },
        { name: 'settingAccount', isMut: false, isSigner: false },
        { name: 'associatedTokenProgram', isMut: false, isSigner: false },
        { name: 'tokenProgram', isMut: false, isSigner: false },
        { name: 'systemProgram', isMut: false, isSigner: false },
      ],
      args: [
        { name: 'offerId', type: 'string' },
        { name: 'lendOfferId', type: 'string' },
        { name: 'tierId', type: 'string' },
        { name: 'collateralAmount', type: 'u64' },
        { name: 'interest', type: 'u16' },
      ],
    },
    {
      name: 'createLoanOfferNative',
      accounts: [
        { name: 'borrower', isMut: true, isSigner: true },
        { name: 'collateralMintAsset', isMut: false, isSigner: false },
        { name: 'lendMintAsset', isMut: false, isSigner: false },
        { name: 'lendAsset', isMut: false, isSigner: false },
        { name: 'collateralAsset', isMut: false, isSigner: false },
        { name: 'loanOffer', isMut: true, isSigner: false },
        { name: 'lender', isMut: false, isSigner: false },
        { name: 'lendOffer', isMut: true, isSigner: false },
        { name: 'lendPriceFeedAccount', isMut: false, isSigner: false },
        { name: 'collateralPriceFeedAccount', isMut: false, isSigner: false },
        { name: 'settingAccount', isMut: false, isSigner: false },
        { name: 'tokenProgram', isMut: false, isSigner: false },
        { name: 'systemProgram', isMut: false, isSigner: false },
      ],
      args: [
        { name: 'offerId', type: 'string' },
        { name: 'lendOfferId', type: 'string' },
        { name: 'tierId', type: 'string' },
        { name: 'collateralAmount', type: 'u64' },
        { name: 'interest', type: 'u16' },
      ],
    },
    {
      name: 'systemUpdateLoanOffer',
      accounts: [
        { name: 'borrower', isMut: false, isSigner: false },
        { name: 'borrowerAtaAsset', isMut: true, isSigner: false },
        { name: 'mintAsset', isMut: false, isSigner: false },
        { name: 'loanOffer', isMut: true, isSigner: false },
        { name: 'system', isMut: true, isSigner: true },
        { name: 'systemAta', isMut: true, isSigner: false },
        { name: 'tokenProgram', isMut: false, isSigner: false },
      ],
      args: [
        { name: 'offerId', type: 'string' },
        { name: 'tierId', type: 'string' },
        { name: 'borrowAmount', type: 'u64' },
      ],
    },
    {
      name: 'depositCollateralLoanOfferNative',
      accounts: [
        { name: 'borrower', isMut: true, isSigner: true },
        { name: 'loanOffer', isMut: true, isSigner: false },
        { name: 'systemProgram', isMut: false, isSigner: false },
      ],
      args: [
        { name: 'offerId', type: 'string' },
        { name: 'tierId', type: 'string' },
        { name: 'amount', type: 'u64' },
      ],
    },
    {
      name: 'depositCollateralLoanOffer',
      accounts: [
        { name: 'borrower', isMut: true, isSigner: true },
        { name: 'collateralMintAsset', isMut: false, isSigner: false },
        { name: 'borrowerAtaAsset', isMut: true, isSigner: false },
        { name: 'loanOffer', isMut: true, isSigner: false },
        { name: 'vaultAuthority', isMut: false, isSigner: false },
        { name: 'vault', isMut: true, isSigner: false },
        { name: 'tokenProgram', isMut: false, isSigner: false },
      ],
      args: [
        { name: 'offerId', type: 'string' },
        { name: 'tierId', type: 'string' },
        { name: 'amount', type: 'u64' },
      ],
    },
    {
      name: 'repayLoanOfferNative',
      accounts: [
        { name: 'borrower', isMut: true, isSigner: true },
        { name: 'lendMintAsset', isMut: false, isSigner: false },
        { name: 'borrowerAtaLendAsset', isMut: true, isSigner: false },
        { name: 'loanOffer', isMut: true, isSigner: false },
        { name: 'hotWalletAtaLendAsset', isMut: true, isSigner: false },
        { name: 'tokenProgram', isMut: false, isSigner: false },
        { name: 'systemProgram', isMut: false, isSigner: false },
      ],
      args: [{ name: 'loanOfferId', type: 'string' }],
    },
    {
      name: 'repayLoanOffer',
      accounts: [
        { name: 'borrower', isMut: true, isSigner: true },
        { name: 'collateralMintAsset', isMut: false, isSigner: false },
        { name: 'lendMintAsset', isMut: false, isSigner: false },
        { name: 'borrowerAtaLendAsset', isMut: true, isSigner: false },
        { name: 'borrowerAtaCollateralAsset', isMut: true, isSigner: false },
        { name: 'loanOffer', isMut: true, isSigner: false },
        { name: 'vaultAuthority', isMut: true, isSigner: false },
        { name: 'vault', isMut: true, isSigner: false },
        { name: 'hotWalletAtaLendAsset', isMut: true, isSigner: false },
        { name: 'tokenProgram', isMut: false, isSigner: false },
      ],
      args: [{ name: 'loanOfferId', type: 'string' }],
    },
    {
      name: 'withdrawCollateralLoanOfferNative',
      accounts: [
        { name: 'borrower', isMut: true, isSigner: true },
        { name: 'collateralMintAsset', isMut: false, isSigner: false },
        { name: 'lendMintAsset', isMut: false, isSigner: false },
        { name: 'lendAsset', isMut: false, isSigner: false },
        { name: 'collateralAsset', isMut: false, isSigner: false },
        { name: 'loanOffer', isMut: true, isSigner: false },
        { name: 'lendPriceFeedAccount', isMut: false, isSigner: false },
        { name: 'collateralPriceFeedAccount', isMut: false, isSigner: false },
      ],
      args: [
        { name: 'loanOfferId', type: 'string' },
        { name: 'withdrawAmount', type: 'u64' },
      ],
    },
    {
      name: 'withdrawCollateralLoanOffer',
      accounts: [
        { name: 'borrower', isMut: true, isSigner: true },
        { name: 'collateralMintAsset', isMut: false, isSigner: false },
        { name: 'lendMintAsset', isMut: false, isSigner: false },
        { name: 'lendAsset', isMut: false, isSigner: false },
        { name: 'collateralAsset', isMut: false, isSigner: false },
        { name: 'borrowerAtaCollateralAsset', isMut: true, isSigner: false },
        { name: 'loanOffer', isMut: true, isSigner: false },
        { name: 'vaultAuthority', isMut: true, isSigner: false },
        { name: 'vault', isMut: true, isSigner: false },
        { name: 'lendPriceFeedAccount', isMut: false, isSigner: false },
        { name: 'collateralPriceFeedAccount', isMut: false, isSigner: false },
        { name: 'tokenProgram', isMut: false, isSigner: false },
      ],
      args: [
        { name: 'loanOfferId', type: 'string' },
        { name: 'withdrawAmount', type: 'u64' },
      ],
    },
    {
      name: 'startLiquidateLoanOfferNativeHealth',
      accounts: [
        { name: 'system', isMut: true, isSigner: true },
        { name: 'borrower', isMut: false, isSigner: false },
        { name: 'loanOffer', isMut: true, isSigner: false },
        { name: 'hotWallet', isMut: true, isSigner: false },
        { name: 'collateralMintAsset', isMut: false, isSigner: false },
        { name: 'lendMintAsset', isMut: false, isSigner: false },
        { name: 'lendAsset', isMut: false, isSigner: false },
        { name: 'collateralAsset', isMut: false, isSigner: false },
        { name: 'lendPriceFeedAccount', isMut: false, isSigner: false },
        { name: 'collateralPriceFeedAccount', isMut: false, isSigner: false },
      ],
      args: [{ name: 'offerId', type: 'string' }],
    },
    {
      name: 'startLiquidateLoanOfferHealth',
      accounts: [
        { name: 'system', isMut: true, isSigner: true },
        { name: 'borrower', isMut: false, isSigner: false },
        { name: 'loanOffer', isMut: true, isSigner: false },
        { name: 'collateralMintAsset', isMut: false, isSigner: false },
        { name: 'lendMintAsset', isMut: false, isSigner: false },
        { name: 'lendAsset', isMut: false, isSigner: false },
        { name: 'collateralAsset', isMut: false, isSigner: false },
        { name: 'lendPriceFeedAccount', isMut: false, isSigner: false },
        { name: 'collateralPriceFeedAccount', isMut: false, isSigner: false },
        { name: 'hotWalletAtaCollateralAsset', isMut: true, isSigner: false },
        { name: 'vaultAuthority', isMut: true, isSigner: false },
        { name: 'vault', isMut: true, isSigner: false },
        { name: 'tokenProgram', isMut: false, isSigner: false },
      ],
      args: [{ name: 'offerId', type: 'string' }],
    },
    {
      name: 'startLiquidateLoanOfferNativeExpired',
      accounts: [
        { name: 'system', isMut: true, isSigner: true },
        { name: 'borrower', isMut: false, isSigner: false },
        { name: 'loanOffer', isMut: true, isSigner: false },
        { name: 'hotWallet', isMut: true, isSigner: false },
      ],
      args: [{ name: 'offerId', type: 'string' }],
    },
    {
      name: 'startLiquidateLoanOfferExpired',
      accounts: [
        { name: 'system', isMut: true, isSigner: true },
        { name: 'borrower', isMut: false, isSigner: false },
        { name: 'collateralMintAsset', isMut: false, isSigner: false },
        { name: 'loanOffer', isMut: true, isSigner: false },
        { name: 'hotWalletAtaCollateralAsset', isMut: true, isSigner: false },
        { name: 'vaultAuthority', isMut: true, isSigner: false },
        { name: 'vault', isMut: true, isSigner: false },
        { name: 'tokenProgram', isMut: false, isSigner: false },
      ],
      args: [{ name: 'offerId', type: 'string' }],
    },
    {
      name: 'finishLiquidateContract',
      accounts: [
        { name: 'system', isMut: true, isSigner: true },
        { name: 'systemAta', isMut: true, isSigner: false },
        { name: 'mintAsset', isMut: false, isSigner: false },
        { name: 'borrower', isMut: false, isSigner: false },
        { name: 'borrowerAtaAsset', isMut: true, isSigner: false },
        { name: 'loanOffer', isMut: true, isSigner: false },
        { name: 'tokenProgram', isMut: false, isSigner: false },
      ],
      args: [
        { name: 'loanOfferId', type: 'string' },
        { name: 'collateralSwappedAmount', type: 'u64' },
        { name: 'liquidatedPrice', type: 'u64' },
        { name: 'liquidatedTx', type: 'string' },
      ],
    },
    {
      name: 'systemFinishLoanOffer',
      accounts: [
        { name: 'system', isMut: true, isSigner: true },
        { name: 'systemAta', isMut: true, isSigner: false },
        { name: 'mintAsset', isMut: false, isSigner: false },
        { name: 'lender', isMut: false, isSigner: false },
        { name: 'lenderAtaAsset', isMut: true, isSigner: false },
        { name: 'borrower', isMut: true, isSigner: false },
        { name: 'loanOffer', isMut: true, isSigner: false },
        { name: 'tokenProgram', isMut: false, isSigner: false },
        { name: 'systemProgram', isMut: false, isSigner: false },
      ],
      args: [
        { name: 'loanOfferId', type: 'string' },
        { name: 'loanAmount', type: 'u64' },
        { name: 'interestAmount', type: 'u64' },
      ],
    },
    {
      name: 'systemRevertStatus',
      accounts: [
        { name: 'system', isMut: true, isSigner: true },
        { name: 'borrower', isMut: false, isSigner: false },
        { name: 'loanOffer', isMut: true, isSigner: false },
      ],
      args: [{ name: 'offerId', type: 'string' }],
    },
    {
      name: 'closeLendOffer',
      accounts: [
        { name: 'signer', isMut: true, isSigner: true },
        { name: 'lender', isMut: false, isSigner: false },
        { name: 'lendOffer', isMut: true, isSigner: false },
        { name: 'systemProgram', isMut: false, isSigner: false },
      ],
      args: [{ name: 'offerId', type: 'string' }],
    },
    {
      name: 'initForeignChainAccount',
      accounts: [
        { name: 'owner', isMut: true, isSigner: true },
        { name: 'foreignChain', isMut: true, isSigner: false },
        { name: 'systemProgram', isMut: false, isSigner: false },
      ],
      args: [
        { name: 'chainId', type: 'u16' },
        { name: 'contractAddress', type: 'string' },
        { name: 'emitterAddress', type: 'string' },
        { name: 'crossChainFee', type: 'u64' },
      ],
    },
    {
      name: 'editForeignChainAccount',
      accounts: [
        { name: 'owner', isMut: true, isSigner: true },
        { name: 'foreignChain', isMut: true, isSigner: false },
      ],
      args: [
        { name: 'chainId', type: 'u16' },
        { name: 'contractAddress', type: { option: 'string' } },
        { name: 'emitterAddress', type: { option: 'string' } },
        { name: 'crossChainFee', type: { option: 'u64' } },
      ],
    },
    {
      name: 'createLoanOfferCrossChain',
      accounts: [
        { name: 'relayer', isMut: true, isSigner: true },
        { name: 'collateralMintAsset', isMut: false, isSigner: false },
        { name: 'lendMintAsset', isMut: false, isSigner: false },
        { name: 'lendAsset', isMut: false, isSigner: false },
        { name: 'collateralAsset', isMut: false, isSigner: false },
        { name: 'loanOffer', isMut: true, isSigner: false },
        { name: 'lendOffer', isMut: true, isSigner: false },
        { name: 'lender', isMut: false, isSigner: false },
        { name: 'borrower', isMut: false, isSigner: false },
        { name: 'settingAccount', isMut: false, isSigner: false },
        {
          name: 'posted',
          isMut: false,
          isSigner: false,
          docs: ['signatures and posted the account data here. Read-only.'],
        },
        { name: 'foreignChain', isMut: true, isSigner: false },
        { name: 'wormholeProgram', isMut: false, isSigner: false },
        { name: 'systemProgram', isMut: false, isSigner: false },
      ],
      args: [
        { name: 'tierId', type: 'string' },
        { name: 'loanOfferId', type: 'string' },
        { name: 'lendOfferId', type: 'string' },
        { name: 'vaaHash', type: { array: ['u8', 32] } },
      ],
    },
    {
      name: 'repayLoanOfferCrossChain',
      accounts: [
        { name: 'borrower', isMut: true, isSigner: true },
        { name: 'collateralMintAsset', isMut: false, isSigner: false },
        { name: 'lendMintAsset', isMut: false, isSigner: false },
        { name: 'collateralAsset', isMut: false, isSigner: false },
        { name: 'lendAsset', isMut: false, isSigner: false },
        { name: 'borrowerAtaLendAsset', isMut: true, isSigner: false },
        { name: 'loanOffer', isMut: true, isSigner: false },
        { name: 'hotWalletAtaLendAsset', isMut: true, isSigner: false },
        { name: 'config', isMut: false, isSigner: false },
        { name: 'wormholeBridge', isMut: true, isSigner: false },
        { name: 'wormholeFeeCollector', isMut: true, isSigner: false },
        { name: 'wormholeEmitter', isMut: false, isSigner: false },
        { name: 'wormholeSequence', isMut: true, isSigner: false },
        { name: 'wormholeMessage', isMut: true, isSigner: false },
        { name: 'foreignChain', isMut: true, isSigner: false },
        { name: 'wormholeProgram', isMut: false, isSigner: false },
        { name: 'tokenProgram', isMut: false, isSigner: false },
        { name: 'systemProgram', isMut: false, isSigner: false },
        { name: 'clock', isMut: false, isSigner: false },
        { name: 'rent', isMut: false, isSigner: false },
      ],
      args: [{ name: 'loanOfferId', type: 'string' }],
    },
    {
      name: 'initWormhole',
      accounts: [
        { name: 'owner', isMut: true, isSigner: true },
        { name: 'wormholeConfig', isMut: true, isSigner: false },
        { name: 'wormholeProgram', isMut: false, isSigner: false },
        { name: 'wormholeBridge', isMut: true, isSigner: false },
        { name: 'wormholeFeeCollector', isMut: true, isSigner: false },
        { name: 'wormholeEmitter', isMut: true, isSigner: false },
        { name: 'wormholeSequence', isMut: true, isSigner: false },
        { name: 'wormholeMessage', isMut: true, isSigner: false },
        { name: 'clock', isMut: false, isSigner: false },
        { name: 'rent', isMut: false, isSigner: false },
        { name: 'systemProgram', isMut: false, isSigner: false },
      ],
      args: [],
    },
    {
      name: 'updateDepositCollateralCrossChain',
      accounts: [
        { name: 'relayer', isMut: true, isSigner: true },
        { name: 'borrower', isMut: false, isSigner: false },
        { name: 'collateralMintAsset', isMut: false, isSigner: false },
        { name: 'collateralAsset', isMut: false, isSigner: false },
        { name: 'loanOffer', isMut: true, isSigner: false },
        {
          name: 'posted',
          isMut: false,
          isSigner: false,
          docs: ['signatures and posted the account data here. Read-only.'],
        },
        { name: 'foreignChain', isMut: true, isSigner: false },
        { name: 'wormholeProgram', isMut: false, isSigner: false },
        { name: 'systemProgram', isMut: false, isSigner: false },
      ],
      args: [
        { name: 'loanOfferId', type: 'string' },
        { name: 'vaaHash', type: { array: ['u8', 32] } },
      ],
    },
    {
      name: 'updateWithdrawCollateralCrossChain',
      accounts: [
        { name: 'relayer', isMut: true, isSigner: true },
        { name: 'borrower', isMut: false, isSigner: false },
        { name: 'collateralMintAsset', isMut: false, isSigner: false },
        { name: 'collateralAsset', isMut: false, isSigner: false },
        { name: 'loanOffer', isMut: true, isSigner: false },
        {
          name: 'posted',
          isMut: false,
          isSigner: false,
          docs: ['signatures and posted the account data here. Read-only.'],
        },
        { name: 'foreignChain', isMut: true, isSigner: false },
        { name: 'wormholeProgram', isMut: false, isSigner: false },
        { name: 'systemProgram', isMut: false, isSigner: false },
      ],
      args: [
        { name: 'loanOfferId', type: 'string' },
        { name: 'vaaHash', type: { array: ['u8', 32] } },
      ],
    },
    {
      name: 'requestCancelCollateralCrossChain',
      accounts: [
        { name: 'relayer', isMut: true, isSigner: true },
        { name: 'borrower', isMut: false, isSigner: false },
        { name: 'lender', isMut: false, isSigner: false },
        { name: 'lendMintAsset', isMut: false, isSigner: false },
        { name: 'lendAsset', isMut: false, isSigner: false },
        { name: 'collateralMintAsset', isMut: false, isSigner: false },
        { name: 'collateralAsset', isMut: false, isSigner: false },
        { name: 'lendOffer', isMut: true, isSigner: false },
        {
          name: 'posted',
          isMut: false,
          isSigner: false,
          docs: ['signatures and posted the account data here. Read-only.'],
        },
        { name: 'foreignChain', isMut: true, isSigner: false },
        { name: 'config', isMut: false, isSigner: false },
        { name: 'wormholeProgram', isMut: false, isSigner: false },
        { name: 'wormholeBridge', isMut: true, isSigner: false },
        { name: 'wormholeFeeCollector', isMut: true, isSigner: false },
        { name: 'wormholeEmitter', isMut: false, isSigner: false },
        { name: 'wormholeSequence', isMut: true, isSigner: false },
        { name: 'wormholeMessage', isMut: true, isSigner: false },
        { name: 'systemProgram', isMut: false, isSigner: false },
        { name: 'clock', isMut: false, isSigner: false },
        { name: 'rent', isMut: false, isSigner: false },
      ],
      args: [
        { name: 'tierId', type: 'string' },
        { name: 'lendOfferId', type: 'string' },
        { name: 'vaaHash', type: { array: ['u8', 32] } },
      ],
    },
    {
      name: 'requestCancelLoanedCrossChain',
      accounts: [
        { name: 'relayer', isMut: true, isSigner: true },
        { name: 'borrower', isMut: false, isSigner: false },
        { name: 'lender', isMut: false, isSigner: false },
        { name: 'lendMintAsset', isMut: false, isSigner: false },
        { name: 'lendAsset', isMut: false, isSigner: false },
        { name: 'collateralMintAsset', isMut: false, isSigner: false },
        { name: 'collateralAsset', isMut: false, isSigner: false },
        { name: 'lendOffer', isMut: true, isSigner: false },
        { name: 'loanOffer', isMut: true, isSigner: false },
        {
          name: 'posted',
          isMut: false,
          isSigner: false,
          docs: ['signatures and posted the account data here. Read-only.'],
        },
        { name: 'foreignChain', isMut: true, isSigner: false },
        { name: 'config', isMut: false, isSigner: false },
        { name: 'wormholeProgram', isMut: false, isSigner: false },
        { name: 'wormholeBridge', isMut: true, isSigner: false },
        { name: 'wormholeFeeCollector', isMut: true, isSigner: false },
        { name: 'wormholeEmitter', isMut: false, isSigner: false },
        { name: 'wormholeSequence', isMut: true, isSigner: false },
        { name: 'wormholeMessage', isMut: true, isSigner: false },
        { name: 'systemProgram', isMut: false, isSigner: false },
        { name: 'clock', isMut: false, isSigner: false },
        { name: 'rent', isMut: false, isSigner: false },
      ],
      args: [
        { name: 'tierId', type: 'string' },
        { name: 'lendOfferId', type: 'string' },
        { name: 'loanOfferId', type: 'string' },
        { name: 'vaaHash', type: { array: ['u8', 32] } },
        { name: 'loanedBorrower', type: 'publicKey' },
      ],
    },
    {
      name: 'depositCollateralTakeLoanCrossChainNative',
      accounts: [
        { name: 'borrower', isMut: true, isSigner: true },
        { name: 'relayer', isMut: true, isSigner: false },
        { name: 'lendMint', isMut: false, isSigner: false },
        { name: 'lendAsset', isMut: false, isSigner: false },
        { name: 'collateralMint', isMut: false, isSigner: false },
        { name: 'collateralAsset', isMut: false, isSigner: false },
        { name: 'collateralHolder', isMut: true, isSigner: false },
        { name: 'lendPriceFeedAccount', isMut: false, isSigner: false },
        { name: 'collateralPriceFeedAccount', isMut: false, isSigner: false },
        { name: 'foreignChain', isMut: true, isSigner: false },
        { name: 'wormholeConfig', isMut: false, isSigner: false },
        { name: 'wormholeProgram', isMut: false, isSigner: false },
        { name: 'wormholeBridge', isMut: true, isSigner: false },
        { name: 'wormholeFeeCollector', isMut: true, isSigner: false },
        { name: 'wormholeEmitter', isMut: false, isSigner: false },
        { name: 'wormholeSequence', isMut: true, isSigner: false },
        { name: 'wormholeMessage', isMut: true, isSigner: false },
        { name: 'systemProgram', isMut: false, isSigner: false },
        { name: 'clock', isMut: false, isSigner: false },
        { name: 'rent', isMut: false, isSigner: false },
      ],
      args: [
        { name: 'tierId', type: 'string' },
        { name: 'lendOfferId', type: 'string' },
        { name: 'lendAmount', type: 'u64' },
        { name: 'collateralAmount', type: 'u64' },
        { name: 'lendChainId', type: 'u16' },
        { name: 'interest', type: 'u16' },
        { name: 'lendChainBorrower', type: 'string' },
      ],
    },
    {
      name: 'depositCollateralLoanOfferCrossChainNative',
      accounts: [
        { name: 'borrower', isMut: true, isSigner: true },
        { name: 'relayer', isMut: true, isSigner: false },
        { name: 'collateralHolder', isMut: true, isSigner: false },
        { name: 'lendMint', isMut: false, isSigner: false },
        { name: 'lendAsset', isMut: false, isSigner: false },
        { name: 'collateralMint', isMut: false, isSigner: false },
        { name: 'collateralAsset', isMut: false, isSigner: false },
        { name: 'wormholeConfig', isMut: false, isSigner: false },
        { name: 'foreignChain', isMut: false, isSigner: false },
        { name: 'wormholeProgram', isMut: false, isSigner: false },
        { name: 'wormholeBridge', isMut: true, isSigner: false },
        { name: 'wormholeFeeCollector', isMut: true, isSigner: false },
        { name: 'wormholeEmitter', isMut: false, isSigner: false },
        { name: 'wormholeSequence', isMut: true, isSigner: false },
        { name: 'wormholeMessage', isMut: true, isSigner: false },
        { name: 'systemProgram', isMut: false, isSigner: false },
        { name: 'clock', isMut: false, isSigner: false },
        { name: 'rent', isMut: false, isSigner: false },
      ],
      args: [
        { name: 'lendOfferId', type: 'string' },
        { name: 'lendChainId', type: 'u16' },
        { name: 'depositAmount', type: 'u64' },
      ],
    },
    {
      name: 'depositCollateralLoanOfferCrossChain',
      accounts: [
        { name: 'borrower', isMut: true, isSigner: true },
        { name: 'relayer', isMut: true, isSigner: false },
        { name: 'collateralMint', isMut: false, isSigner: false },
        { name: 'borrowerCollateralMintAta', isMut: true, isSigner: false },
        { name: 'vaultAuthority', isMut: false, isSigner: false },
        { name: 'vault', isMut: true, isSigner: false },
        { name: 'collateralHolder', isMut: true, isSigner: false },
        { name: 'lendMint', isMut: false, isSigner: false },
        { name: 'lendAsset', isMut: false, isSigner: false },
        { name: 'collateralAsset', isMut: false, isSigner: false },
        { name: 'wormholeConfig', isMut: false, isSigner: false },
        { name: 'foreignChain', isMut: false, isSigner: false },
        { name: 'wormholeProgram', isMut: false, isSigner: false },
        { name: 'wormholeBridge', isMut: true, isSigner: false },
        { name: 'wormholeFeeCollector', isMut: true, isSigner: false },
        { name: 'wormholeEmitter', isMut: false, isSigner: false },
        { name: 'wormholeSequence', isMut: true, isSigner: false },
        { name: 'wormholeMessage', isMut: true, isSigner: false },
        { name: 'systemProgram', isMut: false, isSigner: false },
        { name: 'tokenProgram', isMut: false, isSigner: false },
        { name: 'clock', isMut: false, isSigner: false },
        { name: 'rent', isMut: false, isSigner: false },
      ],
      args: [
        { name: 'lendOfferId', type: 'string' },
        { name: 'lendChainId', type: 'u16' },
        { name: 'depositAmount', type: 'u64' },
      ],
    },
    {
      name: 'withdrawCollateralLoanOfferCrossChainNative',
      accounts: [
        { name: 'borrower', isMut: true, isSigner: true },
        { name: 'relayer', isMut: true, isSigner: false },
        { name: 'lendMint', isMut: false, isSigner: false },
        { name: 'lendAsset', isMut: false, isSigner: false },
        { name: 'collateralMint', isMut: false, isSigner: false },
        { name: 'collateralAsset', isMut: false, isSigner: false },
        { name: 'collateralHolder', isMut: true, isSigner: false },
        { name: 'lendPriceFeedAccount', isMut: false, isSigner: false },
        { name: 'collateralPriceFeedAccount', isMut: false, isSigner: false },
        { name: 'wormholeConfig', isMut: false, isSigner: false },
        { name: 'foreignChain', isMut: false, isSigner: false },
        { name: 'wormholeProgram', isMut: false, isSigner: false },
        { name: 'wormholeBridge', isMut: true, isSigner: false },
        { name: 'wormholeFeeCollector', isMut: true, isSigner: false },
        { name: 'wormholeEmitter', isMut: false, isSigner: false },
        { name: 'wormholeSequence', isMut: true, isSigner: false },
        { name: 'wormholeMessage', isMut: true, isSigner: false },
        { name: 'systemProgram', isMut: false, isSigner: false },
        { name: 'clock', isMut: false, isSigner: false },
        { name: 'rent', isMut: false, isSigner: false },
      ],
      args: [
        { name: 'lendOfferId', type: 'string' },
        { name: 'lendChainId', type: 'u16' },
        { name: 'withdrawAmount', type: 'u64' },
      ],
    },
    {
      name: 'withdrawCollateralLoanOfferCrossChain',
      accounts: [
        { name: 'borrower', isMut: true, isSigner: true },
        { name: 'relayer', isMut: true, isSigner: false },
        { name: 'borrowerCollateralMintAta', isMut: true, isSigner: false },
        { name: 'vaultAuthority', isMut: false, isSigner: false },
        { name: 'vault', isMut: true, isSigner: false },
        { name: 'lendMint', isMut: false, isSigner: false },
        { name: 'lendAsset', isMut: false, isSigner: false },
        { name: 'collateralMint', isMut: false, isSigner: false },
        { name: 'collateralAsset', isMut: false, isSigner: false },
        { name: 'collateralHolder', isMut: true, isSigner: false },
        { name: 'lendPriceFeedAccount', isMut: false, isSigner: false },
        { name: 'collateralPriceFeedAccount', isMut: false, isSigner: false },
        { name: 'wormholeConfig', isMut: false, isSigner: false },
        { name: 'foreignChain', isMut: false, isSigner: false },
        { name: 'wormholeProgram', isMut: false, isSigner: false },
        { name: 'wormholeBridge', isMut: true, isSigner: false },
        { name: 'wormholeFeeCollector', isMut: true, isSigner: false },
        { name: 'wormholeEmitter', isMut: false, isSigner: false },
        { name: 'wormholeSequence', isMut: true, isSigner: false },
        { name: 'wormholeMessage', isMut: true, isSigner: false },
        { name: 'systemProgram', isMut: false, isSigner: false },
        { name: 'tokenProgram', isMut: false, isSigner: false },
        { name: 'clock', isMut: false, isSigner: false },
        { name: 'rent', isMut: false, isSigner: false },
      ],
      args: [
        { name: 'lendOfferId', type: 'string' },
        { name: 'lendChainId', type: 'u16' },
        { name: 'withdrawAmount', type: 'u64' },
      ],
    },
    {
      name: 'refundCollateralLoanOfferCrossChainNative',
      accounts: [
        { name: 'relayer', isMut: true, isSigner: true },
        { name: 'borrower', isMut: true, isSigner: false },
        { name: 'collateralHolder', isMut: true, isSigner: false },
        { name: 'foreignChain', isMut: false, isSigner: false },
        {
          name: 'posted',
          isMut: false,
          isSigner: false,
          docs: ['signatures and posted the account data here. Read-only.'],
        },
        { name: 'wormholeProgram', isMut: false, isSigner: false },
        { name: 'systemProgram', isMut: false, isSigner: false },
      ],
      args: [
        { name: 'lendOfferId', type: 'string' },
        { name: 'lendChainId', type: 'u16' },
        { name: 'vaaHash', type: { array: ['u8', 32] } },
      ],
    },
    {
      name: 'refundCollateralLoanOfferCrossChain',
      accounts: [
        { name: 'relayer', isMut: true, isSigner: true },
        { name: 'borrower', isMut: true, isSigner: false },
        { name: 'collateralMint', isMut: false, isSigner: false },
        { name: 'borrowerCollateralMintAta', isMut: true, isSigner: false },
        { name: 'vaultAuthority', isMut: false, isSigner: false },
        { name: 'vault', isMut: true, isSigner: false },
        { name: 'collateralHolder', isMut: true, isSigner: false },
        { name: 'foreignChain', isMut: false, isSigner: false },
        {
          name: 'posted',
          isMut: false,
          isSigner: false,
          docs: ['signatures and posted the account data here. Read-only.'],
        },
        { name: 'wormholeProgram', isMut: false, isSigner: false },
        { name: 'systemProgram', isMut: false, isSigner: false },
        { name: 'tokenProgram', isMut: false, isSigner: false },
      ],
      args: [
        { name: 'lendOfferId', type: 'string' },
        { name: 'lendChainId', type: 'u16' },
        { name: 'vaaHash', type: { array: ['u8', 32] } },
      ],
    },
    {
      name: 'liquidateCollateralCrossChainNative',
      accounts: [
        { name: 'relayer', isMut: true, isSigner: true },
        { name: 'hotWallet', isMut: true, isSigner: false },
        { name: 'borrower', isMut: false, isSigner: false },
        { name: 'collateralHolder', isMut: true, isSigner: false },
        { name: 'foreignChain', isMut: false, isSigner: false },
        {
          name: 'posted',
          isMut: false,
          isSigner: false,
          docs: ['signatures and posted the account data here. Read-only.'],
        },
        { name: 'wormholeProgram', isMut: false, isSigner: false },
        { name: 'systemProgram', isMut: false, isSigner: false },
      ],
      args: [
        { name: 'lendOfferId', type: 'string' },
        { name: 'lendChainId', type: 'u16' },
        { name: 'vaaHash', type: { array: ['u8', 32] } },
      ],
    },
    {
      name: 'liquidateCollateralCrossChain',
      accounts: [
        { name: 'relayer', isMut: true, isSigner: true },
        { name: 'hotWalletCollateralMintAta', isMut: true, isSigner: false },
        { name: 'borrower', isMut: false, isSigner: false },
        { name: 'collateralMint', isMut: false, isSigner: false },
        { name: 'vaultAuthority', isMut: true, isSigner: false },
        { name: 'vault', isMut: true, isSigner: false },
        { name: 'collateralHolder', isMut: true, isSigner: false },
        { name: 'foreignChain', isMut: false, isSigner: false },
        {
          name: 'posted',
          isMut: false,
          isSigner: false,
          docs: ['signatures and posted the account data here. Read-only.'],
        },
        { name: 'wormholeProgram', isMut: false, isSigner: false },
        { name: 'tokenProgram', isMut: false, isSigner: false },
      ],
      args: [
        { name: 'lendOfferId', type: 'string' },
        { name: 'lendChainId', type: 'u16' },
        { name: 'vaaHash', type: { array: ['u8', 32] } },
      ],
    },
    {
      name: 'startLiquidateHealthLoanCrossChain',
      accounts: [
        { name: 'system', isMut: true, isSigner: true },
        { name: 'borrower', isMut: false, isSigner: false },
        { name: 'loanOffer', isMut: true, isSigner: false },
        { name: 'collateralMintAsset', isMut: false, isSigner: false },
        { name: 'lendMintAsset', isMut: false, isSigner: false },
        { name: 'lendAsset', isMut: false, isSigner: false },
        { name: 'collateralAsset', isMut: false, isSigner: false },
        { name: 'lendPriceFeedAccount', isMut: false, isSigner: false },
        { name: 'collateralPriceFeedAccount', isMut: false, isSigner: false },
        { name: 'foreignChain', isMut: true, isSigner: false },
        { name: 'config', isMut: false, isSigner: false },
        { name: 'wormholeProgram', isMut: false, isSigner: false },
        { name: 'wormholeBridge', isMut: true, isSigner: false },
        { name: 'wormholeFeeCollector', isMut: true, isSigner: false },
        { name: 'wormholeEmitter', isMut: false, isSigner: false },
        { name: 'wormholeSequence', isMut: true, isSigner: false },
        { name: 'wormholeMessage', isMut: true, isSigner: false },
        { name: 'systemProgram', isMut: false, isSigner: false },
        { name: 'clock', isMut: false, isSigner: false },
        { name: 'rent', isMut: false, isSigner: false },
      ],
      args: [{ name: 'loanOfferId', type: 'string' }],
    },
    {
      name: 'startLiquidateExpiredLoanCrossChain',
      accounts: [
        { name: 'system', isMut: true, isSigner: true },
        { name: 'borrower', isMut: false, isSigner: false },
        { name: 'collateralMintAsset', isMut: false, isSigner: false },
        { name: 'collateralAsset', isMut: false, isSigner: false },
        { name: 'loanOffer', isMut: true, isSigner: false },
        { name: 'foreignChain', isMut: true, isSigner: false },
        { name: 'config', isMut: false, isSigner: false },
        { name: 'wormholeProgram', isMut: false, isSigner: false },
        { name: 'wormholeBridge', isMut: true, isSigner: false },
        { name: 'wormholeFeeCollector', isMut: true, isSigner: false },
        { name: 'wormholeEmitter', isMut: false, isSigner: false },
        { name: 'wormholeSequence', isMut: true, isSigner: false },
        { name: 'wormholeMessage', isMut: true, isSigner: false },
        { name: 'systemProgram', isMut: false, isSigner: false },
        { name: 'clock', isMut: false, isSigner: false },
        { name: 'rent', isMut: false, isSigner: false },
      ],
      args: [{ name: 'loanOfferId', type: 'string' }],
    },
    {
      name: 'depositCollateralTakeLoanCrossChain',
      accounts: [
        { name: 'borrower', isMut: true, isSigner: true },
        { name: 'relayer', isMut: true, isSigner: false },
        { name: 'lendMint', isMut: false, isSigner: false },
        { name: 'lendAsset', isMut: false, isSigner: false },
        { name: 'collateralMint', isMut: false, isSigner: false },
        { name: 'collateralAsset', isMut: false, isSigner: false },
        { name: 'borrowerCollateralMintAta', isMut: true, isSigner: false },
        { name: 'collateralHolder', isMut: true, isSigner: false },
        { name: 'vaultAuthority', isMut: false, isSigner: false },
        { name: 'vault', isMut: true, isSigner: false },
        { name: 'lendPriceFeedAccount', isMut: false, isSigner: false },
        { name: 'collateralPriceFeedAccount', isMut: false, isSigner: false },
        { name: 'foreignChain', isMut: false, isSigner: false },
        { name: 'wormholeConfig', isMut: false, isSigner: false },
        { name: 'wormholeBridge', isMut: true, isSigner: false },
        { name: 'wormholeFeeCollector', isMut: true, isSigner: false },
        { name: 'wormholeEmitter', isMut: false, isSigner: false },
        { name: 'wormholeSequence', isMut: true, isSigner: false },
        { name: 'wormholeMessage', isMut: true, isSigner: false },
        { name: 'clock', isMut: false, isSigner: false },
        { name: 'rent', isMut: false, isSigner: false },
        { name: 'wormholeProgram', isMut: false, isSigner: false },
        { name: 'tokenProgram', isMut: false, isSigner: false },
        { name: 'systemProgram', isMut: false, isSigner: false },
      ],
      args: [
        { name: 'tierId', type: 'string' },
        { name: 'lendOfferId', type: 'string' },
        { name: 'lendAmount', type: 'u64' },
        { name: 'collateralAmount', type: 'u64' },
        { name: 'lendChainId', type: 'u16' },
        { name: 'interest', type: 'u16' },
        { name: 'lendChainBorrower', type: 'string' },
      ],
    },
    {
      name: 'cancelCollateralCrossChainNative',
      accounts: [
        { name: 'relayer', isMut: true, isSigner: true },
        { name: 'borrower', isMut: true, isSigner: false },
        { name: 'collateralHolder', isMut: true, isSigner: false },
        {
          name: 'posted',
          isMut: false,
          isSigner: false,
          docs: ['signatures and posted the account data here. Read-only.'],
        },
        { name: 'foreignChain', isMut: true, isSigner: false },
        { name: 'wormholeProgram', isMut: false, isSigner: false },
        { name: 'systemProgram', isMut: false, isSigner: false },
      ],
      args: [
        { name: 'lendOfferId', type: 'string' },
        { name: 'lendChainId', type: 'u16' },
        { name: 'vaaHash', type: { array: ['u8', 32] } },
      ],
    },
    {
      name: 'cancelCollateralCrossChain',
      accounts: [
        { name: 'relayer', isMut: true, isSigner: true },
        { name: 'borrower', isMut: true, isSigner: false },
        { name: 'collateralHolder', isMut: true, isSigner: false },
        { name: 'collateralMint', isMut: false, isSigner: false },
        { name: 'collateralAsset', isMut: false, isSigner: false },
        { name: 'borrowerCollateralMintAta', isMut: true, isSigner: false },
        { name: 'vaultAuthority', isMut: true, isSigner: false },
        { name: 'vault', isMut: true, isSigner: false },
        {
          name: 'posted',
          isMut: false,
          isSigner: false,
          docs: ['signatures and posted the account data here. Read-only.'],
        },
        { name: 'foreignChain', isMut: true, isSigner: false },
        { name: 'wormholeProgram', isMut: false, isSigner: false },
        { name: 'associatedTokenProgram', isMut: false, isSigner: false },
        { name: 'tokenProgram', isMut: false, isSigner: false },
        { name: 'systemProgram', isMut: false, isSigner: false },
      ],
      args: [
        { name: 'lendOfferId', type: 'string' },
        { name: 'lendChainId', type: 'u16' },
        { name: 'vaaHash', type: { array: ['u8', 32] } },
      ],
    },
    {
      name: 'openActiveLendOffer',
      accounts: [
        { name: 'system', isMut: true, isSigner: true },
        { name: 'lendAsset', isMut: false, isSigner: false },
        { name: 'lendMint', isMut: false, isSigner: false },
        { name: 'settingAccount', isMut: false, isSigner: false },
        { name: 'lender', isMut: false, isSigner: false },
        { name: 'lendOffer', isMut: true, isSigner: false },
        { name: 'systemProgram', isMut: false, isSigner: false },
      ],
      args: [
        { name: 'offerId', type: 'string' },
        { name: 'tierId', type: 'string' },
        { name: 'interest', type: 'u16' },
      ],
    },
    {
      name: 'openActiveLoanOfferNative',
      accounts: [
        { name: 'system', isMut: true, isSigner: true },
        { name: 'borrower', isMut: false, isSigner: false },
        { name: 'lender', isMut: false, isSigner: false },
        { name: 'lendMint', isMut: false, isSigner: false },
        { name: 'lendAsset', isMut: false, isSigner: false },
        { name: 'collateralMint', isMut: false, isSigner: false },
        { name: 'collateralAsset', isMut: false, isSigner: false },
        { name: 'settingAccount', isMut: false, isSigner: false },
        { name: 'lendOffer', isMut: true, isSigner: false },
        { name: 'loanOffer', isMut: true, isSigner: false },
        { name: 'systemProgram', isMut: false, isSigner: false },
      ],
      args: [
        { name: 'loanOfferId', type: 'string' },
        { name: 'lendOfferId', type: 'string' },
        { name: 'tierId', type: 'string' },
        { name: 'interest', type: 'u16' },
        { name: 'collateralAmount', type: 'u64' },
        { name: 'loanOfferStartedAt', type: 'i64' },
      ],
    },
    {
      name: 'openActiveLoanOffer',
      accounts: [
        { name: 'system', isMut: true, isSigner: true },
        { name: 'systemCollateralAta', isMut: true, isSigner: false },
        { name: 'borrower', isMut: false, isSigner: false },
        { name: 'lender', isMut: false, isSigner: false },
        { name: 'lendMint', isMut: false, isSigner: false },
        { name: 'lendAsset', isMut: false, isSigner: false },
        { name: 'collateralMint', isMut: false, isSigner: false },
        { name: 'collateralAsset', isMut: false, isSigner: false },
        { name: 'vaultAuthority', isMut: true, isSigner: false },
        { name: 'vault', isMut: true, isSigner: false },
        { name: 'settingAccount', isMut: false, isSigner: false },
        { name: 'lendOffer', isMut: true, isSigner: false },
        { name: 'loanOffer', isMut: true, isSigner: false },
        { name: 'associatedTokenProgram', isMut: false, isSigner: false },
        { name: 'tokenProgram', isMut: false, isSigner: false },
        { name: 'systemProgram', isMut: false, isSigner: false },
      ],
      args: [
        { name: 'loanOfferId', type: 'string' },
        { name: 'lendOfferId', type: 'string' },
        { name: 'tierId', type: 'string' },
        { name: 'interest', type: 'u16' },
        { name: 'collateralAmount', type: 'u64' },
        { name: 'loanOfferStartedAt', type: 'i64' },
      ],
    },
  ],
  accounts: [
    {
      name: 'Asset',
      type: {
        kind: 'struct',
        fields: [
          { name: 'tokenMint', type: 'publicKey' },
          { name: 'maxPriceAgeSeconds', type: 'u64' },
          { name: 'decimals', type: 'u8' },
          { name: 'isCollateral', type: 'bool' },
          { name: 'isLend', type: 'bool' },
          { name: 'priceFeedId', type: 'string' },
          { name: 'priceFeedAccount', type: 'publicKey' },
          { name: 'bump', type: 'u8' },
          { name: 'name', type: 'string' },
          { name: 'tokenAddress', type: { option: { array: ['u8', 32] } } },
          { name: 'chainId', type: 'u16' },
        ],
      },
    },
    {
      name: 'CollateralHolder',
      type: {
        kind: 'struct',
        fields: [
          { name: 'bump', type: 'u8' },
          { name: 'lendAmount', type: 'u64' },
          { name: 'lendChainId', type: 'u16' },
          { name: 'collateralAmount', type: 'u64' },
          { name: 'borrower', type: 'publicKey' },
          { name: 'collateralMintToken', type: 'publicKey' },
          { name: 'status', type: { defined: 'CollateralHolderStatus' } },
          { name: 'startedAt', type: 'i64' },
          { name: 'lendOfferId', type: 'string' },
          { name: 'lendTokenAddress', type: { array: ['u8', 32] } },
          { name: 'lendChainBorrower', type: { array: ['u8', 32] } },
          { name: 'padding', type: { array: ['u64', 7] } },
        ],
      },
    },
    {
      name: 'ForeignChain',
      type: {
        kind: 'struct',
        fields: [
          {
            name: 'chainId',
            docs: ["Emitter chain. Cannot equal `1` (Solana's Chain ID)."],
            type: 'u16',
          },
          { name: 'contractAddress', type: { array: ['u8', 32] } },
          { name: 'emitterAddress', type: { array: ['u8', 32] } },
          { name: 'crossChainFee', type: 'u64' },
          { name: 'bump', type: 'u8' },
        ],
      },
    },
    {
      name: 'LendOfferAccount',
      type: {
        kind: 'struct',
        fields: [
          { name: 'interest', type: 'u16' },
          { name: 'lenderFeePercent', type: 'f64' },
          { name: 'duration', type: 'u64' },
          { name: 'offerId', type: 'string' },
          { name: 'lender', type: 'publicKey' },
          { name: 'lendMintToken', type: 'publicKey' },
          { name: 'amount', type: 'u64' },
          { name: 'bump', type: 'u8' },
          { name: 'status', type: { defined: 'LendOfferStatus' } },
        ],
      },
    },
    {
      name: 'LoanOfferAccount',
      type: {
        kind: 'struct',
        fields: [
          { name: 'tierId', type: 'string' },
          { name: 'lendOfferId', type: 'string' },
          { name: 'interest', type: 'u16' },
          { name: 'borrowAmount', type: 'u64' },
          { name: 'lenderFeePercent', type: 'f64' },
          { name: 'duration', type: 'u64' },
          { name: 'lendMintToken', type: 'publicKey' },
          { name: 'lender', type: 'publicKey' },
          { name: 'offerId', type: 'string' },
          { name: 'borrower', type: 'publicKey' },
          { name: 'collateralMintToken', type: 'publicKey' },
          { name: 'collateralAmount', type: 'u64' },
          { name: 'requestWithdrawAmount', type: { option: 'u64' } },
          { name: 'status', type: { defined: 'LoanOfferStatus' } },
          { name: 'borrowerFeePercent', type: 'f64' },
          { name: 'startedAt', type: 'i64' },
          { name: 'liquidatingAt', type: { option: 'i64' } },
          { name: 'liquidatingPrice', type: { option: 'f64' } },
          { name: 'liquidatedTx', type: { option: 'string' } },
          { name: 'liquidatedPrice', type: { option: 'u64' } },
          { name: 'bump', type: 'u8' },
          { name: 'liquidationFeePercent', type: 'f64' },
        ],
      },
    },
    {
      name: 'SettingAccount',
      type: {
        kind: 'struct',
        fields: [
          { name: 'amount', type: 'u64' },
          { name: 'duration', type: 'u64' },
          { name: 'owner', type: 'publicKey' },
          { name: 'receiver', type: 'publicKey' },
          { name: 'lendMintAsset', type: 'publicKey' },
          { name: 'collateralMintAsset', type: 'publicKey' },
          { name: 'tierId', type: 'string' },
          { name: 'lenderFeePercent', type: 'f64' },
          { name: 'borrowerFeePercent', type: 'f64' },
          { name: 'lendPriceFeed', type: 'publicKey' },
          { name: 'collateralPriceFeed', type: 'publicKey' },
          { name: 'bump', type: 'u8' },
          { name: 'liquidationFeePercent', type: 'f64' },
        ],
      },
    },
    {
      name: 'VaultAuthority',
      type: {
        kind: 'struct',
        fields: [
          { name: 'initializer', type: 'publicKey' },
          { name: 'bump', type: 'u8' },
        ],
      },
    },
    {
      name: 'WormholeConfig',
      type: {
        kind: 'struct',
        fields: [
          { name: 'bump', type: 'u8' },
          { name: 'owner', type: 'publicKey' },
          { name: 'wormhole', type: { defined: 'WormholeAddresses' } },
          { name: 'batchId', type: 'u32' },
          { name: 'finality', type: 'u8' },
        ],
      },
    },
    {
      name: 'WormholeEmitter',
      type: {
        kind: 'struct',
        fields: [{ name: 'bump', docs: ['PDA bump.'], type: 'u8' }],
      },
    },
  ],
  types: [
    {
      name: 'WormholeAddresses',
      type: {
        kind: 'struct',
        fields: [
          { name: 'bridge', type: 'publicKey' },
          { name: 'feeCollector', type: 'publicKey' },
          { name: 'sequence', type: 'publicKey' },
        ],
      },
    },
    {
      name: 'LendOfferStatus',
      type: {
        kind: 'enum',
        variants: [
          { name: 'Created' },
          { name: 'Canceling' },
          { name: 'Canceled' },
          { name: 'Loaned' },
        ],
      },
    },
    {
      name: 'LoanOfferStatus',
      type: {
        kind: 'enum',
        variants: [
          { name: 'Matched' },
          { name: 'FundTransferred' },
          { name: 'Repay' },
          { name: 'BorrowerPaid' },
          { name: 'Liquidating' },
          { name: 'Liquidated' },
          { name: 'Finished' },
        ],
      },
    },
    {
      name: 'CollateralHolderStatus',
      type: {
        kind: 'enum',
        variants: [
          { name: 'Created' },
          { name: 'BorrowerPaid' },
          { name: 'Liquidated' },
        ],
      },
    },
    {
      name: 'LendOfferError',
      type: {
        kind: 'enum',
        variants: [
          { name: 'InvalidLendAmount' },
          { name: 'NotEnoughAmount' },
          { name: 'InvalidMintAsset' },
          { name: 'InterestGreaterThanZero' },
          { name: 'InvalidLender' },
          { name: 'InvalidOfferStatus' },
          { name: 'InvalidOfferId' },
          { name: 'InvalidReceiver' },
          { name: 'InterestOverLimit' },
          { name: 'InvalidSigner' },
        ],
      },
    },
    {
      name: 'LoanOfferError',
      type: {
        kind: 'enum',
        variants: [
          { name: 'InvalidReceiver' },
          { name: 'CanNotDepositCollateralToContractThatNotAvailable' },
          { name: 'CanNotTakeALoanBecauseHealthRatioIsNotValid' },
          { name: 'InvalidPriceFeedAccountForCollateralAsset' },
          { name: 'InvalidPriceFeedAccountForLendAsset' },
          { name: 'NotEnoughAmount' },
          { name: 'InvalidCollateralMintAsset' },
          { name: 'InvalidLendMintAsset' },
          { name: 'InvalidOfferStatus' },
          { name: 'LendOfferIsNotAvailable' },
          { name: 'HealthRatioLimit' },
          { name: 'LoanOfferExpired' },
          { name: 'LoanOfferNotExpired' },
          { name: 'InvalidHotWallet' },
          { name: 'InvalidSystem' },
          { name: 'InvalidBorrower' },
          { name: 'InvalidLoanOffer' },
          { name: 'InvalidBorrowAmount' },
          { name: 'NotAvailableToWithdraw' },
          { name: 'HealthRatioInvalid' },
          { name: 'CanNotCreateLoanCauseLendInterestUpdated' },
          { name: 'InvalidPriceFeedAccount' },
          { name: 'InvalidAssetAccount' },
          { name: 'NotEnoughCollateral' },
          { name: 'InvalidInitializerVaultAuthority' },
          { name: 'InvalidTargetFunction' },
          { name: 'LendOfferIdNotMatch' },
          { name: 'TierIdNotMatch' },
          { name: 'PostedVaaExpired' },
          { name: 'BorrowerSignedLoanOffer' },
          { name: 'LoanOfferInValidity' },
          { name: 'InvalidLendOfferAmount' },
          { name: 'InvalidChainId' },
          { name: 'WithdrawAmountNotMatch' },
          { name: 'InvalidCollateralHolder' },
          { name: 'DepositAmountNotMatch' },
          { name: 'InvalidProgramId' },
          { name: 'LendChainBorrowerNotMatch' },
          { name: 'InvalidRelayer' },
        ],
      },
    },
    {
      name: 'RepayOfferError',
      type: {
        kind: 'enum',
        variants: [
          { name: 'InvalidMintAsset' },
          { name: 'NotEnoughAmount' },
          { name: 'LoanOfferIsNotAvailable' },
          { name: 'InvalidLendAmount' },
          { name: 'InvalidBorrower' },
          { name: 'InvalidCollateralAmount' },
          { name: 'InvalidOfferStatus' },
          { name: 'InvalidLender' },
          { name: 'TimeUnmetException' },
        ],
      },
    },
    {
      name: 'LiquidateOfferError',
      type: {
        kind: 'enum',
        variants: [
          { name: 'InvalidLender' },
          { name: 'InvalidBorrower' },
          { name: 'InvalidOfferStatus' },
          { name: 'InvalidLendAmount' },
          { name: 'NotEnoughAmount' },
          { name: 'InvalidMintAsset' },
          { name: 'InvalidSystem' },
        ],
      },
    },
    {
      name: 'WormholeError',
      type: {
        kind: 'enum',
        variants: [
          { name: 'InvalidOwner' },
          { name: 'InvalidSystem' },
          { name: 'InvalidForeignEmitter' },
          { name: 'InvalidMessage' },
          { name: 'NotSupportThisChainId' },
          { name: 'InvalidSequence' },
          { name: 'InvalidWormholeFeeCollector' },
          { name: 'InvalidWormholeConfig' },
        ],
      },
    },
    {
      name: 'EmitterAccountError',
      type: {
        kind: 'enum',
        variants: [{ name: 'InvalidOwner' }, { name: 'InvalidChainId' }],
      },
    },
    {
      name: 'ParseVaaError',
      type: {
        kind: 'enum',
        variants: [
          { name: 'InvalidTargetChain' },
          { name: 'InvalidCollateralAmount' },
          { name: 'InvalidCollateralDecimal' },
          { name: 'InvalidForeignEmitter' },
          { name: 'InvalidLendAmount' },
          { name: 'InvalidRemainingCollateralAmount' },
          { name: 'InvalidDepositAmount' },
          { name: 'InvalidInterest' },
          { name: 'InvalidLiquidatingPrice' },
          { name: 'InvalidLiquidatingAt' },
        ],
      },
    },
    {
      name: 'WormholeMessage',
      type: {
        kind: 'enum',
        variants: [
          { name: 'Message', fields: [{ name: 'payload', type: 'bytes' }] },
        ],
      },
    },
  ],
  events: [
    {
      name: 'InitSettingAccountEvent',
      fields: [
        { name: 'amount', type: 'u64', index: false },
        { name: 'duration', type: 'u64', index: false },
        { name: 'owner', type: 'publicKey', index: false },
        { name: 'receiver', type: 'publicKey', index: false },
        { name: 'tierId', type: 'string', index: false },
        { name: 'lenderFeePercent', type: 'f64', index: false },
        { name: 'borrowerFeePercent', type: 'f64', index: false },
      ],
    },
    {
      name: 'EditSettingAccountEvent',
      fields: [
        { name: 'receiver', type: 'publicKey', index: false },
        { name: 'tierId', type: 'string', index: false },
        { name: 'amount', type: 'u64', index: false },
        { name: 'duration', type: 'u64', index: false },
        { name: 'lenderFeePercent', type: 'f64', index: false },
      ],
    },
    {
      name: 'CloseSettingAccountEvent',
      fields: [{ name: 'tierId', type: 'string', index: false }],
    },
    {
      name: 'InitAssetEvent',
      fields: [
        { name: 'tokenMint', type: 'publicKey', index: false },
        { name: 'maxPriceAgeSeconds', type: 'u64', index: false },
        { name: 'decimals', type: 'u8', index: false },
        { name: 'isCollateral', type: 'bool', index: false },
        { name: 'isLend', type: 'bool', index: false },
        { name: 'priceFeedId', type: 'string', index: false },
        { name: 'priceFeedAccount', type: 'publicKey', index: false },
        { name: 'bump', type: 'u8', index: false },
        { name: 'name', type: 'string', index: false },
        {
          name: 'tokenAddress',
          type: { option: { array: ['u8', 32] } },
          index: false,
        },
        { name: 'chainId', type: 'u16', index: false },
      ],
    },
    {
      name: 'EditAssetEvent',
      fields: [
        { name: 'tokenMint', type: 'publicKey', index: false },
        { name: 'maxPriceAgeSeconds', type: 'u64', index: false },
        { name: 'decimals', type: 'u8', index: false },
        { name: 'isCollateral', type: 'bool', index: false },
        { name: 'isLend', type: 'bool', index: false },
        { name: 'priceFeedId', type: 'string', index: false },
        { name: 'priceFeedAccount', type: 'publicKey', index: false },
        { name: 'bump', type: 'u8', index: false },
        { name: 'name', type: 'string', index: false },
      ],
    },
    {
      name: 'CreateLendOfferEvent',
      fields: [
        { name: 'lender', type: 'publicKey', index: false },
        { name: 'interest', type: 'u16', index: false },
        { name: 'lenderFeePercent', type: 'f64', index: false },
        { name: 'duration', type: 'u64', index: false },
        { name: 'amount', type: 'u64', index: false },
        { name: 'offerId', type: 'string', index: false },
        { name: 'tierId', type: 'string', index: false },
      ],
    },
    {
      name: 'EditLendOfferEvent',
      fields: [
        { name: 'lender', type: 'publicKey', index: false },
        { name: 'interest', type: 'u16', index: false },
        { name: 'lenderFeePercent', type: 'f64', index: false },
        { name: 'duration', type: 'u64', index: false },
        { name: 'amount', type: 'u64', index: false },
        { name: 'offerId', type: 'string', index: false },
      ],
    },
    {
      name: 'LendOfferCancelRequestEvent',
      fields: [
        { name: 'lender', type: 'publicKey', index: false },
        { name: 'interest', type: 'u16', index: false },
        { name: 'lenderFeePercent', type: 'f64', index: false },
        { name: 'duration', type: 'u64', index: false },
        { name: 'amount', type: 'u64', index: false },
        { name: 'offerId', type: 'string', index: false },
      ],
    },
    {
      name: 'LendOfferCanceledEvent',
      fields: [
        { name: 'lender', type: 'publicKey', index: false },
        { name: 'interest', type: 'u16', index: false },
        { name: 'lenderFeePercent', type: 'f64', index: false },
        { name: 'duration', type: 'u64', index: false },
        { name: 'amount', type: 'u64', index: false },
        { name: 'offerId', type: 'string', index: false },
      ],
    },
    {
      name: 'LoanOfferCreateRequestEvent',
      fields: [
        { name: 'tierId', type: 'string', index: false },
        { name: 'lendOfferId', type: 'string', index: false },
        { name: 'interest', type: 'u16', index: false },
        { name: 'borrowAmount', type: 'u64', index: false },
        { name: 'lenderFeePercent', type: 'f64', index: false },
        { name: 'duration', type: 'u64', index: false },
        { name: 'lendMintToken', type: 'publicKey', index: false },
        { name: 'lender', type: 'publicKey', index: false },
        { name: 'offerId', type: 'string', index: false },
        { name: 'borrower', type: 'publicKey', index: false },
        { name: 'collateralMintToken', type: 'publicKey', index: false },
        { name: 'collateralAmount', type: 'u64', index: false },
        { name: 'status', type: { defined: 'LoanOfferStatus' }, index: false },
        { name: 'borrowerFeePercent', type: 'f64', index: false },
        { name: 'startedAt', type: 'i64', index: false },
      ],
    },
    {
      name: 'RequestCreateLoanEvent',
      fields: [
        { name: 'loanId', type: 'string', index: false },
        { name: 'offerId', type: 'string', index: false },
        { name: 'borrowAmount', type: 'u64', index: false },
        { name: 'duration', type: 'u64', index: false },
        { name: 'collateralAmount', type: 'u64', index: false },
        { name: 'lendToken', type: 'publicKey', index: false },
        { name: 'collateralToken', type: 'string', index: false },
        { name: 'lender', type: 'publicKey', index: false },
        { name: 'lendChainBorrower', type: 'publicKey', index: false },
        { name: 'startedAt', type: 'i64', index: false },
        { name: 'interest', type: 'u16', index: false },
        { name: 'lenderFeePercent', type: 'f64', index: false },
        { name: 'borrowerFeePercent', type: 'f64', index: false },
        { name: 'status', type: { defined: 'LoanOfferStatus' }, index: false },
      ],
    },
    {
      name: 'LoanOfferUpdateEvent',
      fields: [
        { name: 'tierId', type: 'string', index: false },
        { name: 'lendOfferId', type: 'string', index: false },
        { name: 'interest', type: 'u16', index: false },
        { name: 'borrowAmount', type: 'u64', index: false },
        { name: 'lenderFeePercent', type: 'f64', index: false },
        { name: 'duration', type: 'u64', index: false },
        { name: 'lendMintToken', type: 'publicKey', index: false },
        { name: 'lender', type: 'publicKey', index: false },
        { name: 'offerId', type: 'string', index: false },
        { name: 'borrower', type: 'publicKey', index: false },
        { name: 'collateralMintToken', type: 'publicKey', index: false },
        { name: 'collateralAmount', type: 'u64', index: false },
        { name: 'status', type: { defined: 'LoanOfferStatus' }, index: false },
        { name: 'borrowerFeePercent', type: 'f64', index: false },
        { name: 'startedAt', type: 'i64', index: false },
      ],
    },
    {
      name: 'WithdrawCollateralEvent',
      fields: [
        { name: 'borrower', type: 'publicKey', index: false },
        { name: 'withdrawAmount', type: 'u64', index: false },
        { name: 'loanOfferId', type: 'string', index: false },
        { name: 'collateralAmount', type: 'u64', index: false },
      ],
    },
    {
      name: 'UnhealthyRatioDetectedEvent',
      fields: [
        { name: 'borrower', type: 'publicKey', index: false },
        { name: 'withdrawAmount', type: 'u64', index: false },
        { name: 'loanOfferId', type: 'string', index: false },
        { name: 'collateralAmount', type: 'u64', index: false },
      ],
    },
    {
      name: 'LoanOfferExpiredEvent',
      fields: [
        { name: 'borrower', type: 'publicKey', index: false },
        { name: 'withdrawAmount', type: 'u64', index: false },
        { name: 'loanOfferId', type: 'string', index: false },
        { name: 'collateralAmount', type: 'u64', index: false },
      ],
    },
    {
      name: 'DepositCollateralLoanOfferEvent',
      fields: [
        { name: 'tierId', type: 'string', index: false },
        { name: 'lendOfferId', type: 'string', index: false },
        { name: 'interest', type: 'u16', index: false },
        { name: 'borrowAmount', type: 'u64', index: false },
        { name: 'lenderFeePercent', type: 'f64', index: false },
        { name: 'duration', type: 'u64', index: false },
        { name: 'lendMintToken', type: 'publicKey', index: false },
        { name: 'lender', type: 'publicKey', index: false },
        { name: 'offerId', type: 'string', index: false },
        { name: 'borrower', type: 'publicKey', index: false },
        { name: 'collateralMintToken', type: 'publicKey', index: false },
        { name: 'collateralAmount', type: 'u64', index: false },
        { name: 'status', type: { defined: 'LoanOfferStatus' }, index: false },
        { name: 'borrowerFeePercent', type: 'f64', index: false },
        { name: 'startedAt', type: 'i64', index: false },
      ],
    },
    {
      name: 'LiquidatingCollateralEvent',
      fields: [
        { name: 'offerId', type: 'string', index: false },
        { name: 'liquidatingPrice', type: { option: 'f64' }, index: false },
        { name: 'liquidatingAt', type: { option: 'i64' }, index: false },
      ],
    },
    {
      name: 'LiquidatingCollateralLoanEvent',
      fields: [
        { name: 'loanId', type: 'string', index: false },
        { name: 'liquidatingPrice', type: { option: 'f64' }, index: false },
        { name: 'liquidatingAt', type: { option: 'i64' }, index: false },
        { name: 'collateralChainId', type: 'u16', index: false },
        { name: 'collateralAmount', type: 'u64', index: false },
        { name: 'collateralToken', type: 'string', index: false },
      ],
    },
    {
      name: 'LiquidatedCollateralLoanEvent',
      fields: [
        { name: 'lender', type: 'publicKey', index: false },
        { name: 'lendChainBorrower', type: 'publicKey', index: false },
        { name: 'loanId', type: 'string', index: false },
        { name: 'swappedAmount', type: 'u64', index: false },
        { name: 'status', type: { defined: 'LoanOfferStatus' }, index: false },
        { name: 'liquidatedPrice', type: 'u64', index: false },
        { name: 'liquidatedTx', type: 'string', index: false },
        { name: 'remainingFundToBorrower', type: 'u64', index: false },
      ],
    },
    {
      name: 'SystemRepayLoanOfferEvent',
      fields: [
        { name: 'lender', type: 'publicKey', index: false },
        { name: 'borrower', type: 'publicKey', index: false },
        { name: 'interest', type: 'u16', index: false },
        { name: 'loanAmount', type: 'u64', index: false },
        { name: 'collateralAmount', type: 'u64', index: false },
        { name: 'loanOfferId', type: 'string', index: false },
        { name: 'tierId', type: 'string', index: false },
        { name: 'status', type: { defined: 'LoanOfferStatus' }, index: false },
      ],
    },
    {
      name: 'BorrowerPaidEvent',
      fields: [
        { name: 'lender', type: 'publicKey', index: false },
        { name: 'lendChainBorrower', type: 'publicKey', index: false },
        { name: 'collateralAmount', type: 'u64', index: false },
        { name: 'lendToken', type: 'publicKey', index: false },
        { name: 'collateralToken', type: 'string', index: false },
        { name: 'loanId', type: 'string', index: false },
        { name: 'repayAmount', type: 'u64', index: false },
        { name: 'status', type: { defined: 'LoanOfferStatus' }, index: false },
        { name: 'interest', type: 'u16', index: false },
        { name: 'tierId', type: 'string', index: false },
      ],
    },
    {
      name: 'SystemFinishLoanOfferEvent',
      fields: [
        { name: 'system', type: 'publicKey', index: false },
        { name: 'lender', type: 'publicKey', index: false },
        { name: 'borrower', type: 'publicKey', index: false },
        { name: 'interest', type: 'u16', index: false },
        { name: 'loanAmount', type: 'u64', index: false },
        { name: 'loanOfferId', type: 'string', index: false },
        { name: 'tierId', type: 'string', index: false },
        { name: 'status', type: { defined: 'LoanOfferStatus' }, index: false },
      ],
    },
    {
      name: 'SystemRevertEvent',
      fields: [
        { name: 'offerId', type: 'string', index: false },
        { name: 'status', type: { defined: 'LoanOfferStatus' }, index: false },
      ],
    },
    {
      name: 'InitForeignEmitterEvent',
      fields: [
        { name: 'chainId', type: 'u16', index: false },
        { name: 'contractAddress', type: 'string', index: false },
        { name: 'emitterAddress', type: 'string', index: false },
        { name: 'crossChainFee', type: 'u64', index: false },
      ],
    },
    {
      name: 'RequestCancelCollateralHolderEvent',
      fields: [
        { name: 'collateralChainId', type: 'u16', index: false },
        { name: 'collateralChainAddress', type: 'string', index: false },
        { name: 'offerId', type: 'string', index: false },
        { name: 'lendChainBorrower', type: 'publicKey', index: false },
      ],
    },
    {
      name: 'DepositCollateralLoanEvent',
      fields: [
        { name: 'collateralChainId', type: 'u16', index: false },
        { name: 'collateralChainAddress', type: 'string', index: false },
        { name: 'loanId', type: 'string', index: false },
        { name: 'depositAmount', type: 'u64', index: false },
        { name: 'collateralAmount', type: 'u64', index: false },
        { name: 'collateralToken', type: 'string', index: false },
        { name: 'lendChainBorrower', type: 'publicKey', index: false },
      ],
    },
    {
      name: 'WithdrawCollateralLoanEvent',
      fields: [
        { name: 'collateralChainId', type: 'u16', index: false },
        { name: 'collateralChainAddress', type: 'string', index: false },
        { name: 'loanId', type: 'string', index: false },
        { name: 'withdrawAmount', type: 'u64', index: false },
        { name: 'collateralAmount', type: 'u64', index: false },
        { name: 'collateralToken', type: 'string', index: false },
        { name: 'lendChainBorrower', type: 'publicKey', index: false },
      ],
    },
    {
      name: 'CollateralCreatedEvent',
      fields: [
        { name: 'offerId', type: 'string', index: false },
        { name: 'lendChainId', type: 'u16', index: false },
        { name: 'lendAmount', type: 'u64', index: false },
        { name: 'collateralChainBorrower', type: 'publicKey', index: false },
        { name: 'collateralToken', type: 'publicKey', index: false },
        { name: 'collateralAmount', type: 'u64', index: false },
        { name: 'startedAt', type: 'i64', index: false },
        { name: 'lendChainBorrower', type: 'string', index: false },
        {
          name: 'status',
          type: { defined: 'CollateralHolderStatus' },
          index: false,
        },
      ],
    },
    {
      name: 'DepositCollateralHolderEvent',
      fields: [
        { name: 'offerId', type: 'string', index: false },
        { name: 'lendChainId', type: 'u16', index: false },
        { name: 'collateralChainBorrower', type: 'publicKey', index: false },
        { name: 'collateralToken', type: 'publicKey', index: false },
        { name: 'depositAmount', type: 'u64', index: false },
        { name: 'startedAt', type: 'i64', index: false },
        {
          name: 'status',
          type: { defined: 'CollateralHolderStatus' },
          index: false,
        },
        { name: 'collateralAmount', type: 'u64', index: false },
      ],
    },
    {
      name: 'WithdrawCollateralHolderEvent',
      fields: [
        { name: 'offerId', type: 'string', index: false },
        { name: 'lendChainId', type: 'u16', index: false },
        { name: 'withdrawAmount', type: 'u64', index: false },
        { name: 'collateralChainBorrower', type: 'publicKey', index: false },
        { name: 'collateralToken', type: 'publicKey', index: false },
        { name: 'collateralAmount', type: 'u64', index: false },
        { name: 'startedAt', type: 'i64', index: false },
        {
          name: 'status',
          type: { defined: 'CollateralHolderStatus' },
          index: false,
        },
      ],
    },
    {
      name: 'RefundCollateralHolderEvent',
      fields: [
        { name: 'offerId', type: 'string', index: false },
        { name: 'lendChainId', type: 'u16', index: false },
        { name: 'collateralChainBorrower', type: 'publicKey', index: false },
        { name: 'startedAt', type: 'i64', index: false },
        { name: 'collateralAmount', type: 'u64', index: false },
        { name: 'collateralToken', type: 'publicKey', index: false },
      ],
    },
    {
      name: 'CollateralHolderCancelledEvent',
      fields: [
        { name: 'offerId', type: 'string', index: false },
        { name: 'collateralChainBorrower', type: 'publicKey', index: false },
        { name: 'lendChainId', type: 'u16', index: false },
        { name: 'collateralAmount', type: 'u64', index: false },
      ],
    },
    {
      name: 'LiquidateCollateralHolderEvent',
      fields: [
        { name: 'offerId', type: 'string', index: false },
        { name: 'liquidatingPrice', type: 'u64', index: false },
        { name: 'liquidatingAt', type: 'u64', index: false },
        { name: 'lendChainId', type: 'u16', index: false },
        { name: 'collateralChainBorrower', type: 'publicKey', index: false },
        { name: 'startedAt', type: 'i64', index: false },
        { name: 'collateralAmount', type: 'u64', index: false },
      ],
    },
  ],
  errors: [
    { code: 6000, name: 'InvalidTierId', msg: 'Invalid tier id' },
    { code: 6001, name: 'InvalidOwner', msg: 'Invalid owner account' },
  ],
};
